// 魔王城の英文法問題。各難易度50問。
// 形式: { q:空所(___)を含む英文, choices:[英語の選択肢4つ], answer:正解のindex, ja:完成文の和訳, note:日本語の簡単な解説 }
const GRAMMAR_DATA = {
  500: [
    { q: "I ___ a student.", choices: ["am", "is", "are", "be"], answer: 0, ja: "私は学生です。", note: "主語Iにはam" },
    { q: "She ___ my sister.", choices: ["am", "is", "are", "do"], answer: 1, ja: "彼女は私の姉妹です。", note: "三人称単数にはis" },
    { q: "They ___ in the park.", choices: ["am", "is", "are", "be"], answer: 2, ja: "彼らは公園にいます。", note: "主語theyにはare" },
    { q: "He ___ to school every day.", choices: ["go", "goes", "going", "gone"], answer: 1, ja: "彼は毎日学校へ行きます。", note: "三単現はgoes" },
    { q: "I have two ___.", choices: ["dog", "dogs", "doges", "dog's"], answer: 1, ja: "私は犬を2匹飼っています。", note: "複数形はdogs" },
    { q: "This is ___ book.", choices: ["I", "my", "me", "mine"], answer: 1, ja: "これは私の本です。", note: "名詞の前は所有格my" },
    { q: "That bag is ___.", choices: ["my", "me", "mine", "I"], answer: 2, ja: "あのかばんは私のものです。", note: "単独で「私のもの」はmine" },
    { q: "___ you like coffee?", choices: ["Do", "Does", "Are", "Is"], answer: 0, ja: "あなたはコーヒーが好きですか。", note: "一般動詞・主語youの疑問はDo" },
    { q: "___ she play tennis?", choices: ["Do", "Does", "Is", "Are"], answer: 1, ja: "彼女はテニスをしますか。", note: "三単現の疑問はDoes" },
    { q: "I am ___ TV now.", choices: ["watch", "watches", "watching", "watched"], answer: 2, ja: "私は今テレビを見ています。", note: "現在進行形はbe+~ing" },
    { q: "We ___ soccer yesterday.", choices: ["play", "plays", "played", "playing"], answer: 2, ja: "私たちは昨日サッカーをしました。", note: "過去形はplayed" },
    { q: "He can ___ very fast.", choices: ["run", "runs", "running", "ran"], answer: 0, ja: "彼はとても速く走れます。", note: "助動詞can+動詞の原形" },
    { q: "There ___ a cat on the bed.", choices: ["is", "are", "am", "be"], answer: 0, ja: "ベッドの上に猫が1匹います。", note: "単数はThere is" },
    { q: "There ___ many books here.", choices: ["is", "are", "am", "be"], answer: 1, ja: "ここにはたくさんの本があります。", note: "複数はThere are" },
    { q: "I go to school ___ bus.", choices: ["in", "on", "by", "at"], answer: 2, ja: "私はバスで学校へ行きます。", note: "交通手段はby" },
    { q: "The cat is ___ the table.", choices: ["on", "in", "at", "of"], answer: 0, ja: "猫はテーブルの上にいます。", note: "面の上はon" },
    { q: "I get up ___ seven.", choices: ["in", "on", "at", "to"], answer: 2, ja: "私は7時に起きます。", note: "時刻はat" },
    { q: "My birthday is ___ May.", choices: ["in", "on", "at", "by"], answer: 0, ja: "私の誕生日は5月です。", note: "月はin" },
    { q: "We have a party ___ Sunday.", choices: ["in", "on", "at", "to"], answer: 1, ja: "私たちは日曜日にパーティーをします。", note: "曜日はon" },
    { q: "___ is your name?", choices: ["What", "Who", "Where", "When"], answer: 0, ja: "あなたの名前は何ですか。", note: "名前を聞く→What" },
    { q: "___ are you from?", choices: ["What", "Where", "Who", "Why"], answer: 1, ja: "あなたはどこの出身ですか。", note: "出身を聞く→Where" },
    { q: "___ do you go to bed?", choices: ["What", "Where", "When", "Who"], answer: 2, ja: "あなたはいつ寝ますか。", note: "時を聞く→When" },
    { q: "___ is that man?", choices: ["What", "Who", "Where", "When"], answer: 1, ja: "あの男性は誰ですか。", note: "人を聞く→Who" },
    { q: "This pen is ___ than that one.", choices: ["long", "longer", "longest", "more long"], answer: 1, ja: "このペンはあのペンより長いです。", note: "比較級は-er" },
    { q: "He is the ___ boy in the class.", choices: ["tall", "taller", "tallest", "more tall"], answer: 2, ja: "彼はクラスで一番背が高い男の子です。", note: "最上級は-est" },
    { q: "I like apples ___ oranges.", choices: ["and", "but", "or", "so"], answer: 0, ja: "私はりんごとオレンジが好きです。", note: "並列はand" },
    { q: "I'm tired, ___ I'll go to bed.", choices: ["and", "but", "so", "or"], answer: 2, ja: "私は疲れたので、寝ます。", note: "だから→so" },
    { q: "She is kind ___ everyone.", choices: ["to", "at", "in", "of"], answer: 0, ja: "彼女はみんなに親切です。", note: "be kind to 〜に親切" },
    { q: "I'm good ___ math.", choices: ["in", "at", "on", "to"], answer: 1, ja: "私は数学が得意です。", note: "be good at 〜が得意" },
    { q: "Look ___ the blackboard.", choices: ["at", "in", "on", "to"], answer: 0, ja: "黒板を見なさい。", note: "look at 〜を見る" },
    { q: "___ books are these?", choices: ["Who", "Whose", "Which", "What"], answer: 1, ja: "これらは誰の本ですか。", note: "誰の→Whose" },
    { q: "___ do you want, this or that?", choices: ["What", "Which", "Who", "Where"], answer: 1, ja: "これとあれ、どちらが欲しいですか。", note: "二択はWhich" },
    { q: "He doesn't ___ meat.", choices: ["eat", "eats", "ate", "eating"], answer: 0, ja: "彼は肉を食べません。", note: "doesn't+原形" },
    { q: "___ the window, please.", choices: ["Open", "Opens", "Opened", "Opening"], answer: 0, ja: "窓を開けてください。", note: "命令文は原形で始める" },
    { q: "Let's ___ to the movies.", choices: ["go", "goes", "going", "went"], answer: 0, ja: "映画を見に行きましょう。", note: "Let's+原形" },
    { q: "I want ___ water.", choices: ["a", "an", "some", "many"], answer: 2, ja: "私は水が欲しいです。", note: "数えられない名詞にはsome" },
    { q: "She has ___ umbrella.", choices: ["a", "an", "the", "some"], answer: 1, ja: "彼女は傘を持っています。", note: "母音の前はan" },
    { q: "He is ___ honest man.", choices: ["a", "an", "the", "some"], answer: 1, ja: "彼は正直な男性です。", note: "発音が母音で始まる→an" },
    { q: "My mother ___ cooking now.", choices: ["is", "are", "am", "do"], answer: 0, ja: "母は今料理をしています。", note: "進行形のbe・三単現→is" },
    { q: "I ___ happy yesterday.", choices: ["am", "is", "was", "were"], answer: 2, ja: "私は昨日幸せでした。", note: "過去be・I→was" },
    { q: "They ___ at home last night.", choices: ["was", "were", "are", "is"], answer: 1, ja: "彼らは昨夜家にいました。", note: "過去be・they→were" },
    { q: "Can you swim? — Yes, I ___.", choices: ["am", "do", "can", "is"], answer: 2, ja: "泳げますか。— はい、泳げます。", note: "canで聞かれたらcanで答える" },
    { q: "Does he like music? — No, he ___.", choices: ["isn't", "doesn't", "don't", "aren't"], answer: 1, ja: "彼は音楽が好きですか。— いいえ、好きではありません。", note: "doesで聞かれたらdoesn't" },
    { q: "How ___ apples do you have?", choices: ["much", "many", "long", "old"], answer: 1, ja: "りんごをいくつ持っていますか。", note: "数えられる名詞の数→many" },
    { q: "How ___ water do you need?", choices: ["many", "much", "old", "far"], answer: 1, ja: "どれくらいの水が必要ですか。", note: "量→much" },
    { q: "She lives ___ Tokyo.", choices: ["in", "on", "at", "to"], answer: 0, ja: "彼女は東京に住んでいます。", note: "都市・国はin" },
    { q: "Please be quiet ___ the library.", choices: ["in", "on", "at", "of"], answer: 0, ja: "図書館では静かにしてください。", note: "建物の中はin" },
    { q: "This is the ___ movie of the year.", choices: ["good", "better", "best", "well"], answer: 2, ja: "これは今年最高の映画です。", note: "goodの最上級はbest" },
    { q: "I ___ like dogs.", choices: ["am", "do", "does", "is"], answer: 1, ja: "私は犬が本当に好きです。", note: "一般動詞の文。be動詞は使わない" },
    { q: "Tom and I ___ good friends.", choices: ["am", "is", "are", "be"], answer: 2, ja: "トムと私は仲のよい友達です。", note: "複数主語→are" },
  ],
  700: [
    { q: "I have ___ in this town for ten years.", choices: ["live", "lived", "living", "lives"], answer: 1, ja: "私はこの町に10年間住んでいます。", note: "現在完了 have+過去分詞" },
    { q: "She has ___ to Paris twice.", choices: ["be", "been", "being", "was"], answer: 1, ja: "彼女はパリに2回行ったことがあります。", note: "have been (経験)" },
    { q: "Have you ___ your homework yet?", choices: ["do", "did", "done", "doing"], answer: 2, ja: "もう宿題は終わりましたか。", note: "have done" },
    { q: "This letter was ___ by Tom.", choices: ["write", "wrote", "written", "writing"], answer: 2, ja: "この手紙はトムによって書かれました。", note: "受動態 be+過去分詞" },
    { q: "English is ___ in many countries.", choices: ["speak", "spoke", "spoken", "speaking"], answer: 2, ja: "英語は多くの国で話されています。", note: "be spoken (受動態)" },
    { q: "The window ___ broken yesterday.", choices: ["is", "was", "were", "be"], answer: 1, ja: "窓は昨日割られました。", note: "受動態の過去・単数→was" },
    { q: "The man ___ is talking is my teacher.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "話している男性は私の先生です。", note: "先行詞が人で主語→who" },
    { q: "I have a book ___ is very interesting.", choices: ["who", "which", "whose", "where"], answer: 1, ja: "私はとても面白い本を持っています。", note: "先行詞が物→which" },
    { q: "This is the house ___ I was born.", choices: ["which", "who", "where", "when"], answer: 2, ja: "ここは私が生まれた家です。", note: "場所を表す関係副詞→where" },
    { q: "I want ___ a doctor.", choices: ["be", "to be", "being", "been"], answer: 1, ja: "私は医者になりたいです。", note: "want to+原形" },
    { q: "He decided ___ abroad.", choices: ["study", "to study", "studying", "studied"], answer: 1, ja: "彼は留学することを決めました。", note: "decide to+原形" },
    { q: "I enjoy ___ books.", choices: ["read", "to read", "reading", "reads"], answer: 2, ja: "私は読書を楽しみます。", note: "enjoy+動名詞" },
    { q: "She is good at ___.", choices: ["sing", "to sing", "singing", "sang"], answer: 2, ja: "彼女は歌うのが得意です。", note: "前置詞at+動名詞" },
    { q: "Would you mind ___ the door?", choices: ["open", "to open", "opening", "opened"], answer: 2, ja: "ドアを開けていただけますか。", note: "mind+動名詞" },
    { q: "You ___ wear a seatbelt. It's the law.", choices: ["must", "may", "could", "would"], answer: 0, ja: "シートベルトを着用しなければなりません。法律です。", note: "義務→must" },
    { q: "It ___ rain this afternoon. Take an umbrella.", choices: ["must", "might", "can", "should"], answer: 1, ja: "午後は雨が降るかもしれません。傘を持って。", note: "弱い推量→might" },
    { q: "You ___ see a doctor if you feel sick.", choices: ["should", "must not", "can't", "would"], answer: 0, ja: "具合が悪いなら医者に診てもらうべきです。", note: "助言→should" },
    { q: "He is ___ taller than his brother.", choices: ["very", "much", "more", "most"], answer: 1, ja: "彼は兄よりずっと背が高いです。", note: "比較級の強調→much" },
    { q: "This is ___ interesting than that.", choices: ["more", "most", "much", "very"], answer: 0, ja: "これはあれより面白いです。", note: "長い形容詞の比較級→more" },
    { q: "She runs ___ in her class.", choices: ["fast", "faster", "fastest", "the fastest"], answer: 3, ja: "彼女はクラスで一番速く走ります。", note: "副詞の最上級→the fastest" },
    { q: "I'll call you ___ I arrive.", choices: ["when", "because", "but", "so"], answer: 0, ja: "着いたら電話します。", note: "〜したら→when" },
    { q: "Wait here ___ I come back.", choices: ["since", "until", "during", "while"], answer: 1, ja: "私が戻るまでここで待っていて。", note: "〜まで(ずっと)→until" },
    { q: "He couldn't come ___ he was sick.", choices: ["because", "so", "but", "though"], answer: 0, ja: "彼は病気だったので来られませんでした。", note: "理由→because" },
    { q: "___ it was raining, we went out.", choices: ["Because", "Although", "So", "If"], answer: 1, ja: "雨が降っていたが、私たちは出かけました。", note: "〜だけれど→Although" },
    { q: "Do you know ___ he lives?", choices: ["where", "what", "which", "whose"], answer: 0, ja: "彼がどこに住んでいるか知っていますか。", note: "間接疑問・場所→where" },
    { q: "Tell me ___ this means.", choices: ["what", "who", "where", "when"], answer: 0, ja: "これがどういう意味か教えて。", note: "間接疑問→what" },
    { q: "If it ___ tomorrow, I'll stay home.", choices: ["rain", "rains", "rained", "raining"], answer: 1, ja: "明日雨なら家にいます。", note: "条件のifは現在形→rains" },
    { q: "I've known her ___ 2010.", choices: ["for", "since", "from", "during"], answer: 1, ja: "私は2010年から彼女を知っています。", note: "起点→since" },
    { q: "We've been friends ___ five years.", choices: ["since", "for", "from", "in"], answer: 1, ja: "私たちは5年間友達です。", note: "期間→for" },
    { q: "The book ___ I bought was expensive.", choices: ["who", "which", "whose", "where"], answer: 1, ja: "私が買った本は高かったです。", note: "物・目的格→which" },
    { q: "I know a girl ___ father is a doctor.", choices: ["who", "which", "whose", "whom"], answer: 2, ja: "私は父親が医者の女の子を知っています。", note: "所有→whose" },
    { q: "She told me ___ late.", choices: ["not be", "not to be", "to not be", "be not"], answer: 1, ja: "彼女は私に遅れないように言いました。", note: "tell 人 not to do" },
    { q: "It is important ___ English.", choices: ["study", "to study", "studying", "studied"], answer: 1, ja: "英語を勉強することは大切です。", note: "It is ... to do" },
    { q: "He kept ___ even when it got dark.", choices: ["work", "to work", "working", "worked"], answer: 2, ja: "暗くなっても彼は働き続けました。", note: "keep+動名詞(〜し続ける)" },
    { q: "I'm looking forward to ___ you.", choices: ["see", "to see", "seeing", "saw"], answer: 2, ja: "あなたに会うのを楽しみにしています。", note: "look forward to+動名詞" },
    { q: "The cake ___ by my mother.", choices: ["made", "was made", "is making", "makes"], answer: 1, ja: "そのケーキは母が作りました。", note: "受動態→was made" },
    { q: "These cars are ___ in Japan.", choices: ["make", "made", "making", "makes"], answer: 1, ja: "これらの車は日本で作られています。", note: "be made (受動態)" },
    { q: "He has ___ finished his work.", choices: ["yet", "already", "ago", "since"], answer: 1, ja: "彼はもう仕事を終えました。", note: "完了・肯定→already" },
    { q: "I haven't seen him ___.", choices: ["already", "yet", "ago", "still"], answer: 1, ja: "私はまだ彼に会っていません。", note: "完了・否定/疑問→yet" },
    { q: "How long ___ you studied English?", choices: ["have", "has", "did", "do"], answer: 0, ja: "どのくらい英語を勉強していますか。", note: "現在完了の疑問・you→have" },
    { q: "She ___ just left.", choices: ["has", "have", "is", "was"], answer: 0, ja: "彼女はちょうど出かけたところです。", note: "三単現の完了→has" },
    { q: "If I ___ time, I would help you.", choices: ["have", "has", "had", "having"], answer: 2, ja: "時間があれば手伝うのに。", note: "仮定法過去→had" },
    { q: "I wish I ___ rich.", choices: ["am", "was", "were", "be"], answer: 2, ja: "私が金持ちならなあ。", note: "仮定法のwishはwere" },
    { q: "You had better ___ now.", choices: ["go", "to go", "going", "went"], answer: 0, ja: "もう行ったほうがいい。", note: "had better+原形" },
    { q: "He made me ___ it again.", choices: ["do", "to do", "doing", "did"], answer: 0, ja: "彼は私にもう一度それをやらせた。", note: "使役make+原形" },
    { q: "I saw her ___ the room.", choices: ["enter", "to enter", "entered", "enters"], answer: 0, ja: "私は彼女が部屋に入るのを見た。", note: "知覚動詞+原形" },
    { q: "Neither John ___ Mary came.", choices: ["or", "nor", "and", "but"], answer: 1, ja: "ジョンもメアリーも来なかった。", note: "neither A nor B" },
    { q: "Both Tom ___ Ken are kind.", choices: ["or", "nor", "and", "but"], answer: 2, ja: "トムもケンも親切だ。", note: "both A and B" },
    { q: "This is the best movie ___ I've ever seen.", choices: ["who", "what", "that", "where"], answer: 2, ja: "これは私が今まで見た中で最高の映画だ。", note: "最上級の後の関係代名詞→that" },
    { q: "He spent two hours ___ the report.", choices: ["write", "to write", "writing", "wrote"], answer: 2, ja: "彼は報告書を書くのに2時間を費やした。", note: "spend 時間+動名詞" },
  ],
  900: [
    { q: "If I ___ harder, I would have passed.", choices: ["studied", "had studied", "study", "have studied"], answer: 1, ja: "もっと勉強していたら合格していただろう。", note: "仮定法過去完了 had+過去分詞" },
    { q: "If she had left earlier, she ___ the train.", choices: ["caught", "would catch", "would have caught", "catches"], answer: 2, ja: "もっと早く出ていたら電車に間に合っただろう。", note: "帰結節 would have+過去分詞" },
    { q: "___ in simple English, the book sold well.", choices: ["Write", "Written", "Writing", "To write"], answer: 1, ja: "平易な英語で書かれていたので、その本はよく売れた。", note: "受動の分詞構文→Written" },
    { q: "___ the test, he felt relieved.", choices: ["Finish", "Finished", "Having finished", "Finishes"], answer: 2, ja: "試験を終えて、彼はほっとした。", note: "完了分詞構文 Having+過去分詞" },
    { q: "Never ___ I seen such a beautiful sight.", choices: ["have", "had", "has", "did"], answer: 1, ja: "そんな美しい光景は見たことがなかった。", note: "否定語+倒置(過去完了)→had" },
    { q: "Hardly ___ he arrived when it began to rain.", choices: ["has", "had", "have", "did"], answer: 1, ja: "彼が着くやいなや雨が降り始めた。", note: "Hardly...when は過去完了の倒置" },
    { q: "It was John ___ broke the window.", choices: ["who", "which", "whom", "whose"], answer: 0, ja: "窓を割ったのはジョンだった。", note: "強調構文・人→who" },
    { q: "It was yesterday ___ I met her.", choices: ["when", "that", "which", "who"], answer: 1, ja: "私が彼女に会ったのは昨日だった。", note: "強調構文 It was 〜 that" },
    { q: "This is the reason ___ he left.", choices: ["why", "which", "where", "what"], answer: 0, ja: "これが彼が去った理由だ。", note: "理由の関係副詞→why" },
    { q: "I remember the day ___ we first met.", choices: ["why", "when", "where", "which"], answer: 1, ja: "私たちが初めて会った日を覚えている。", note: "時の関係副詞→when" },
    { q: "He has ___ working here for ten years.", choices: ["be", "been", "being", "was"], answer: 1, ja: "彼はここで10年間働いている。", note: "現在完了進行形 have been ~ing" },
    { q: "I've ___ waiting for an hour.", choices: ["been", "be", "being", "was"], answer: 0, ja: "私は1時間ずっと待っている。", note: "have been waiting" },
    { q: "Were I you, I ___ accept the offer.", choices: ["will", "would", "can", "must"], answer: 1, ja: "私があなたなら、その申し出を受けるだろう。", note: "if省略の倒置・仮定法→would" },
    { q: "Had I known, I ___ have come.", choices: ["will", "would", "can", "should"], answer: 1, ja: "知っていたら来ていただろう。", note: "Had I known の帰結→would have" },
    { q: "He talks ___ he knew everything.", choices: ["as if", "even if", "only if", "what if"], answer: 0, ja: "彼はまるで何でも知っているかのように話す。", note: "as if+仮定法(まるで〜のように)" },
    { q: "The project, ___ took years, finally ended.", choices: ["who", "which", "that", "what"], answer: 1, ja: "何年もかかったその計画がついに終わった。", note: "非制限用法・物→which" },
    { q: "___ honest, I don't agree.", choices: ["To be", "Being", "Been", "Be"], answer: 0, ja: "正直に言うと、私は賛成しません。", note: "To be honest(正直に言うと)" },
    { q: "Not until midnight ___ he come home.", choices: ["does", "did", "do", "had"], answer: 1, ja: "真夜中になって初めて彼は帰宅した。", note: "Not until+倒置(過去)→did" },
    { q: "So tired ___ he that he fell asleep.", choices: ["was", "is", "were", "did"], answer: 0, ja: "彼はとても疲れていて眠ってしまった。", note: "So+形容詞の倒置→was" },
    { q: "___ all his efforts, he failed.", choices: ["Despite", "Although", "Because", "However"], answer: 0, ja: "あらゆる努力にもかかわらず、彼は失敗した。", note: "前置詞despite+名詞" },
    { q: "He insisted that she ___ present.", choices: ["is", "be", "was", "being"], answer: 1, ja: "彼は彼女が出席すべきだと主張した。", note: "insist that+(should)原形→be" },
    { q: "It is essential that he ___ on time.", choices: ["is", "be", "was", "being"], answer: 1, ja: "彼が時間どおりであることが不可欠だ。", note: "要求・必要のthat節→原形be" },
    { q: "I'd rather you ___ not smoke here.", choices: ["do", "did", "to do", "done"], answer: 1, ja: "ここでタバコを吸わないでほしい。", note: "would rather+S+過去形→did" },
    { q: "No sooner had he sat down ___ the phone rang.", choices: ["when", "than", "then", "that"], answer: 1, ja: "彼が座るとすぐに電話が鳴った。", note: "No sooner...than" },
    { q: "___ generous, she helped everyone.", choices: ["Being", "Been", "To be", "Be"], answer: 0, ja: "寛大なので、彼女はみんなを助けた。", note: "分詞構文→Being" },
    { q: "The house ___ roof is red is mine.", choices: ["which", "whose", "that", "where"], answer: 1, ja: "屋根が赤い家が私の家だ。", note: "所有を表す→whose" },
    { q: "She is said ___ very rich.", choices: ["be", "to be", "being", "been"], answer: 1, ja: "彼女はとても金持ちだと言われている。", note: "be said to be(〜だと言われている)" },
    { q: "He is believed ___ the country.", choices: ["leave", "to have left", "leaving", "left"], answer: 1, ja: "彼は国を去ったと信じられている。", note: "過去の内容→to have+過去分詞" },
    { q: "Little ___ he know the truth.", choices: ["does", "did", "do", "had"], answer: 1, ja: "彼は真実をほとんど知らなかった。", note: "Little+倒置(過去)→did" },
    { q: "Only after the meeting ___ I understand.", choices: ["do", "did", "had", "was"], answer: 1, ja: "会議の後で初めて私は理解した。", note: "Only after+倒置(過去)→did" },
    { q: "___ from space, the earth looks blue.", choices: ["Seeing", "Seen", "To see", "See"], answer: 1, ja: "宇宙から見ると、地球は青く見える。", note: "受動の分詞構文→Seen" },
    { q: "There is no point in ___ about it.", choices: ["worry", "to worry", "worrying", "worried"], answer: 2, ja: "それを心配しても意味がない。", note: "no point in+動名詞" },
    { q: "He objected to ___ treated like a child.", choices: ["be", "being", "to be", "been"], answer: 1, ja: "彼は子供扱いされることに反対した。", note: "object to+動名詞(being)" },
    { q: "I'm used to ___ early.", choices: ["get up", "to get up", "getting up", "got up"], answer: 2, ja: "私は早起きに慣れている。", note: "be used to+動名詞(〜に慣れている)" },
    { q: "It's high time we ___.", choices: ["leave", "left", "to leave", "leaving"], answer: 1, ja: "そろそろ出発する時間だ。", note: "It's time+仮定法過去→left" },
    { q: "Whatever ___, don't give up.", choices: ["happen", "happens", "happened", "happening"], answer: 1, ja: "何が起きても、あきらめるな。", note: "Whateverの後・三単現→happens" },
    { q: "___ hard he tried, he couldn't do it.", choices: ["However", "Whatever", "Whoever", "Whenever"], answer: 0, ja: "どんなに頑張っても彼にはできなかった。", note: "However+形容詞/副詞(どんなに〜でも)" },
    { q: "The more you practice, the ___ you get.", choices: ["good", "better", "best", "well"], answer: 1, ja: "練習するほど上達する。", note: "the 比較級, the 比較級→better" },
    { q: "Scarcely had I left ___ it started to rain.", choices: ["than", "when", "then", "that"], answer: 1, ja: "私が出るやいなや雨が降り出した。", note: "Scarcely...when" },
    { q: "I would have helped, ___ I been there.", choices: ["if", "had", "have", "should"], answer: 1, ja: "そこにいたら手伝っていただろう。", note: "if省略の倒置→Had I been" },
    { q: "He acts ___ he were the boss.", choices: ["as though", "even though", "so that", "now that"], answer: 0, ja: "彼はまるで自分が上司であるかのように振る舞う。", note: "as though+仮定法" },
    { q: "Not only ___ he sing, but he also dances.", choices: ["does", "do", "did", "is"], answer: 0, ja: "彼は歌うだけでなく踊りもする。", note: "Not only+倒置・三単現→does" },
    { q: "I suggest that the plan ___ changed.", choices: ["is", "be", "was", "being"], answer: 1, ja: "私は計画を変更すべきだと提案する。", note: "suggest that+(should)be" },
    { q: "___ for your help, I would have failed.", choices: ["But", "Without", "If", "Despite"], answer: 1, ja: "あなたの助けがなければ失敗していただろう。", note: "Without+名詞(〜がなければ)" },
    { q: "He is the last person ___ tell a lie.", choices: ["who", "to", "that", "which"], answer: 1, ja: "彼は最も嘘をつきそうにない人だ。", note: "the last person to do(最も〜しそうにない)" },
    { q: "___ being tired, she finished the work.", choices: ["Despite", "Although", "In spite", "Because"], answer: 0, ja: "疲れていたが、彼女は仕事を終えた。", note: "Despite+動名詞" },
    { q: "It was not until he left ___ I realized it.", choices: ["when", "that", "which", "then"], answer: 1, ja: "彼が去って初めて私はそれに気づいた。", note: "It was not until 〜 that" },
    { q: "Such was his anger ___ he couldn't speak.", choices: ["that", "as", "than", "which"], answer: 0, ja: "彼の怒りはあまりに激しく、口がきけなかった。", note: "Such 〜 that(あまりに〜なので)" },
    { q: "I'd appreciate it if you ___ help me.", choices: ["can", "could", "will", "do"], answer: 1, ja: "手伝っていただけるとありがたいです。", note: "丁寧な仮定→could" },
    { q: "He spoke as if he ___ everything.", choices: ["knows", "knew", "known", "know"], answer: 1, ja: "彼はまるで何でも知っているかのように話した。", note: "as if+仮定法過去→knew" },
  ],
};
