// 魔王城の英文法問題。各難易度200問。
// 形式: { q:空所(___)を含む英文, choices:[英語の選択肢4つ], answer:正解のindex, ja:完成文の和訳, note:日本語の簡単な解説 }
const GRAMMAR_DATA = {
  500: [
    { q: "I ___ a student.", choices: ["am", "is", "are", "be"], answer: 0, ja: "私は学生です。", note: "主語Iにはam" },
    { q: "She ___ my sister.", choices: ["am", "is", "are", "do"], answer: 1, ja: "彼女は私の姉妹です。", note: "三人称単数にはis" },
    { q: "They ___ in the park.", choices: ["am", "is", "are", "be"], answer: 2, ja: "彼らは公園にいます。", note: "主語theyにはare" },
    { q: "He ___ to school every day.", choices: ["go", "goes", "going", "gone"], answer: 1, ja: "彼は毎日学校へ行きます。", note: "三単現はgoes" },
    { q: "I have two ___.", choices: ["dog", "dogs", "doges", "dog's"], answer: 1, ja: "私は犬を2匹飼っています。", note: "複数形はdogs" },
    { q: "This is ___ book.", choices: ["I", "my", "me", "mine"], answer: 1, ja: "これは私の本です。", note: "名詞の前は所有格my" },
    { q: "That bag is ___.", choices: ["my", "me", "mine", "I"], answer: 2, ja: "あのかばんは私のものです。", note: "単独で「私のもの」はmine" },
    { q: "___ you like coffee?", choices: ["Do", "Does", "Are", "Is"], answer: 0, ja: "あなたはコーヒーが好きですか。", note: "一般動詞・主語youの疑問はDo" },
    { q: "___ she play tennis?", choices: ["Do", "Does", "Is", "Are"], answer: 1, ja: "彼女はテニスをしますか。", note: "三単現の疑問はDoes" },
    { q: "I am ___ TV now.", choices: ["watch", "watches", "watching", "watched"], answer: 2, ja: "私は今テレビを見ています。", note: "現在進行形はbe+~ing" },
    { q: "We ___ soccer yesterday.", choices: ["play", "plays", "played", "playing"], answer: 2, ja: "私たちは昨日サッカーをしました。", note: "過去形はplayed" },
    { q: "He can ___ very fast.", choices: ["run", "runs", "running", "ran"], answer: 0, ja: "彼はとても速く走れます。", note: "助動詞can+動詞の原形" },
    { q: "There ___ a cat on the bed.", choices: ["is", "are", "am", "be"], answer: 0, ja: "ベッドの上に猫が1匹います。", note: "単数はThere is" },
    { q: "There ___ many books here.", choices: ["is", "are", "am", "be"], answer: 1, ja: "ここにはたくさんの本があります。", note: "複数はThere are" },
    { q: "I go to school ___ bus.", choices: ["in", "on", "by", "at"], answer: 2, ja: "私はバスで学校へ行きます。", note: "交通手段はby" },
    { q: "The cat is ___ the table.", choices: ["on", "in", "at", "of"], answer: 0, ja: "猫はテーブルの上にいます。", note: "面の上はon" },
    { q: "I get up ___ seven.", choices: ["in", "on", "at", "to"], answer: 2, ja: "私は7時に起きます。", note: "時刻はat" },
    { q: "My birthday is ___ May.", choices: ["in", "on", "at", "by"], answer: 0, ja: "私の誕生日は5月です。", note: "月はin" },
    { q: "We have a party ___ Sunday.", choices: ["in", "on", "at", "to"], answer: 1, ja: "私たちは日曜日にパーティーをします。", note: "曜日はon" },
    { q: "___ is your name?", choices: ["What", "Who", "Where", "When"], answer: 0, ja: "あなたの名前は何ですか。", note: "名前を聞く→What" },
    { q: "___ are you from?", choices: ["What", "Where", "Who", "Why"], answer: 1, ja: "あなたはどこの出身ですか。", note: "出身を聞く→Where" },
    { q: "___ do you go to bed?", choices: ["What", "Where", "When", "Who"], answer: 2, ja: "あなたはいつ寝ますか。", note: "時を聞く→When" },
    { q: "___ is that man?", choices: ["What", "Who", "Where", "When"], answer: 1, ja: "あの男性は誰ですか。", note: "人を聞く→Who" },
    { q: "This pen is ___ than that one.", choices: ["long", "longer", "longest", "more long"], answer: 1, ja: "このペンはあのペンより長いです。", note: "比較級は-er" },
    { q: "He is the ___ boy in the class.", choices: ["tall", "taller", "tallest", "more tall"], answer: 2, ja: "彼はクラスで一番背が高い男の子です。", note: "最上級は-est" },
    { q: "I like apples ___ oranges.", choices: ["and", "but", "or", "so"], answer: 0, ja: "私はりんごとオレンジが好きです。", note: "並列はand" },
    { q: "I'm tired, ___ I'll go to bed.", choices: ["and", "but", "so", "or"], answer: 2, ja: "私は疲れたので、寝ます。", note: "だから→so" },
    { q: "She is kind ___ everyone.", choices: ["to", "at", "in", "of"], answer: 0, ja: "彼女はみんなに親切です。", note: "be kind to 〜に親切" },
    { q: "I'm good ___ math.", choices: ["in", "at", "on", "to"], answer: 1, ja: "私は数学が得意です。", note: "be good at 〜が得意" },
    { q: "Look ___ the blackboard.", choices: ["at", "in", "on", "to"], answer: 0, ja: "黒板を見なさい。", note: "look at 〜を見る" },
    { q: "___ books are these?", choices: ["Who", "Whose", "Which", "What"], answer: 1, ja: "これらは誰の本ですか。", note: "誰の→Whose" },
    { q: "___ do you want, this or that?", choices: ["What", "Which", "Who", "Where"], answer: 1, ja: "これとあれ、どちらが欲しいですか。", note: "二択はWhich" },
    { q: "He doesn't ___ meat.", choices: ["eat", "eats", "ate", "eating"], answer: 0, ja: "彼は肉を食べません。", note: "doesn't+原形" },
    { q: "___ the window, please.", choices: ["Open", "Opens", "Opened", "Opening"], answer: 0, ja: "窓を開けてください。", note: "命令文は原形で始める" },
    { q: "Let's ___ to the movies.", choices: ["go", "goes", "going", "went"], answer: 0, ja: "映画を見に行きましょう。", note: "Let's+原形" },
    { q: "I want ___ water.", choices: ["a", "an", "some", "many"], answer: 2, ja: "私は水が欲しいです。", note: "数えられない名詞にはsome" },
    { q: "She has ___ umbrella.", choices: ["a", "an", "the", "some"], answer: 1, ja: "彼女は傘を持っています。", note: "母音の前はan" },
    { q: "He is ___ honest man.", choices: ["a", "an", "the", "some"], answer: 1, ja: "彼は正直な男性です。", note: "発音が母音で始まる→an" },
    { q: "My mother ___ cooking now.", choices: ["is", "are", "am", "do"], answer: 0, ja: "母は今料理をしています。", note: "進行形のbe・三単現→is" },
    { q: "I ___ happy yesterday.", choices: ["am", "is", "was", "were"], answer: 2, ja: "私は昨日幸せでした。", note: "過去be・I→was" },
    { q: "They ___ at home last night.", choices: ["was", "were", "are", "is"], answer: 1, ja: "彼らは昨夜家にいました。", note: "過去be・they→were" },
    { q: "Can you swim? — Yes, I ___.", choices: ["am", "do", "can", "is"], answer: 2, ja: "泳げますか。— はい、泳げます。", note: "canで聞かれたらcanで答える" },
    { q: "Does he like music? — No, he ___.", choices: ["isn't", "doesn't", "don't", "aren't"], answer: 1, ja: "彼は音楽が好きですか。— いいえ、好きではありません。", note: "doesで聞かれたらdoesn't" },
    { q: "How ___ apples do you have?", choices: ["much", "many", "long", "old"], answer: 1, ja: "りんごをいくつ持っていますか。", note: "数えられる名詞の数→many" },
    { q: "How ___ water do you need?", choices: ["many", "much", "old", "far"], answer: 1, ja: "どれくらいの水が必要ですか。", note: "量→much" },
    { q: "She lives ___ Tokyo.", choices: ["in", "on", "at", "to"], answer: 0, ja: "彼女は東京に住んでいます。", note: "都市・国はin" },
    { q: "Please be quiet ___ the library.", choices: ["in", "on", "at", "of"], answer: 0, ja: "図書館では静かにしてください。", note: "建物の中はin" },
    { q: "This is the ___ movie of the year.", choices: ["good", "better", "best", "well"], answer: 2, ja: "これは今年最高の映画です。", note: "goodの最上級はbest" },
    { q: "I ___ like dogs.", choices: ["am", "do", "does", "is"], answer: 1, ja: "私は犬が本当に好きです。", note: "一般動詞の文。be動詞は使わない" },
    { q: "Tom and I ___ good friends.", choices: ["am", "is", "are", "be"], answer: 2, ja: "トムと私は仲のよい友達です。", note: "複数主語→are" },
    { q: "You ___ my friend.", choices: ["am", "is", "are", "be"], answer: 2, ja: "あなたは私の友達です。", note: "主語youにはare" },
    { q: "We ___ happy today.", choices: ["am", "is", "are", "do"], answer: 2, ja: "私たちは今日うれしい。", note: "主語weにはare" },
    { q: "It ___ a nice day.", choices: ["am", "is", "are", "be"], answer: 1, ja: "いい天気だ。", note: "主語itにはis" },
    { q: "Tom and I ___ classmates.", choices: ["am", "is", "are", "was"], answer: 2, ja: "トムと私は同級生です。", note: "複数の主語にはare" },
    { q: "The dog ___ very big.", choices: ["am", "is", "are", "do"], answer: 1, ja: "その犬はとても大きい。", note: "単数にはis" },
    { q: "I ___ tired last night.", choices: ["am", "was", "were", "is"], answer: 1, ja: "私は昨夜つかれていた。", note: "Iの過去はwas" },
    { q: "They ___ at home yesterday.", choices: ["was", "were", "are", "is"], answer: 1, ja: "彼らは昨日家にいた。", note: "theyの過去はwere" },
    { q: "She ___ a nurse before.", choices: ["was", "were", "is", "am"], answer: 0, ja: "彼女は以前看護師だった。", note: "sheの過去はwas" },
    { q: "We ___ in Osaka last week.", choices: ["was", "were", "are", "am"], answer: 1, ja: "先週私たちは大阪にいた。", note: "weの過去はwere" },
    { q: "My mother ___ dinner every evening.", choices: ["cook", "cooks", "cooking", "cooked"], answer: 1, ja: "母は毎晩夕食を作る。", note: "三単現はcooks" },
    { q: "The baby ___ a lot.", choices: ["cry", "cries", "crys", "cried"], answer: 1, ja: "赤ちゃんはよく泣く。", note: "子音+yはiesでcries" },
    { q: "He ___ his homework after school.", choices: ["do", "does", "doing", "did"], answer: 1, ja: "彼は放課後に宿題をする。", note: "三単現はdoes" },
    { q: "She ___ English very well.", choices: ["speak", "speaks", "speaking", "spoke"], answer: 1, ja: "彼女は英語をとても上手に話す。", note: "三単現はspeaks" },
    { q: "This bus ___ at nine.", choices: ["leave", "leaves", "leaving", "left"], answer: 1, ja: "このバスは9時に出発する。", note: "三単現はleaves" },
    { q: "I see three ___.", choices: ["bird", "birds", "birdes", "bird's"], answer: 1, ja: "鳥が3羽見える。", note: "複数形はbirds" },
    { q: "There are five ___ in the box.", choices: ["box", "boxs", "boxes", "boxen"], answer: 2, ja: "箱の中に5つの箱がある。", note: "x語尾はesでboxes" },
    { q: "He bought some ___.", choices: ["tomato", "tomatos", "tomatoes", "tomatoo"], answer: 2, ja: "彼はトマトをいくつか買った。", note: "o語尾はesでtomatoes" },
    { q: "She has many ___.", choices: ["dish", "dishs", "dishes", "dishies"], answer: 2, ja: "彼女は皿をたくさん持っている。", note: "sh語尾はesでdishes" },
    { q: "Please help ___.", choices: ["I", "my", "me", "mine"], answer: 2, ja: "私を手伝ってください。", note: "動詞の目的語は目的格me" },
    { q: "I know ___.", choices: ["he", "his", "him", "he's"], answer: 2, ja: "私は彼を知っている。", note: "目的格はhim" },
    { q: "Give it to ___.", choices: ["she", "her", "hers", "he"], answer: 1, ja: "それを彼女に渡して。", note: "前置詞の後は目的格her" },
    { q: "This is ___ car.", choices: ["they", "their", "them", "theirs"], answer: 1, ja: "これは彼らの車です。", note: "名詞の前は所有格their" },
    { q: "The idea is ___.", choices: ["our", "ours", "us", "we"], answer: 1, ja: "その考えは私たちのものです。", note: "単独ではours" },
    { q: "I have ___ apple.", choices: ["a", "an", "the", "some"], answer: 1, ja: "私はりんごを1つ持っている。", note: "母音の前はan" },
    { q: "She is ___ honest girl.", choices: ["a", "an", "the", "one"], answer: 1, ja: "彼女は正直な女の子だ。", note: "honestのhは無音でan" },
    { q: "He is ___ teacher.", choices: ["a", "an", "the", "some"], answer: 0, ja: "彼は先生だ。", note: "子音の前はa" },
    { q: "Look at ___ stars.", choices: ["that", "this", "those", "it"], answer: 2, ja: "あの星々を見て。", note: "複数の「あれら」はthose" },
    { q: "___ do you live?", choices: ["What", "Where", "When", "Who"], answer: 1, ja: "どこに住んでいますか。", note: "場所はWhere" },
    { q: "___ is your birthday?", choices: ["What", "Where", "When", "Which"], answer: 2, ja: "誕生日はいつですか。", note: "時はWhen" },
    { q: "___ old are you?", choices: ["What", "How", "Who", "When"], answer: 1, ja: "何歳ですか。", note: "程度・年齢はHow old" },
    { q: "___ much is it?", choices: ["What", "How", "Which", "Who"], answer: 1, ja: "いくらですか。", note: "値段はHow much" },
    { q: "___ bag is this?", choices: ["Who", "Whose", "Which", "What"], answer: 1, ja: "これは誰のかばんですか。", note: "所有者はWhose" },
    { q: "___ you swim?", choices: ["Can", "Are", "Is", "Do you can"], answer: 0, ja: "泳げますか。", note: "能力の疑問はCan" },
    { q: "She can ___ the piano.", choices: ["play", "plays", "playing", "played"], answer: 0, ja: "彼女はピアノを弾ける。", note: "can+原形" },
    { q: "He ___ not drive.", choices: ["can", "cans", "do", "is"], answer: 0, ja: "彼は運転できない。", note: "cannot=can not" },
    { q: "They ___ playing outside.", choices: ["is", "am", "are", "be"], answer: 2, ja: "彼らは外で遊んでいる。", note: "進行形be動詞はare" },
    { q: "She is ___ a letter.", choices: ["write", "writes", "writing", "wrote"], answer: 2, ja: "彼女は手紙を書いている。", note: "進行形は~ing" },
    { q: "What ___ you doing?", choices: ["is", "am", "are", "do"], answer: 2, ja: "何をしているの。", note: "youの進行形はare" },
    { q: "I'm ___ lunch now.", choices: ["eat", "eats", "having", "had"], answer: 2, ja: "今昼食を食べている。", note: "進行形having" },
    { q: "We ___ to the zoo yesterday.", choices: ["go", "goes", "went", "gone"], answer: 2, ja: "昨日動物園へ行った。", note: "goの過去はwent" },
    { q: "He ___ a big fish.", choices: ["catch", "catched", "caught", "catches"], answer: 2, ja: "彼は大きな魚を捕まえた。", note: "catchの過去はcaught" },
    { q: "I ___ my key.", choices: ["lose", "losed", "lost", "loses"], answer: 2, ja: "私は鍵をなくした。", note: "loseの過去はlost" },
    { q: "They ___ TV last night.", choices: ["watch", "watches", "watched", "watching"], answer: 2, ja: "彼らは昨夜テレビを見た。", note: "過去形watched" },
    { q: "I ___ up at six today.", choices: ["get", "got", "gotten", "gets"], answer: 1, ja: "今日は6時に起きた。", note: "getの過去はgot" },
    { q: "I ___ call you later.", choices: ["will", "am", "do", "was"], answer: 0, ja: "あとで電話するね。", note: "未来はwill" },
    { q: "It ___ rain tomorrow.", choices: ["will", "is", "does", "did"], answer: 0, ja: "明日は雨が降るだろう。", note: "未来の予測will" },
    { q: "She will ___ tomorrow.", choices: ["come", "comes", "came", "coming"], answer: 0, ja: "彼女は明日来る。", note: "will+原形" },
    { q: "I get up ___ the morning.", choices: ["in", "on", "at", "to"], answer: 0, ja: "私は朝起きる。", note: "in the morning" },
    { q: "See you ___ Monday.", choices: ["in", "on", "at", "for"], answer: 1, ja: "月曜に会おう。", note: "曜日はon" },
    { q: "The movie starts ___ seven.", choices: ["in", "on", "at", "to"], answer: 2, ja: "映画は7時に始まる。", note: "時刻はat" },
    { q: "This is a present ___ you.", choices: ["to", "for", "at", "of"], answer: 1, ja: "これはあなたへのプレゼントです。", note: "~のためにはfor" },
    { q: "He is good ___ math.", choices: ["in", "on", "at", "for"], answer: 2, ja: "彼は数学が得意だ。", note: "be good at" },
    { q: "Wait ___ me.", choices: ["to", "for", "at", "of"], answer: 1, ja: "私を待って。", note: "wait for" },
    { q: "I go ___ bed at ten.", choices: ["to", "in", "on", "at"], answer: 0, ja: "私は10時に寝る。", note: "go to bed" },
    { q: "She came ___ China.", choices: ["to", "from", "at", "in"], answer: 1, ja: "彼女は中国から来た。", note: "出身・起点はfrom" },
    { q: "Cut it ___ a knife.", choices: ["by", "with", "in", "of"], answer: 1, ja: "ナイフで切って。", note: "道具はwith" },
    { q: "___ quiet, please.", choices: ["Be", "Do", "Are", "Is"], answer: 0, ja: "静かにしてください。", note: "be動詞の命令はBe" },
    { q: "___ your hands before lunch.", choices: ["Wash", "Washes", "Washing", "Washed"], answer: 0, ja: "昼食前に手を洗いなさい。", note: "命令文は原形" },
    { q: "Don't ___ here.", choices: ["run", "runs", "running", "ran"], answer: 0, ja: "ここで走らないで。", note: "Don't+原形" },
    { q: "There ___ some milk in the cup.", choices: ["is", "are", "am", "be"], answer: 0, ja: "コップに牛乳がある。", note: "milkは不可算でis" },
    { q: "There ___ two apples on the table.", choices: ["is", "are", "am", "be"], answer: 1, ja: "テーブルにりんごが2つある。", note: "複数はare" },
    { q: "How many ___ do you have?", choices: ["pen", "pens", "penes", "pen's"], answer: 1, ja: "ペンを何本持っていますか。", note: "How manyの後は複数" },
    { q: "I like ___ books.", choices: ["read", "reads", "reading", "to reads"], answer: 2, ja: "私は本を読むのが好きだ。", note: "like ~ing" },
    { q: "She enjoys ___.", choices: ["sing", "sings", "singing", "sang"], answer: 2, ja: "彼女は歌うのを楽しむ。", note: "enjoy+~ing" },
    { q: "I want ___ eat something.", choices: ["to", "for", "at", "ing"], answer: 0, ja: "何か食べたい。", note: "want to+原形" },
    { q: "He wants ___ go home.", choices: ["to", "for", "at", "of"], answer: 0, ja: "彼は家に帰りたい。", note: "want to" },
    { q: "My father ___ a car.", choices: ["have", "has", "having", "haves"], answer: 1, ja: "父は車を持っている。", note: "三単現haveはhas" },
    { q: "I don't ___ coffee.", choices: ["like", "likes", "liked", "liking"], answer: 0, ja: "私はコーヒーが好きではない。", note: "don't+原形" },
    { q: "She doesn't ___ meat.", choices: ["eat", "eats", "ate", "eating"], answer: 0, ja: "彼女は肉を食べない。", note: "doesn't+原形" },
    { q: "___ it cold today?", choices: ["Is", "Are", "Am", "Do"], answer: 0, ja: "今日は寒いですか。", note: "itの疑問はIs" },
    { q: "___ they students?", choices: ["Is", "Are", "Am", "Do"], answer: 1, ja: "彼らは学生ですか。", note: "theyの疑問はAre" },
    { q: "Where ___ he from?", choices: ["is", "are", "am", "do"], answer: 0, ja: "彼はどこの出身ですか。", note: "heにはis" },
    { q: "I was born ___ 2010.", choices: ["in", "on", "at", "to"], answer: 0, ja: "私は2010年に生まれた。", note: "年はin" },
    { q: "Turn ___ the light.", choices: ["off", "of", "at", "to"], answer: 0, ja: "電気を消して。", note: "turn off=消す" },
    { q: "Please sit ___.", choices: ["down", "on", "in", "to"], answer: 0, ja: "座ってください。", note: "sit down" },
    { q: "I'm looking ___ my cat.", choices: ["at", "for", "in", "on"], answer: 1, ja: "猫を探している。", note: "look for=探す" },
    { q: "This is ___ than that.", choices: ["big", "bigger", "biggest", "more big"], answer: 1, ja: "これはあれより大きい。", note: "比較級bigger" },
    { q: "She is ___ than me.", choices: ["tall", "taller", "tallest", "more tall"], answer: 1, ja: "彼女は私より背が高い。", note: "比較級taller" },
    { q: "Today is ___ than yesterday.", choices: ["hot", "hotter", "hottest", "more hot"], answer: 1, ja: "今日は昨日より暑い。", note: "比較級hotter" },
    { q: "This is the ___ book of the three.", choices: ["good", "better", "best", "well"], answer: 2, ja: "これは3冊で一番いい本だ。", note: "最上級best" },
    { q: "He runs ___ than Tom.", choices: ["fast", "faster", "fastest", "more fast"], answer: 1, ja: "彼はトムより速く走る。", note: "比較級faster" },
    { q: "This is ___ bike.", choices: ["Tom", "Tom's", "Toms", "Tom is"], answer: 1, ja: "これはトムの自転車だ。", note: "所有は's" },
    { q: "The ___ tail is long.", choices: ["dog", "dogs", "dog's", "dogs'"], answer: 2, ja: "その犬のしっぽは長い。", note: "単数所有はdog's" },
    { q: "I'm going ___ study tonight.", choices: ["to", "for", "at", "of"], answer: 0, ja: "今夜勉強するつもりだ。", note: "be going to+原形" },
    { q: "You ___ wear a helmet.", choices: ["must", "musts", "musting", "musted"], answer: 0, ja: "ヘルメットをかぶらねばならない。", note: "義務のmust" },
    { q: "You ___ see a doctor.", choices: ["should", "shoulds", "shoulding", "do"], answer: 0, ja: "医者に診てもらうべきだ。", note: "助言のshould" },
    { q: "I don't have ___ money.", choices: ["some", "any", "many", "a"], answer: 1, ja: "お金がない。", note: "否定文ではany" },
    { q: "Do you have ___ questions?", choices: ["some", "any", "much", "a"], answer: 1, ja: "質問はありますか。", note: "疑問文ではany" },
    { q: "There are ___ apples in the basket.", choices: ["some", "any", "much", "a"], answer: 0, ja: "かごにりんごがいくつかある。", note: "肯定文ではsome" },
    { q: "I don't have ___ friends here.", choices: ["much", "many", "any much", "a"], answer: 1, ja: "ここに友達が多くない。", note: "可算の多いはmany" },
    { q: "She sings ___.", choices: ["good", "well", "nice", "best"], answer: 1, ja: "彼女は上手に歌う。", note: "動詞を修飾する副詞well" },
    { q: "He is a ___ driver.", choices: ["careful", "carefully", "care", "cares"], answer: 0, ja: "彼は注意深い運転手だ。", note: "名詞を修飾する形容詞" },
    { q: "I like tea, ___ I don't like coffee.", choices: ["and", "but", "or", "so"], answer: 1, ja: "紅茶は好きだがコーヒーは好きでない。", note: "逆接but" },
    { q: "Hurry up, ___ you'll be late.", choices: ["and", "but", "or", "so"], answer: 2, ja: "急がないと遅れるよ。", note: "命令文, or ~" },
    { q: "It was rainy, ___ we stayed home.", choices: ["and", "but", "or", "so"], answer: 3, ja: "雨だったので家にいた。", note: "結果so" },
    { q: "I ___ not hungry now.", choices: ["am", "is", "are", "do"], answer: 0, ja: "私は今おなかがすいていない。", note: "I am not" },
    { q: "She ___ not here.", choices: ["am", "is", "are", "do"], answer: 1, ja: "彼女はここにいない。", note: "she is not" },
    { q: "They ___ not ready.", choices: ["am", "is", "are", "does"], answer: 2, ja: "彼らは準備ができていない。", note: "they are not" },
    { q: "___ you go there yesterday?", choices: ["Do", "Did", "Are", "Was"], answer: 1, ja: "昨日そこへ行きましたか。", note: "過去の疑問Did" },
    { q: "I ___ not see him.", choices: ["do", "did", "am", "was"], answer: 1, ja: "私は彼を見なかった。", note: "did not+原形" },
    { q: "___ she happy then?", choices: ["Was", "Were", "Did", "Is"], answer: 0, ja: "そのとき彼女は幸せでしたか。", note: "sheの過去の疑問Was" },
    { q: "It ___ Monday today.", choices: ["is", "are", "am", "do"], answer: 0, ja: "今日は月曜だ。", note: "曜日はit is" },
    { q: "___ go to the park.", choices: ["Let's", "Let", "We", "Do"], answer: 0, ja: "公園へ行こう。", note: "勧誘Let's+原形" },
    { q: "They ___ in Nagoya.", choices: ["live", "lives", "living", "to live"], answer: 0, ja: "彼らは名古屋に住んでいる。", note: "theyは原形live" },
    { q: "We ___ soccer every Sunday.", choices: ["play", "plays", "playing", "to play"], answer: 0, ja: "毎週日曜サッカーをする。", note: "weは原形play" },
    { q: "He ___ not listening.", choices: ["is", "are", "am", "do"], answer: 0, ja: "彼は聞いていない。", note: "heの進行形否定 is not" },
    { q: "___ you help me?", choices: ["Will", "Do", "Are", "Is"], answer: 0, ja: "手伝ってくれますか。", note: "依頼Will you" },
    { q: "Whose is this? It's ___.", choices: ["her", "hers", "she", "her's"], answer: 1, ja: "これは誰の？ 彼女のよ。", note: "単独で彼女のものはhers" },
    { q: "The keys are ___ the drawer.", choices: ["in", "on", "at", "to"], answer: 0, ja: "鍵は引き出しの中だ。", note: "中はin" },
    { q: "A bird is ___ the roof.", choices: ["in", "on", "at", "to"], answer: 1, ja: "鳥が屋根の上にいる。", note: "面の上はon" },
    { q: "Please ___ the door.", choices: ["open", "opens", "opening", "opened"], answer: 0, ja: "ドアを開けて。", note: "命令文は原形" },
    { q: "I ___ my teeth every morning.", choices: ["brush", "brushes", "brushing", "brushed"], answer: 0, ja: "毎朝歯を磨く。", note: "Iは原形brush" },
    { q: "This is the ___ mountain in Japan.", choices: ["high", "higher", "highest", "more high"], answer: 2, ja: "これは日本で一番高い山だ。", note: "最上級highest" },
    { q: "___ time is it now?", choices: ["What", "How", "Which", "Who"], answer: 0, ja: "今何時ですか。", note: "時刻はWhat time" },
    { q: "I ___ swim well.", choices: ["can't", "don't can", "am not", "isn't"], answer: 0, ja: "私は上手に泳げない。", note: "cannotの短縮can't" },
    { q: "___ I your teacher?", choices: ["Am", "Is", "Are", "Do"], answer: 0, ja: "私はあなたの先生ですか。", note: "Iの疑問はAm" },
    { q: "___ they at school then?", choices: ["Was", "Were", "Did", "Are"], answer: 1, ja: "そのとき彼らは学校にいましたか。", note: "theyの過去の疑問Were" },
    { q: "He ___ to music every day.", choices: ["listen", "listens", "listening", "listened"], answer: 1, ja: "彼は毎日音楽を聴く。", note: "三単現listens" },
    { q: "We ___ not have class today.", choices: ["do", "does", "is", "are"], answer: 0, ja: "今日は授業がない。", note: "weはdo not" },
    { q: "Does she ___ a pet?", choices: ["have", "has", "having", "had"], answer: 0, ja: "彼女はペットを飼っていますか。", note: "Does+原形have" },
    { q: "The sun ___ in the east.", choices: ["rise", "rises", "rising", "rose"], answer: 1, ja: "太陽は東から昇る。", note: "一般的事実は三単現rises" },
    { q: "Water ___ at 100 degrees.", choices: ["boil", "boils", "boiling", "boiled"], answer: 1, ja: "水は100度で沸騰する。", note: "事実は三単現boils" },
    { q: "___ you close the window?", choices: ["Could", "Do", "Are", "Was"], answer: 0, ja: "窓を閉めてくれますか。", note: "丁寧な依頼Could you" },
    { q: "I'd like a ___ of tea.", choices: ["cup", "piece", "glass", "sheet"], answer: 0, ja: "紅茶を一杯ください。", note: "a cup of ~" },
    { q: "There isn't ___ bread.", choices: ["some", "any", "many", "a"], answer: 1, ja: "パンがない。", note: "否定文ではany" },
    { q: "He is taller ___ his brother.", choices: ["then", "than", "as", "that"], answer: 1, ja: "彼は兄より背が高い。", note: "比較のthan" },
    { q: "Look! It ___ snowing.", choices: ["is", "are", "am", "do"], answer: 0, ja: "見て！ 雪が降っている。", note: "itの進行形 is" },
    { q: "The store is open ___ 9 to 6.", choices: ["from", "in", "on", "at"], answer: 0, ja: "店は9時から6時まで開いている。", note: "from ~ to" },
    { q: "I usually walk ___ school.", choices: ["to", "in", "on", "of"], answer: 0, ja: "私はたいてい歩いて学校へ行く。", note: "walk to ~" },
    { q: "We played ___ the beach.", choices: ["in", "on", "at", "to"], answer: 1, ja: "私たちは浜辺で遊んだ。", note: "on the beach" },
    { q: "The ball rolled ___ the hill.", choices: ["down", "in", "at", "of"], answer: 0, ja: "ボールが丘を転がり落ちた。", note: "down=下へ" },
    { q: "Please be ___ with the glass.", choices: ["careful", "carefully", "care", "cares"], answer: 0, ja: "ガラスに気をつけて。", note: "be+形容詞" },
    { q: "___ you a doctor?", choices: ["Am", "Is", "Are", "Do"], answer: 2, ja: "あなたは医者ですか。", note: "youの疑問Are" },
    { q: "He ___ a bike to work.", choices: ["ride", "rides", "riding", "rode"], answer: 1, ja: "彼は自転車で通勤する。", note: "三単現rides" },
    { q: "They didn't ___ the game.", choices: ["win", "won", "wins", "winning"], answer: 0, ja: "彼らは試合に勝てなかった。", note: "didn't+原形win" },
    { q: "Where did you ___?", choices: ["go", "went", "gone", "going"], answer: 0, ja: "どこへ行ったの。", note: "did+原形go" },
    { q: "I have a cat ___ a dog.", choices: ["and", "but", "or", "so"], answer: 0, ja: "私は猫と犬を飼っている。", note: "並列and" },
    { q: "Is this ___ that?", choices: ["and", "but", "or", "so"], answer: 2, ja: "これですか、それともあれですか。", note: "選択or" },
    { q: "She is kind ___ everyone likes her.", choices: ["and", "but", "or", "so"], answer: 3, ja: "彼女は親切なのでみんなに好かれる。", note: "結果so" },
    { q: "Close the door, ___ it's cold.", choices: ["because", "but", "or", "and"], answer: 0, ja: "寒いのでドアを閉めて。", note: "理由because" },
    { q: "I ___ a letter now.", choices: ["write", "am writing", "writes", "wrote"], answer: 1, ja: "私は今手紙を書いている。", note: "今~しているは進行形" },
    { q: "___ is a book on the desk.", choices: ["There", "It", "This", "That"], answer: 0, ja: "机の上に本がある。", note: "存在のThere is" },
    { q: "Mike is ___ boy in the class.", choices: ["tall", "taller", "the tallest", "more tall"], answer: 2, ja: "マイクはクラスで一番背が高い。", note: "in ~では最上級" },
    { q: "Who ___ that? My teacher.", choices: ["is", "are", "am", "do"], answer: 0, ja: "あれは誰？ 私の先生だ。", note: "単数の主語はis" },
    { q: "___ these your books?", choices: ["Is", "Are", "Am", "Do"], answer: 1, ja: "これらはあなたの本ですか。", note: "複数の疑問はAre" },
    { q: "The cats ___ black.", choices: ["is", "are", "am", "be"], answer: 1, ja: "その猫たちは黒い。", note: "複数はare" },
    { q: "He doesn't ___ a car.", choices: ["have", "has", "having", "had"], answer: 0, ja: "彼は車を持っていない。", note: "doesn't+原形have" },
    { q: "___ your father tall?", choices: ["Is", "Are", "Am", "Do"], answer: 0, ja: "あなたのお父さんは背が高いですか。", note: "単数の疑問Is" },
    { q: "I ___ born in Osaka.", choices: ["am", "was", "were", "is"], answer: 1, ja: "私は大阪で生まれた。", note: "受け身の過去was born" },
    { q: "We didn't ___ to school today.", choices: ["go", "went", "gone", "going"], answer: 0, ja: "今日は学校へ行かなかった。", note: "didn't+原形go" },
  ],
  700: [
    { q: "I have ___ in this town for ten years.", choices: ["live", "lived", "living", "lives"], answer: 1, ja: "私はこの町に10年間住んでいます。", note: "現在完了 have+過去分詞" },
    { q: "She has ___ to Paris twice.", choices: ["be", "been", "being", "was"], answer: 1, ja: "彼女はパリに2回行ったことがあります。", note: "have been (経験)" },
    { q: "Have you ___ your homework yet?", choices: ["do", "did", "done", "doing"], answer: 2, ja: "もう宿題は終わりましたか。", note: "have done" },
    { q: "This letter was ___ by Tom.", choices: ["write", "wrote", "written", "writing"], answer: 2, ja: "この手紙はトムによって書かれました。", note: "受動態 be+過去分詞" },
    { q: "English is ___ in many countries.", choices: ["speak", "spoke", "spoken", "speaking"], answer: 2, ja: "英語は多くの国で話されています。", note: "be spoken (受動態)" },
    { q: "The window ___ broken yesterday.", choices: ["is", "was", "were", "be"], answer: 1, ja: "窓は昨日割られました。", note: "受動態の過去・単数→was" },
    { q: "The man ___ is talking is my teacher.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "話している男性は私の先生です。", note: "先行詞が人で主語→who" },
    { q: "I have a book ___ is very interesting.", choices: ["who", "which", "whose", "where"], answer: 1, ja: "私はとても面白い本を持っています。", note: "先行詞が物→which" },
    { q: "This is the house ___ I was born.", choices: ["which", "who", "where", "when"], answer: 2, ja: "ここは私が生まれた家です。", note: "場所を表す関係副詞→where" },
    { q: "I want ___ a doctor.", choices: ["be", "to be", "being", "been"], answer: 1, ja: "私は医者になりたいです。", note: "want to+原形" },
    { q: "He decided ___ abroad.", choices: ["study", "to study", "studying", "studied"], answer: 1, ja: "彼は留学することを決めました。", note: "decide to+原形" },
    { q: "I enjoy ___ books.", choices: ["read", "to read", "reading", "reads"], answer: 2, ja: "私は読書を楽しみます。", note: "enjoy+動名詞" },
    { q: "She is good at ___.", choices: ["sing", "to sing", "singing", "sang"], answer: 2, ja: "彼女は歌うのが得意です。", note: "前置詞at+動名詞" },
    { q: "Would you mind ___ the door?", choices: ["open", "to open", "opening", "opened"], answer: 2, ja: "ドアを開けていただけますか。", note: "mind+動名詞" },
    { q: "You ___ wear a seatbelt. It's the law.", choices: ["must", "may", "could", "would"], answer: 0, ja: "シートベルトを着用しなければなりません。法律です。", note: "義務→must" },
    { q: "It ___ rain this afternoon. Take an umbrella.", choices: ["must", "might", "can", "should"], answer: 1, ja: "午後は雨が降るかもしれません。傘を持って。", note: "弱い推量→might" },
    { q: "You ___ see a doctor if you feel sick.", choices: ["should", "must not", "can't", "would"], answer: 0, ja: "具合が悪いなら医者に診てもらうべきです。", note: "助言→should" },
    { q: "He is ___ taller than his brother.", choices: ["very", "much", "more", "most"], answer: 1, ja: "彼は兄よりずっと背が高いです。", note: "比較級の強調→much" },
    { q: "This is ___ interesting than that.", choices: ["more", "most", "much", "very"], answer: 0, ja: "これはあれより面白いです。", note: "長い形容詞の比較級→more" },
    { q: "She runs ___ in her class.", choices: ["fast", "faster", "fastest", "the fastest"], answer: 3, ja: "彼女はクラスで一番速く走ります。", note: "副詞の最上級→the fastest" },
    { q: "I'll call you ___ I arrive.", choices: ["when", "because", "but", "so"], answer: 0, ja: "着いたら電話します。", note: "〜したら→when" },
    { q: "Wait here ___ I come back.", choices: ["since", "until", "during", "while"], answer: 1, ja: "私が戻るまでここで待っていて。", note: "〜まで(ずっと)→until" },
    { q: "He couldn't come ___ he was sick.", choices: ["because", "so", "but", "though"], answer: 0, ja: "彼は病気だったので来られませんでした。", note: "理由→because" },
    { q: "___ it was raining, we went out.", choices: ["Because", "Although", "So", "If"], answer: 1, ja: "雨が降っていたが、私たちは出かけました。", note: "〜だけれど→Although" },
    { q: "Do you know ___ he lives?", choices: ["where", "what", "which", "whose"], answer: 0, ja: "彼がどこに住んでいるか知っていますか。", note: "間接疑問・場所→where" },
    { q: "Tell me ___ this means.", choices: ["what", "who", "where", "when"], answer: 0, ja: "これがどういう意味か教えて。", note: "間接疑問→what" },
    { q: "If it ___ tomorrow, I'll stay home.", choices: ["rain", "rains", "rained", "raining"], answer: 1, ja: "明日雨なら家にいます。", note: "条件のifは現在形→rains" },
    { q: "I've known her ___ 2010.", choices: ["for", "since", "from", "during"], answer: 1, ja: "私は2010年から彼女を知っています。", note: "起点→since" },
    { q: "We've been friends ___ five years.", choices: ["since", "for", "from", "in"], answer: 1, ja: "私たちは5年間友達です。", note: "期間→for" },
    { q: "The book ___ I bought was expensive.", choices: ["who", "which", "whose", "where"], answer: 1, ja: "私が買った本は高かったです。", note: "物・目的格→which" },
    { q: "I know a girl ___ father is a doctor.", choices: ["who", "which", "whose", "whom"], answer: 2, ja: "私は父親が医者の女の子を知っています。", note: "所有→whose" },
    { q: "She told me ___ late.", choices: ["not be", "not to be", "to not be", "be not"], answer: 1, ja: "彼女は私に遅れないように言いました。", note: "tell 人 not to do" },
    { q: "It is important ___ English.", choices: ["study", "to study", "studying", "studied"], answer: 1, ja: "英語を勉強することは大切です。", note: "It is ... to do" },
    { q: "He kept ___ even when it got dark.", choices: ["work", "to work", "working", "worked"], answer: 2, ja: "暗くなっても彼は働き続けました。", note: "keep+動名詞(〜し続ける)" },
    { q: "I'm looking forward to ___ you.", choices: ["see", "to see", "seeing", "saw"], answer: 2, ja: "あなたに会うのを楽しみにしています。", note: "look forward to+動名詞" },
    { q: "The cake ___ by my mother.", choices: ["made", "was made", "is making", "makes"], answer: 1, ja: "そのケーキは母が作りました。", note: "受動態→was made" },
    { q: "These cars are ___ in Japan.", choices: ["make", "made", "making", "makes"], answer: 1, ja: "これらの車は日本で作られています。", note: "be made (受動態)" },
    { q: "He has ___ finished his work.", choices: ["yet", "already", "ago", "since"], answer: 1, ja: "彼はもう仕事を終えました。", note: "完了・肯定→already" },
    { q: "I haven't seen him ___.", choices: ["already", "yet", "ago", "still"], answer: 1, ja: "私はまだ彼に会っていません。", note: "完了・否定/疑問→yet" },
    { q: "How long ___ you studied English?", choices: ["have", "has", "did", "do"], answer: 0, ja: "どのくらい英語を勉強していますか。", note: "現在完了の疑問・you→have" },
    { q: "She ___ just left.", choices: ["has", "have", "is", "was"], answer: 0, ja: "彼女はちょうど出かけたところです。", note: "三単現の完了→has" },
    { q: "If I ___ time, I would help you.", choices: ["have", "has", "had", "having"], answer: 2, ja: "時間があれば手伝うのに。", note: "仮定法過去→had" },
    { q: "I wish I ___ rich.", choices: ["am", "was", "were", "be"], answer: 2, ja: "私が金持ちならなあ。", note: "仮定法のwishはwere" },
    { q: "You had better ___ now.", choices: ["go", "to go", "going", "went"], answer: 0, ja: "もう行ったほうがいい。", note: "had better+原形" },
    { q: "He made me ___ it again.", choices: ["do", "to do", "doing", "did"], answer: 0, ja: "彼は私にもう一度それをやらせた。", note: "使役make+原形" },
    { q: "I saw her ___ the room.", choices: ["enter", "to enter", "entered", "enters"], answer: 0, ja: "私は彼女が部屋に入るのを見た。", note: "知覚動詞+原形" },
    { q: "Neither John ___ Mary came.", choices: ["or", "nor", "and", "but"], answer: 1, ja: "ジョンもメアリーも来なかった。", note: "neither A nor B" },
    { q: "Both Tom ___ Ken are kind.", choices: ["or", "nor", "and", "but"], answer: 2, ja: "トムもケンも親切だ。", note: "both A and B" },
    { q: "This is the best movie ___ I've ever seen.", choices: ["who", "what", "that", "where"], answer: 2, ja: "これは私が今まで見た中で最高の映画だ。", note: "最上級の後の関係代名詞→that" },
    { q: "He spent two hours ___ the report.", choices: ["write", "to write", "writing", "wrote"], answer: 2, ja: "彼は報告書を書くのに2時間を費やした。", note: "spend 時間+動名詞" },
    { q: "I have ___ finished my homework.", choices: ["yet", "just", "ago", "since"], answer: 1, ja: "ちょうど宿題を終えた。", note: "現在完了just=ちょうど" },
    { q: "She has lived here ___ 2015.", choices: ["for", "since", "from", "in"], answer: 1, ja: "彼女は2015年からここに住んでいる。", note: "起点はsince" },
    { q: "We have known each other ___ ten years.", choices: ["for", "since", "from", "at"], answer: 0, ja: "私たちは10年来の知り合いだ。", note: "期間はfor" },
    { q: "Have you ___ been to Kyoto?", choices: ["ever", "yet", "already", "since"], answer: 0, ja: "京都に行ったことがありますか。", note: "経験の疑問ever" },
    { q: "I have ___ seen that movie.", choices: ["yet", "ever", "already", "since"], answer: 2, ja: "私はもうその映画を見た。", note: "肯定already" },
    { q: "He hasn't come home ___.", choices: ["yet", "just", "already", "ever"], answer: 0, ja: "彼はまだ帰宅していない。", note: "否定文のyet=まだ" },
    { q: "This letter ___ by Tom.", choices: ["wrote", "was written", "writes", "is writing"], answer: 1, ja: "この手紙はトムによって書かれた。", note: "受動態was+過去分詞" },
    { q: "English ___ in many countries.", choices: ["speaks", "is spoken", "speaking", "spoke"], answer: 1, ja: "英語は多くの国で話されている。", note: "受動態is spoken" },
    { q: "The window was ___ by the boy.", choices: ["break", "broke", "broken", "breaks"], answer: 2, ja: "窓は少年に割られた。", note: "breakの過去分詞broken" },
    { q: "The man ___ is talking is my uncle.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "話している男性は私のおじだ。", note: "人が主語→who" },
    { q: "This is the book ___ I bought.", choices: ["who", "which", "whose", "who's"], answer: 1, ja: "これは私が買った本だ。", note: "物→which" },
    { q: "I have a friend ___ father is a doctor.", choices: ["who", "which", "whose", "whom"], answer: 2, ja: "父が医者の友達がいる。", note: "所有格whose" },
    { q: "The house ___ stands on the hill is old.", choices: ["who", "which", "whose", "what"], answer: 1, ja: "丘に立つ家は古い。", note: "物が主語which" },
    { q: "She is as tall ___ her mother.", choices: ["as", "than", "so", "that"], answer: 0, ja: "彼女は母と同じくらい背が高い。", note: "as ~ as" },
    { q: "This is the ___ movie of all.", choices: ["more exciting", "most exciting", "exciting", "much exciting"], answer: 1, ja: "これは全部で一番わくわくする映画だ。", note: "最上級most" },
    { q: "He runs ___ faster than me.", choices: ["much", "very", "many", "so"], answer: 0, ja: "彼は私よりずっと速く走る。", note: "比較級強調much" },
    { q: "I want ___ something hot.", choices: ["to drink", "drink", "drinking", "drank"], answer: 0, ja: "何か温かいものが飲みたい。", note: "want to+原形" },
    { q: "It is important ___ English every day.", choices: ["study", "to study", "studies", "studied"], answer: 1, ja: "毎日英語を勉強するのは大切だ。", note: "It is ~ to do" },
    { q: "He is too tired ___ walk.", choices: ["to", "for", "that", "so"], answer: 0, ja: "彼は疲れすぎて歩けない。", note: "too ~ to do" },
    { q: "She is old enough ___ drive.", choices: ["to", "for", "that", "so"], answer: 0, ja: "彼女は運転できる年齢だ。", note: "~ enough to do" },
    { q: "I stopped ___ because I was tired.", choices: ["to walk", "walking", "walk", "walked"], answer: 1, ja: "疲れたので歩くのをやめた。", note: "stop ~ing=やめる" },
    { q: "He finished ___ the report.", choices: ["to write", "writing", "write", "wrote"], answer: 1, ja: "彼は報告書を書き終えた。", note: "finish+~ing" },
    { q: "Thank you for ___ me.", choices: ["help", "helping", "to help", "helped"], answer: 1, ja: "手伝ってくれてありがとう。", note: "前置詞forの後は~ing" },
    { q: "She is going ___ a doctor.", choices: ["to be", "be", "being", "been"], answer: 0, ja: "彼女は医者になるつもりだ。", note: "be going to+原形" },
    { q: "If it ___ tomorrow, we'll stay home.", choices: ["rains", "will rain", "rained", "raining"], answer: 0, ja: "明日雨なら家にいる。", note: "条件のifは現在形" },
    { q: "You ___ finish it by five.", choices: ["have to", "have", "having to", "has to"], answer: 0, ja: "5時までに終えねばならない。", note: "have to=~ねばならない" },
    { q: "You ___ worry. It's fine.", choices: ["don't have to", "have to", "must", "should"], answer: 0, ja: "心配しなくていい。", note: "don't have to=不要" },
    { q: "He ___ be at home. His car is here.", choices: ["must", "can't", "should", "may"], answer: 0, ja: "彼は家にいるにちがいない。", note: "確信のmust" },
    { q: "It ___ rain later. Take an umbrella.", choices: ["might", "must", "can't", "won't"], answer: 0, ja: "あとで雨かもしれない。", note: "推量might" },
    { q: "___ you like some tea?", choices: ["Would", "Do", "Are", "Will"], answer: 0, ja: "紅茶はいかがですか。", note: "勧めWould you like" },
    { q: "I ___ rather stay home tonight.", choices: ["would", "will", "should", "could"], answer: 0, ja: "今夜は家にいたい。", note: "would rather=むしろ~したい" },
    { q: "I stayed home ___ I was sick.", choices: ["because", "although", "but", "or"], answer: 0, ja: "病気だったので家にいた。", note: "理由because" },
    { q: "Call me ___ you arrive.", choices: ["when", "which", "who", "that"], answer: 0, ja: "着いたら電話して。", note: "時のwhen" },
    { q: "___ you study hard, you'll pass.", choices: ["If", "Although", "But", "So"], answer: 0, ja: "熱心に勉強すれば合格する。", note: "条件If" },
    { q: "The ___ boy is my brother.", choices: ["sleep", "sleeping", "slept", "sleeps"], answer: 1, ja: "眠っている少年は私の弟だ。", note: "現在分詞の修飾sleeping" },
    { q: "I saw a ___ window.", choices: ["break", "breaking", "broken", "broke"], answer: 2, ja: "割れた窓を見た。", note: "過去分詞の修飾broken" },
    { q: "The language ___ in Brazil is Portuguese.", choices: ["speak", "speaking", "spoken", "spoke"], answer: 2, ja: "ブラジルで話される言語はポルトガル語だ。", note: "過去分詞spoken" },
    { q: "My mother made me ___ my room.", choices: ["clean", "to clean", "cleaning", "cleaned"], answer: 0, ja: "母は私に部屋を掃除させた。", note: "make+O+原形" },
    { q: "Let me ___ you.", choices: ["help", "to help", "helping", "helped"], answer: 0, ja: "手伝わせて。", note: "let+O+原形" },
    { q: "He helped me ___ the box.", choices: ["carry", "carried", "carries", "to carrying"], answer: 0, ja: "彼は箱を運ぶのを手伝ってくれた。", note: "help+O+(to)原形" },
    { q: "___ a beautiful flower this is!", choices: ["What", "How", "Which", "Who"], answer: 0, ja: "なんて美しい花だろう。", note: "What+名詞の感嘆文" },
    { q: "___ tall he is!", choices: ["What", "How", "Which", "Who"], answer: 1, ja: "彼はなんて背が高いんだ。", note: "How+形容詞の感嘆文" },
    { q: "You like music, ___ you?", choices: ["do", "don't", "aren't", "didn't"], answer: 1, ja: "音楽が好きだよね。", note: "肯定→否定の付加疑問" },
    { q: "She can't swim, ___ she?", choices: ["can", "can't", "does", "is"], answer: 0, ja: "彼女は泳げないよね。", note: "否定→肯定の付加疑問" },
    { q: "Tell me ___ this is.", choices: ["what", "what is", "is what", "which is"], answer: 0, ja: "これが何か教えて。", note: "間接疑問what+SV" },
    { q: "There ___ a lot of people at the party.", choices: ["was", "were", "is", "has"], answer: 1, ja: "パーティーには大勢いた。", note: "peopleは複数扱いwere" },
    { q: "The test was ___ difficult that I failed.", choices: ["so", "such", "too", "very"], answer: 0, ja: "試験がとても難しくて落ちた。", note: "so+形容詞+that" },
    { q: "It was ___ a nice day that we went out.", choices: ["so", "such", "too", "very"], answer: 1, ja: "とてもいい日だったので外出した。", note: "such+a+形+名+that" },
    { q: "Either you ___ I must go.", choices: ["and", "or", "but", "nor"], answer: 1, ja: "あなたか私が行かねばならない。", note: "either A or B" },
    { q: "___ of my parents is a teacher.", choices: ["Neither", "Both", "All", "Any"], answer: 0, ja: "両親のどちらも先生ではない。", note: "neither=どちらも~ない(単数)" },
    { q: "I have ___ money left.", choices: ["little", "few", "many", "a few"], answer: 0, ja: "お金がほとんど残っていない。", note: "不可算のlittle" },
    { q: "There are ___ students in the room.", choices: ["few", "little", "much", "a little"], answer: 0, ja: "部屋には学生がほとんどいない。", note: "可算のfew" },
    { q: "She has been ___ English for two hours.", choices: ["study", "studying", "studied", "studies"], answer: 1, ja: "彼女は2時間英語を勉強し続けている。", note: "現在完了進行have been ~ing" },
    { q: "By the time we arrived, the movie ___ started.", choices: ["has", "had", "have", "having"], answer: 1, ja: "着いたときには映画は始まっていた。", note: "過去完了had+pp" },
    { q: "I wish I ___ speak Chinese.", choices: ["can", "could", "will", "am"], answer: 1, ja: "中国語が話せたらなあ。", note: "I wish+過去(could)" },
    { q: "He speaks ___ he were a teacher.", choices: ["as if", "even if", "as", "if"], answer: 0, ja: "彼はまるで先生のように話す。", note: "as if=まるで~のように" },
    { q: "She asked me ___ I was busy.", choices: ["if", "that", "what", "who"], answer: 0, ja: "彼女は私が忙しいか尋ねた。", note: "間接疑問のif=~かどうか" },
    { q: "The bridge ___ last year is long.", choices: ["build", "built", "building", "builds"], answer: 1, ja: "去年建てられた橋は長い。", note: "過去分詞built" },
    { q: "Please remember ___ the door.", choices: ["to lock", "locking", "lock", "locked"], answer: 0, ja: "ドアに鍵をかけるのを忘れないで。", note: "remember to do=これからすること" },
    { q: "I'll never forget ___ you.", choices: ["to meet", "meeting", "meet", "met"], answer: 1, ja: "あなたに会ったことを忘れない。", note: "forget ~ing=したこと" },
    { q: "He apologized for ___ late.", choices: ["be", "being", "to be", "been"], answer: 1, ja: "彼は遅刻を謝った。", note: "前置詞forの後は~ing" },
    { q: "This song makes me ___ happy.", choices: ["feel", "to feel", "feeling", "felt"], answer: 0, ja: "この歌は私を幸せにする。", note: "make+O+原形" },
    { q: "The number of students ___ increasing.", choices: ["is", "are", "were", "have"], answer: 0, ja: "生徒数は増えている。", note: "the number of ~は単数is" },
    { q: "Each of the boys ___ a bag.", choices: ["have", "has", "are", "were"], answer: 1, ja: "少年たちはそれぞれかばんを持っている。", note: "each of ~は単数has" },
    { q: "Neither of them ___ right.", choices: ["is", "are", "were", "have"], answer: 0, ja: "彼らのどちらも正しくない。", note: "neither of ~は単数is" },
    { q: "I don't know what ___.", choices: ["to do", "do", "doing", "did"], answer: 0, ja: "何をすべきか分からない。", note: "疑問詞+to do" },
    { q: "Would you mind ___ the window?", choices: ["opening", "to open", "open", "opened"], answer: 0, ja: "窓を開けてもらえますか。", note: "mind+~ing" },
    { q: "He is used to ___ early.", choices: ["get up", "getting up", "got up", "gets up"], answer: 1, ja: "彼は早起きに慣れている。", note: "be used to ~ing" },
    { q: "It's no use ___ over spilt milk.", choices: ["cry", "crying", "to cry", "cried"], answer: 1, ja: "こぼれた牛乳を嘆いても無駄だ。", note: "It's no use ~ing" },
    { q: "The movie was ___. I almost slept.", choices: ["bored", "boring", "bore", "bores"], answer: 1, ja: "映画は退屈だった。", note: "物はboring" },
    { q: "I was ___ with the result.", choices: ["satisfying", "satisfied", "satisfy", "satisfies"], answer: 1, ja: "私は結果に満足した。", note: "人はsatisfied" },
    { q: "This book is worth ___.", choices: ["read", "reading", "to read", "readed"], answer: 1, ja: "この本は読む価値がある。", note: "worth+~ing" },
    { q: "He suggested ___ a break.", choices: ["take", "taking", "to take", "took"], answer: 1, ja: "彼は休憩を提案した。", note: "suggest+~ing" },
    { q: "She promised ___ me later.", choices: ["to call", "calling", "call", "called"], answer: 0, ja: "彼女はあとで電話すると約束した。", note: "promise to do" },
    { q: "We decided ___ in Osaka.", choices: ["to stay", "staying", "stay", "stayed"], answer: 0, ja: "私たちは大阪に泊まると決めた。", note: "decide to do" },
    { q: "I'm afraid ___ dogs.", choices: ["of", "for", "at", "to"], answer: 0, ja: "私は犬が怖い。", note: "be afraid of" },
    { q: "She is interested ___ art.", choices: ["in", "on", "at", "for"], answer: 0, ja: "彼女は芸術に興味がある。", note: "be interested in" },
    { q: "He is proud ___ his work.", choices: ["of", "in", "at", "for"], answer: 0, ja: "彼は自分の仕事を誇りに思う。", note: "be proud of" },
    { q: "This bag is different ___ mine.", choices: ["from", "to", "of", "with"], answer: 0, ja: "このかばんは私のと違う。", note: "different from" },
    { q: "I'm looking ___ to the trip.", choices: ["forward", "for", "up", "after"], answer: 0, ja: "旅行を楽しみにしている。", note: "look forward to" },
    { q: "Please turn ___ the radio. It's loud.", choices: ["down", "up", "in", "off to"], answer: 0, ja: "ラジオの音を下げて。", note: "turn down=音量を下げる" },
    { q: "I ran ___ an old friend today.", choices: ["into", "out", "up", "off"], answer: 0, ja: "今日旧友に偶然会った。", note: "run into=偶然会う" },
    { q: "The plane took ___ on time.", choices: ["off", "on", "up", "in"], answer: 0, ja: "飛行機は定刻に離陸した。", note: "take off=離陸する" },
    { q: "Don't give ___. Keep trying.", choices: ["up", "in", "off", "out"], answer: 0, ja: "あきらめないで。", note: "give up=あきらめる" },
    { q: "The concert has been ___ off.", choices: ["put", "taken", "given", "made"], answer: 0, ja: "コンサートは延期された。", note: "put off=延期する" },
    { q: "I got up early ___ catch the train.", choices: ["so that", "in order to", "because", "although"], answer: 1, ja: "電車に間に合うよう早起きした。", note: "目的in order to" },
    { q: "Study hard ___ you can pass.", choices: ["so that", "because", "although", "unless"], answer: 0, ja: "合格できるよう熱心に勉強しなさい。", note: "目的so that ~ can" },
    { q: "He has been to Paris ___.", choices: ["twice", "yet", "since", "for"], answer: 0, ja: "彼はパリに2回行ったことがある。", note: "経験の回数twice" },
    { q: "I've lived in Tokyo ___ I was born.", choices: ["since", "for", "when", "while"], answer: 0, ja: "生まれてからずっと東京に住んでいる。", note: "since+S+V" },
    { q: "Please wait ___ I come back.", choices: ["until", "by", "during", "for"], answer: 0, ja: "私が戻るまで待って。", note: "~までずっとはuntil" },
    { q: "Finish it ___ noon.", choices: ["by", "until", "during", "since"], answer: 0, ja: "正午までに終えて。", note: "期限by=~までに" },
    { q: "I fell asleep ___ the movie.", choices: ["during", "while", "for", "since"], answer: 0, ja: "映画の間に眠ってしまった。", note: "名詞の前はduring" },
    { q: "The phone rang ___ I was cooking.", choices: ["while", "during", "for", "since"], answer: 0, ja: "料理中に電話が鳴った。", note: "節の前はwhile" },
    { q: "She is the tallest ___ the three.", choices: ["of", "in", "among", "at"], answer: 0, ja: "彼女は3人で一番背が高い。", note: "最上級of+複数" },
    { q: "This is the best hotel ___ this city.", choices: ["of", "in", "among", "at"], answer: 1, ja: "これはこの街で一番のホテルだ。", note: "最上級in+場所" },
    { q: "No other boy is ___ tall as Ken.", choices: ["as", "so", "more", "very"], answer: 0, ja: "ケンほど背の高い少年はいない。", note: "as ~ as (最上級相当)" },
    { q: "He is ___ of the two.", choices: ["taller", "the taller", "tallest", "tall"], answer: 1, ja: "彼は2人のうちで背が高い方だ。", note: "of the twoはthe+比較級" },
    { q: "I'd like something ___ to eat.", choices: ["hot", "hotly", "heat", "to hot"], answer: 0, ja: "何か温かい食べ物がほしい。", note: "-thing+形容詞は後置" },
    { q: "There is nothing ___ in the box.", choices: ["special", "specially", "specialize", "specialty"], answer: 0, ja: "箱には特別なものは何もない。", note: "nothing+形容詞は後置" },
    { q: "The taller boy is Tom, ___ is my friend.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "背の高い方の少年トムは私の友達だ。", note: "非制限用法who" },
    { q: "He didn't come, ___ surprised me.", choices: ["who", "which", "that", "what"], answer: 1, ja: "彼は来ず、それが私を驚かせた。", note: "前文を受ける非制限which" },
    { q: "I know the reason ___ he was late.", choices: ["why", "which", "where", "when"], answer: 0, ja: "彼が遅れた理由を知っている。", note: "関係副詞why" },
    { q: "This is the town ___ I was born.", choices: ["where", "which", "why", "who"], answer: 0, ja: "ここは私が生まれた町だ。", note: "関係副詞where" },
    { q: "Do you remember the day ___ we met?", choices: ["when", "which", "where", "who"], answer: 0, ja: "私たちが出会った日を覚えている？", note: "関係副詞when" },
    { q: "He is the only person ___ can help.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "彼が手伝える唯一の人だ。", note: "先行詞+onlyはwho/that" },
    { q: "I have ___ to tell you.", choices: ["something", "anything", "nothing much", "some"], answer: 0, ja: "あなたに言いたいことがある。", note: "肯定はsomething" },
    { q: "Would you like ___ to drink?", choices: ["something", "anything", "nothing", "some"], answer: 1, ja: "何か飲みますか。", note: "勧めの疑問はanything" },
    { q: "It is said ___ he is rich.", choices: ["that", "which", "what", "who"], answer: 0, ja: "彼は金持ちだと言われている。", note: "It is said that ~" },
    { q: "I think ___ he is honest.", choices: ["that", "which", "what", "who"], answer: 0, ja: "彼は正直だと思う。", note: "接続詞that" },
    { q: "The reason is ___ I was ill.", choices: ["that", "because", "why", "which"], answer: 0, ja: "理由は私が病気だったからだ。", note: "補語のthat節" },
    { q: "He works ___ a bank.", choices: ["for", "in", "at", "on"], answer: 2, ja: "彼は銀行で働いている。", note: "勤務先はat/for" },
    { q: "I'm good ___ cooking.", choices: ["at", "in", "on", "for"], answer: 0, ja: "私は料理が得意だ。", note: "be good at ~ing" },
    { q: "She was born ___ a rich family.", choices: ["into", "in", "on", "at"], answer: 1, ja: "彼女は裕福な家に生まれた。", note: "be born in" },
    { q: "Thanks ___ your help, I finished.", choices: ["to", "for", "of", "at"], answer: 0, ja: "あなたの助けのおかげで終えた。", note: "thanks to=おかげで" },
    { q: "___ of you is right.", choices: ["Both", "Each", "All", "Many"], answer: 1, ja: "あなたたちそれぞれが正しい。", note: "each of+単数" },
    { q: "Most ___ the students agreed.", choices: ["of", "in", "at", "for"], answer: 0, ja: "生徒の大半が賛成した。", note: "most of the ~" },
    { q: "I'd rather walk ___ take a bus.", choices: ["than", "then", "as", "that"], answer: 0, ja: "バスより歩きたい。", note: "would rather A than B" },
    { q: "The more you practice, the ___ you get.", choices: ["good", "better", "best", "well"], answer: 1, ja: "練習するほど上手くなる。", note: "the 比較級, the 比較級" },
    { q: "It's about time you ___ to bed.", choices: ["go", "went", "gone", "going"], answer: 1, ja: "もう寝る時間だ。", note: "It's time+過去形" },
    { q: "He made himself ___ in English.", choices: ["understand", "understood", "understanding", "to understand"], answer: 1, ja: "彼は英語で意思を通じさせた。", note: "make oneself understood" },
    { q: "I had my hair ___ yesterday.", choices: ["cut", "cutting", "to cut", "cuts"], answer: 0, ja: "昨日髪を切ってもらった。", note: "have+O+過去分詞(使役受動)" },
    { q: "The news made everyone ___.", choices: ["happy", "happily", "happiness", "to happy"], answer: 0, ja: "その知らせはみんなを喜ばせた。", note: "make+O+形容詞" },
    { q: "You had ___ see a doctor.", choices: ["better", "best", "well", "good"], answer: 0, ja: "医者に診てもらうほうがよい。", note: "had better+原形" },
    { q: "Not only Tom ___ Ken came.", choices: ["but also", "and also", "or", "but"], answer: 0, ja: "トムだけでなくケンも来た。", note: "not only A but also B" },
    { q: "He is ___ a doctor but a writer.", choices: ["not", "no", "never", "none"], answer: 0, ja: "彼は医者ではなく作家だ。", note: "not A but B" },
    { q: "As soon ___ he came, we left.", choices: ["as", "than", "that", "so"], answer: 0, ja: "彼が来るとすぐ出発した。", note: "as soon as" },
    { q: "I don't know ___ to start.", choices: ["how", "how to", "what", "which"], answer: 1, ja: "どう始めればいいか分からない。", note: "how to do" },
    { q: "There is ___ milk left.", choices: ["little", "few", "many", "a few"], answer: 0, ja: "牛乳がほとんど残っていない。", note: "不可算little" },
    { q: "Few people ___ the answer.", choices: ["know", "knows", "knowing", "known"], answer: 0, ja: "答えを知る人はほとんどいない。", note: "few+複数動詞" },
    { q: "The train had already left ___ we got there.", choices: ["when", "which", "where", "that"], answer: 0, ja: "着いたときには電車は出ていた。", note: "時のwhen" },
    { q: "He acts ___ he knows everything.", choices: ["as if", "even if", "if", "as"], answer: 0, ja: "彼は何でも知っているように振る舞う。", note: "as if" },
    { q: "Please let me ___ if you're coming.", choices: ["know", "to know", "knowing", "known"], answer: 0, ja: "来るかどうか教えて。", note: "let+O+原形" },
    { q: "I want you ___ honest.", choices: ["to be", "be", "being", "been"], answer: 0, ja: "あなたに正直でいてほしい。", note: "want+O+to do" },
    { q: "It was kind ___ you to help.", choices: ["of", "for", "to", "with"], answer: 0, ja: "手伝ってくれてご親切に。", note: "人の性質はof" },
    { q: "It is difficult ___ me to run fast.", choices: ["of", "for", "to", "with"], answer: 1, ja: "私が速く走るのは難しい。", note: "難易はfor" },
    { q: "She seems ___ tired.", choices: ["to be", "being", "be", "been"], answer: 0, ja: "彼女は疲れているようだ。", note: "seem to be" },
    { q: "This medicine will make you ___ better.", choices: ["feel", "to feel", "feeling", "felt"], answer: 0, ja: "この薬で気分がよくなる。", note: "make+O+原形" },
    { q: "I have never seen ___ a big dog.", choices: ["so", "such", "too", "very"], answer: 1, ja: "こんな大きな犬を見たことがない。", note: "such+a+形+名" },
    { q: "The problem is too hard ___ solve.", choices: ["to", "for", "that", "so"], answer: 0, ja: "その問題は難しすぎて解けない。", note: "too ~ to do" },
    { q: "He was seen ___ the room.", choices: ["to enter", "enter", "entering", "entered"], answer: 0, ja: "彼が部屋に入るのが見られた。", note: "知覚動詞の受動はto+原形" },
    { q: "I'm certain ___ he will win.", choices: ["that", "which", "what", "who"], answer: 0, ja: "彼が勝つと確信している。", note: "be certain that" },
    { q: "___ hard he tried, he failed.", choices: ["However", "Whatever", "Whenever", "Wherever"], answer: 0, ja: "どんなに頑張っても失敗した。", note: "However+形/副" },
    { q: "Take ___ you like.", choices: ["whatever", "however", "whenever", "wherever"], answer: 0, ja: "好きなものを取って。", note: "whatever=何でも" },
    { q: "The house was built ___ stone.", choices: ["of", "from", "in", "at"], answer: 0, ja: "その家は石で造られた。", note: "材料が見て分かるならof" },
    { q: "He has ___ to London twice.", choices: ["been", "gone", "be", "being"], answer: 0, ja: "彼はロンドンに2回行ったことがある。", note: "経験はhave been to" },
    { q: "The room ___ cleaned every day.", choices: ["is", "does", "has", "being"], answer: 0, ja: "その部屋は毎日掃除される。", note: "受動態is cleaned" },
    { q: "I know a girl ___ can play the violin.", choices: ["who", "which", "whose", "whom"], answer: 0, ja: "バイオリンを弾ける少女を知っている。", note: "人が主語who" },
    { q: "He is ___ intelligent as his sister.", choices: ["as", "more", "so", "than"], answer: 0, ja: "彼は姉と同じくらい賢い。", note: "as ~ as" },
    { q: "I'm thinking ___ buying a car.", choices: ["of", "to", "for", "at"], answer: 0, ja: "車を買おうかと思っている。", note: "think of ~ing" },
    { q: "She avoided ___ to him.", choices: ["talking", "to talk", "talk", "talked"], answer: 0, ja: "彼女は彼と話すのを避けた。", note: "avoid+~ing" },
  ],
  900: [
    { q: "If I ___ harder, I would have passed.", choices: ["studied", "had studied", "study", "have studied"], answer: 1, ja: "もっと勉強していたら合格していただろう。", note: "仮定法過去完了 had+過去分詞" },
    { q: "If she had left earlier, she ___ the train.", choices: ["caught", "would catch", "would have caught", "catches"], answer: 2, ja: "もっと早く出ていたら電車に間に合っただろう。", note: "帰結節 would have+過去分詞" },
    { q: "___ in simple English, the book sold well.", choices: ["Write", "Written", "Writing", "To write"], answer: 1, ja: "平易な英語で書かれていたので、その本はよく売れた。", note: "受動の分詞構文→Written" },
    { q: "___ the test, he felt relieved.", choices: ["Finish", "Finished", "Having finished", "Finishes"], answer: 2, ja: "試験を終えて、彼はほっとした。", note: "完了分詞構文 Having+過去分詞" },
    { q: "Never ___ I seen such a beautiful sight.", choices: ["have", "had", "has", "did"], answer: 1, ja: "そんな美しい光景は見たことがなかった。", note: "否定語+倒置(過去完了)→had" },
    { q: "Hardly ___ he arrived when it began to rain.", choices: ["has", "had", "have", "did"], answer: 1, ja: "彼が着くやいなや雨が降り始めた。", note: "Hardly...when は過去完了の倒置" },
    { q: "It was John ___ broke the window.", choices: ["who", "which", "whom", "whose"], answer: 0, ja: "窓を割ったのはジョンだった。", note: "強調構文・人→who" },
    { q: "It was yesterday ___ I met her.", choices: ["when", "that", "which", "who"], answer: 1, ja: "私が彼女に会ったのは昨日だった。", note: "強調構文 It was 〜 that" },
    { q: "This is the reason ___ he left.", choices: ["why", "which", "where", "what"], answer: 0, ja: "これが彼が去った理由だ。", note: "理由の関係副詞→why" },
    { q: "I remember the day ___ we first met.", choices: ["why", "when", "where", "which"], answer: 1, ja: "私たちが初めて会った日を覚えている。", note: "時の関係副詞→when" },
    { q: "He has ___ working here for ten years.", choices: ["be", "been", "being", "was"], answer: 1, ja: "彼はここで10年間働いている。", note: "現在完了進行形 have been ~ing" },
    { q: "I've ___ waiting for an hour.", choices: ["been", "be", "being", "was"], answer: 0, ja: "私は1時間ずっと待っている。", note: "have been waiting" },
    { q: "Were I you, I ___ accept the offer.", choices: ["will", "would", "can", "must"], answer: 1, ja: "私があなたなら、その申し出を受けるだろう。", note: "if省略の倒置・仮定法→would" },
    { q: "Had I known, I ___ have come.", choices: ["will", "would", "can", "should"], answer: 1, ja: "知っていたら来ていただろう。", note: "Had I known の帰結→would have" },
    { q: "He talks ___ he knew everything.", choices: ["as if", "even if", "only if", "what if"], answer: 0, ja: "彼はまるで何でも知っているかのように話す。", note: "as if+仮定法(まるで〜のように)" },
    { q: "The project, ___ took years, finally ended.", choices: ["who", "which", "that", "what"], answer: 1, ja: "何年もかかったその計画がついに終わった。", note: "非制限用法・物→which" },
    { q: "___ honest, I don't agree.", choices: ["To be", "Being", "Been", "Be"], answer: 0, ja: "正直に言うと、私は賛成しません。", note: "To be honest(正直に言うと)" },
    { q: "Not until midnight ___ he come home.", choices: ["does", "did", "do", "had"], answer: 1, ja: "真夜中になって初めて彼は帰宅した。", note: "Not until+倒置(過去)→did" },
    { q: "So tired ___ he that he fell asleep.", choices: ["was", "is", "were", "did"], answer: 0, ja: "彼はとても疲れていて眠ってしまった。", note: "So+形容詞の倒置→was" },
    { q: "___ all his efforts, he failed.", choices: ["Despite", "Although", "Because", "However"], answer: 0, ja: "あらゆる努力にもかかわらず、彼は失敗した。", note: "前置詞despite+名詞" },
    { q: "He insisted that she ___ present.", choices: ["is", "be", "was", "being"], answer: 1, ja: "彼は彼女が出席すべきだと主張した。", note: "insist that+(should)原形→be" },
    { q: "It is essential that he ___ on time.", choices: ["is", "be", "was", "being"], answer: 1, ja: "彼が時間どおりであることが不可欠だ。", note: "要求・必要のthat節→原形be" },
    { q: "I'd rather you ___ not smoke here.", choices: ["do", "did", "to do", "done"], answer: 1, ja: "ここでタバコを吸わないでほしい。", note: "would rather+S+過去形→did" },
    { q: "No sooner had he sat down ___ the phone rang.", choices: ["when", "than", "then", "that"], answer: 1, ja: "彼が座るとすぐに電話が鳴った。", note: "No sooner...than" },
    { q: "___ generous, she helped everyone.", choices: ["Being", "Been", "To be", "Be"], answer: 0, ja: "寛大なので、彼女はみんなを助けた。", note: "分詞構文→Being" },
    { q: "The house ___ roof is red is mine.", choices: ["which", "whose", "that", "where"], answer: 1, ja: "屋根が赤い家が私の家だ。", note: "所有を表す→whose" },
    { q: "She is said ___ very rich.", choices: ["be", "to be", "being", "been"], answer: 1, ja: "彼女はとても金持ちだと言われている。", note: "be said to be(〜だと言われている)" },
    { q: "He is believed ___ the country.", choices: ["leave", "to have left", "leaving", "left"], answer: 1, ja: "彼は国を去ったと信じられている。", note: "過去の内容→to have+過去分詞" },
    { q: "Little ___ he know the truth.", choices: ["does", "did", "do", "had"], answer: 1, ja: "彼は真実をほとんど知らなかった。", note: "Little+倒置(過去)→did" },
    { q: "Only after the meeting ___ I understand.", choices: ["do", "did", "had", "was"], answer: 1, ja: "会議の後で初めて私は理解した。", note: "Only after+倒置(過去)→did" },
    { q: "___ from space, the earth looks blue.", choices: ["Seeing", "Seen", "To see", "See"], answer: 1, ja: "宇宙から見ると、地球は青く見える。", note: "受動の分詞構文→Seen" },
    { q: "There is no point in ___ about it.", choices: ["worry", "to worry", "worrying", "worried"], answer: 2, ja: "それを心配しても意味がない。", note: "no point in+動名詞" },
    { q: "He objected to ___ treated like a child.", choices: ["be", "being", "to be", "been"], answer: 1, ja: "彼は子供扱いされることに反対した。", note: "object to+動名詞(being)" },
    { q: "I'm used to ___ early.", choices: ["get up", "to get up", "getting up", "got up"], answer: 2, ja: "私は早起きに慣れている。", note: "be used to+動名詞(〜に慣れている)" },
    { q: "It's high time we ___.", choices: ["leave", "left", "to leave", "leaving"], answer: 1, ja: "そろそろ出発する時間だ。", note: "It's time+仮定法過去→left" },
    { q: "Whatever ___, don't give up.", choices: ["happen", "happens", "happened", "happening"], answer: 1, ja: "何が起きても、あきらめるな。", note: "Whateverの後・三単現→happens" },
    { q: "___ hard he tried, he couldn't do it.", choices: ["However", "Whatever", "Whoever", "Whenever"], answer: 0, ja: "どんなに頑張っても彼にはできなかった。", note: "However+形容詞/副詞(どんなに〜でも)" },
    { q: "The more you practice, the ___ you get.", choices: ["good", "better", "best", "well"], answer: 1, ja: "練習するほど上達する。", note: "the 比較級, the 比較級→better" },
    { q: "Scarcely had I left ___ it started to rain.", choices: ["than", "when", "then", "that"], answer: 1, ja: "私が出るやいなや雨が降り出した。", note: "Scarcely...when" },
    { q: "I would have helped, ___ I been there.", choices: ["if", "had", "have", "should"], answer: 1, ja: "そこにいたら手伝っていただろう。", note: "if省略の倒置→Had I been" },
    { q: "He acts ___ he were the boss.", choices: ["as though", "even though", "so that", "now that"], answer: 0, ja: "彼はまるで自分が上司であるかのように振る舞う。", note: "as though+仮定法" },
    { q: "Not only ___ he sing, but he also dances.", choices: ["does", "do", "did", "is"], answer: 0, ja: "彼は歌うだけでなく踊りもする。", note: "Not only+倒置・三単現→does" },
    { q: "I suggest that the plan ___ changed.", choices: ["is", "be", "was", "being"], answer: 1, ja: "私は計画を変更すべきだと提案する。", note: "suggest that+(should)be" },
    { q: "___ for your help, I would have failed.", choices: ["But", "Without", "If", "Despite"], answer: 1, ja: "あなたの助けがなければ失敗していただろう。", note: "Without+名詞(〜がなければ)" },
    { q: "He is the last person ___ tell a lie.", choices: ["who", "to", "that", "which"], answer: 1, ja: "彼は最も嘘をつきそうにない人だ。", note: "the last person to do(最も〜しそうにない)" },
    { q: "___ being tired, she finished the work.", choices: ["Despite", "Although", "In spite", "Because"], answer: 0, ja: "疲れていたが、彼女は仕事を終えた。", note: "Despite+動名詞" },
    { q: "It was not until he left ___ I realized it.", choices: ["when", "that", "which", "then"], answer: 1, ja: "彼が去って初めて私はそれに気づいた。", note: "It was not until 〜 that" },
    { q: "Such was his anger ___ he couldn't speak.", choices: ["that", "as", "than", "which"], answer: 0, ja: "彼の怒りはあまりに激しく、口がきけなかった。", note: "Such 〜 that(あまりに〜なので)" },
    { q: "I'd appreciate it if you ___ help me.", choices: ["can", "could", "will", "do"], answer: 1, ja: "手伝っていただけるとありがたいです。", note: "丁寧な仮定→could" },
    { q: "He spoke as if he ___ everything.", choices: ["knows", "knew", "known", "know"], answer: 1, ja: "彼はまるで何でも知っているかのように話した。", note: "as if+仮定法過去→knew" },
    { q: "If I ___ you, I would accept the offer.", choices: ["am", "were", "was", "be"], answer: 1, ja: "もし私があなたなら申し出を受ける。", note: "仮定法過去はwere" },
    { q: "If he had studied, he ___ have passed.", choices: ["would", "will", "can", "must"], answer: 0, ja: "勉強していれば合格しただろうに。", note: "仮定法過去完了would have" },
    { q: "Had I known, I ___ have told you.", choices: ["would", "will", "can", "do"], answer: 0, ja: "知っていたら教えたのに。", note: "if省略の倒置Had I known" },
    { q: "I wish I ___ studied harder.", choices: ["have", "had", "would", "did"], answer: 1, ja: "もっと勉強しておけばよかった。", note: "I wish+過去完了" },
    { q: "___ it not for water, we couldn't live.", choices: ["Were", "Was", "Is", "Had"], answer: 0, ja: "水がなければ生きられない。", note: "Were it not for=if it were not for" },
    { q: "He talks as if he ___ everything.", choices: ["knows", "knew", "know", "known"], answer: 1, ja: "彼は何でも知っているかのように話す。", note: "as if+仮定法過去" },
    { q: "It's high time we ___ a decision.", choices: ["make", "made", "have made", "making"], answer: 1, ja: "もう決断すべき時だ。", note: "It's time+仮定法過去" },
    { q: "___ finishing the work, she went home.", choices: ["On", "In", "At", "By"], answer: 0, ja: "仕事を終えるとすぐ帰宅した。", note: "on ~ing=~するとすぐ" },
    { q: "___ tired, he kept working.", choices: ["Being", "Been", "To be", "Be"], answer: 0, ja: "疲れていたが働き続けた。", note: "分詞構文Being ~" },
    { q: "___ from the sky, the town looked small.", choices: ["Seen", "Seeing", "See", "To see"], answer: 0, ja: "空から見ると町は小さく見えた。", note: "受動の分詞構文Seen" },
    { q: "Never ___ I seen such a sight.", choices: ["have", "had", "did", "do"], answer: 0, ja: "そんな光景は見たことがない。", note: "Never+倒置haveI" },
    { q: "Hardly had he arrived ___ it began to rain.", choices: ["when", "than", "then", "that"], answer: 0, ja: "彼が着くとすぐ雨が降り出した。", note: "Hardly ~ when" },
    { q: "No sooner had she left ___ he came.", choices: ["than", "when", "then", "that"], answer: 0, ja: "彼女が去るやいなや彼が来た。", note: "No sooner ~ than" },
    { q: "Not only ___ he late, but he was rude.", choices: ["was", "he was", "did", "is"], answer: 0, ja: "彼は遅れた上に無礼だった。", note: "Not only+倒置was he" },
    { q: "It was in Kyoto ___ I met her.", choices: ["that", "which", "where", "when"], answer: 0, ja: "私が彼女に会ったのは京都でだった。", note: "強調構文(場所でもthat)" },
    { q: "___ he says is true.", choices: ["What", "That", "Which", "Who"], answer: 0, ja: "彼が言うことは本当だ。", note: "関係代名詞what=~すること" },
    { q: "This is ___ I want to say.", choices: ["what", "that", "which", "who"], answer: 0, ja: "これが私の言いたいことだ。", note: "先行詞なしwhat" },
    { q: "By next year, I ___ worked here for a decade.", choices: ["will have", "will", "have", "had"], answer: 0, ja: "来年でここで10年働いたことになる。", note: "未来完了will have+pp" },
    { q: "She ___ been waiting for an hour when he came.", choices: ["had", "has", "will have", "have"], answer: 0, ja: "彼が来たとき彼女は1時間待ち続けていた。", note: "過去完了進行had been ~ing" },
    { q: "The plan is ___ to fail.", choices: ["likely", "like", "alike", "liking"], answer: 0, ja: "その計画は失敗しそうだ。", note: "be likely to" },
    { q: "He must ___ forgotten the meeting.", choices: ["have", "has", "had", "having"], answer: 0, ja: "彼は会議を忘れたにちがいない。", note: "must have+pp=~したにちがいない" },
    { q: "You should ___ told me earlier.", choices: ["have", "has", "had", "having"], answer: 0, ja: "もっと早く言うべきだった。", note: "should have+pp" },
    { q: "She can't ___ said such a thing.", choices: ["have", "has", "had", "having"], answer: 0, ja: "彼女がそんなことを言ったはずがない。", note: "can't have+pp" },
    { q: "You needn't ___ come so early.", choices: ["have", "has", "had", "having"], answer: 0, ja: "そんなに早く来る必要はなかった。", note: "needn't have+pp" },
    { q: "He suggested that she ___ early.", choices: ["leave", "leaves", "left", "leaving"], answer: 0, ja: "彼は彼女に早く出るよう提案した。", note: "suggest that S+原形(仮定法現在)" },
    { q: "It is essential that he ___ present.", choices: ["be", "is", "was", "being"], answer: 0, ja: "彼が出席することが不可欠だ。", note: "要求・必要のthat節は原形be" },
    { q: "The higher we climbed, the ___ it became.", choices: ["cold", "colder", "coldest", "more cold"], answer: 1, ja: "登るほど寒くなった。", note: "the 比較級, the 比較級" },
    { q: "___ generous, he is also wise.", choices: ["Not only", "As", "Though", "Because"], answer: 0, ja: "寛大なだけでなく賢明でもある。", note: "Not only ~文頭" },
    { q: "Weather ___, we'll have a picnic.", choices: ["permitting", "permitted", "permit", "to permit"], answer: 0, ja: "天気がよければピクニックをする。", note: "独立分詞構文Weather permitting" },
    { q: "All things ___, it went well.", choices: ["considered", "considering", "consider", "considers"], answer: 0, ja: "すべてを考えれば、うまくいった。", note: "all things considered" },
    { q: "He is said ___ been rich.", choices: ["to have", "to has", "having", "to be"], answer: 0, ja: "彼は金持ちだったと言われている。", note: "完了不定詞to have+pp" },
    { q: "I would rather you ___ not go.", choices: ["did", "do", "will", "have"], answer: 0, ja: "あなたには行ってほしくない。", note: "would rather+S+過去形" },
    { q: "___ that he was late, he apologized.", choices: ["Realizing", "Realized", "Realize", "To realize"], answer: 0, ja: "遅刻に気づいて彼は謝った。", note: "能動の分詞構文Realizing" },
    { q: "Provided that you agree, we'll start.", choices: ["Provided", "Provide", "Providing to", "Provides"], answer: 0, ja: "あなたが同意するなら始める。", note: "provided (that)=もし~なら" },
    { q: "We won't go ___ it stops raining.", choices: ["unless", "if", "though", "because"], answer: 0, ja: "雨がやまない限り行かない。", note: "unless=~しない限り" },
    { q: "He is, ___ were, a walking dictionary.", choices: ["as it", "so it", "such it", "that it"], answer: 0, ja: "彼はいわば生き字引だ。", note: "as it were=いわば" },
    { q: "The book, ___ cover is red, is mine.", choices: ["whose", "which", "who", "that"], answer: 0, ja: "表紙が赤い本は私のだ。", note: "所有格whose(物にも)" },
    { q: "I'll give this to ___ wants it.", choices: ["whoever", "whomever", "whatever", "whichever"], answer: 0, ja: "ほしい人には誰にでもあげる。", note: "whoever=~する人は誰でも(主格)" },
    { q: "___ you choose, I'll support you.", choices: ["Whichever", "However", "Whenever", "Wherever"], answer: 0, ja: "どちらを選んでも応援する。", note: "whichever=どちらでも" },
    { q: "Scarcely had we sat down ___ the phone rang.", choices: ["when", "than", "then", "that"], answer: 0, ja: "座るやいなや電話が鳴った。", note: "Scarcely ~ when" },
    { q: "Only after the exam ___ he relax.", choices: ["did", "does", "was", "has"], answer: 0, ja: "試験の後になって初めて彼はくつろいだ。", note: "Only after+倒置did he" },
    { q: "So tired ___ he that he slept at once.", choices: ["was", "did", "is", "has"], answer: 0, ja: "彼はとても疲れていてすぐ眠った。", note: "So+形+倒置was he" },
    { q: "Such was his anger ___ he shouted.", choices: ["that", "which", "as", "than"], answer: 0, ja: "彼の怒りはすさまじく、叫んだ。", note: "Such was ~ that" },
    { q: "He objected to my ___ the plan.", choices: ["changing", "change", "to change", "changed"], answer: 0, ja: "彼は私が計画を変えるのに反対した。", note: "動名詞の意味上の主語my+~ing" },
    { q: "I insisted on ___ paid immediately.", choices: ["being", "be", "been", "to be"], answer: 0, ja: "私はすぐ支払われることを主張した。", note: "受動の動名詞being+pp" },
    { q: "The problem remains ___.", choices: ["unsolved", "unsolving", "unsolve", "to unsolve"], answer: 0, ja: "問題は未解決のままだ。", note: "remain+過去分詞" },
    { q: "With the sun ___, it grew cold.", choices: ["set", "setting", "to set", "sets"], answer: 1, ja: "日が沈むにつれ寒くなった。", note: "with+O+~ing(付帯状況)" },
    { q: "He stood there with his arms ___.", choices: ["folded", "folding", "fold", "to fold"], answer: 0, ja: "彼は腕を組んで立っていた。", note: "with+O+過去分詞" },
    { q: "It goes without ___ that health is important.", choices: ["saying", "say", "to say", "said"], answer: 0, ja: "健康が大切なのは言うまでもない。", note: "It goes without saying that" },
    { q: "There is no ___ what will happen.", choices: ["telling", "tell", "to tell", "told"], answer: 0, ja: "何が起こるか分からない。", note: "There is no ~ing=できない" },
    { q: "I couldn't help ___ at the joke.", choices: ["laughing", "laugh", "to laugh", "laughed"], answer: 0, ja: "その冗談に笑わずにいられなかった。", note: "cannot help ~ing" },
    { q: "On no account ___ you touch it.", choices: ["must", "you must", "do", "are"], answer: 0, ja: "決してそれに触れてはならない。", note: "On no account+倒置must you" },
    { q: "Were he to fail, he would try again.", choices: ["Were", "Was", "If", "Had"], answer: 0, ja: "仮に失敗しても再挑戦するだろう。", note: "were to+倒置(未来の仮定)" },
    { q: "But for your help, I ___ have failed.", choices: ["would", "will", "can", "do"], answer: 0, ja: "あなたの助けがなければ失敗していた。", note: "but for=~がなければ" },
    { q: "He behaves ___ though nothing happened.", choices: ["as", "even", "so", "just"], answer: 0, ja: "彼は何もなかったかのように振る舞う。", note: "as though=as if" },
    { q: "It is not until you lose health ___ you know its value.", choices: ["that", "when", "which", "than"], answer: 0, ja: "健康を失って初めてその価値が分かる。", note: "It is not until ~ that (強調)" },
    { q: "The teacher had us ___ the passage aloud.", choices: ["read", "to read", "reading", "reads"], answer: 0, ja: "先生は私たちに一節を音読させた。", note: "have+O+原形(使役)" },
    { q: "I got him ___ the car.", choices: ["to wash", "wash", "washing", "washed"], answer: 0, ja: "私は彼に車を洗わせた／洗ってもらった。", note: "get+O+to do" },
    { q: "The document needs ___.", choices: ["revising", "revise", "to revising", "revised to"], answer: 0, ja: "その書類は修正が必要だ。", note: "need ~ing=~される必要(受動的)" },
    { q: "Much ___ my surprise, he agreed.", choices: ["to", "for", "of", "at"], answer: 0, ja: "とても驚いたことに、彼は同意した。", note: "to one's surprise" },
    { q: "___ his age, he is very active.", choices: ["Considering", "Considered", "Consider", "To consider"], answer: 0, ja: "年齢の割に彼はとても活発だ。", note: "considering=~の割に" },
    { q: "He is anything ___ a fool.", choices: ["but", "than", "of", "as"], answer: 0, ja: "彼は決して愚か者ではない。", note: "anything but=決して~でない" },
    { q: "She is far ___ satisfied.", choices: ["from", "of", "to", "than"], answer: 0, ja: "彼女は満足には程遠い。", note: "far from=決して~でない" },
    { q: "It is no ___ true.", choices: ["longer", "long", "more longer", "longest"], answer: 0, ja: "それはもはや真実ではない。", note: "no longer=もはや~ない" },
    { q: "I have no choice ___ to accept.", choices: ["but", "than", "except of", "for"], answer: 0, ja: "受け入れるしかない。", note: "have no choice but to do" },
    { q: "The more, the ___.", choices: ["better", "good", "best", "well"], answer: 0, ja: "多ければ多いほどよい。", note: "the more the better" },
    { q: "He is superior ___ me in math.", choices: ["to", "than", "as", "of"], answer: 0, ja: "彼は数学で私より優れている。", note: "superior to" },
    { q: "This model is preferable ___ that one.", choices: ["to", "than", "as", "of"], answer: 0, ja: "この型のほうがあれより好ましい。", note: "preferable to" },
    { q: "No sooner ___ she seen me than she ran.", choices: ["had", "has", "did", "was"], answer: 0, ja: "私を見るやいなや彼女は走った。", note: "No sooner had+S+pp" },
    { q: "___ strange it may sound, it's true.", choices: ["However", "Whatever", "Whenever", "Wherever"], answer: 0, ja: "どんなに奇妙に聞こえても本当だ。", note: "However+形" },
    { q: "Such being the case, we gave up.", choices: ["Such", "So", "That", "As"], answer: 0, ja: "そういう事情なので、あきらめた。", note: "Such being the case(独立分詞)" },
    { q: "___ speaking, women live longer than men.", choices: ["Generally", "General", "To general", "Generalized"], answer: 0, ja: "一般的に言えば女性のほうが長生きだ。", note: "generally speaking(慣用分詞構文)" },
    { q: "Should you need help, call me.", choices: ["Should", "Would", "Could", "Might"], answer: 0, ja: "もし助けが必要なら電話して。", note: "if省略の倒置Should you" },
    { q: "He denied ___ the money.", choices: ["having taken", "to take", "take", "taken"], answer: 0, ja: "彼はお金を取ったことを否定した。", note: "deny+動名詞(完了)" },
    { q: "There is little, ___ any, hope.", choices: ["if", "though", "even", "as"], answer: 0, ja: "希望はほとんど、あってもわずかだ。", note: "little if any" },
    { q: "It was careless ___ him to lose it.", choices: ["of", "for", "to", "with"], answer: 0, ja: "それをなくすとは彼は不注意だった。", note: "人の性質はof" },
    { q: "The higher the demand, the ___ the price.", choices: ["higher", "high", "highest", "more high"], answer: 0, ja: "需要が高いほど価格も高い。", note: "the 比較級, the 比較級" },
    { q: "Not a word ___ he say.", choices: ["did", "does", "was", "has"], answer: 0, ja: "彼は一言も言わなかった。", note: "否定語文頭+倒置did he" },
    { q: "___ as he was, he couldn't lift it.", choices: ["Strong", "Stronger", "Strongest", "More strong"], answer: 0, ja: "彼は強かったが、持ち上げられなかった。", note: "形容詞+as+S+V(譲歩)" },
    { q: "Come ___ may, I'll go.", choices: ["what", "whatever", "how", "when"], answer: 0, ja: "何が起ころうと私は行く。", note: "Come what may(慣用)" },
    { q: "He spoke slowly ___ to be understood.", choices: ["so as", "so that", "in order", "such as"], answer: 0, ja: "理解されるようゆっくり話した。", note: "so as to do" },
    { q: "The results were ___ from satisfactory.", choices: ["far", "much", "very", "too"], answer: 0, ja: "結果は満足には程遠かった。", note: "far from" },
    { q: "I would sooner die ___ betray them.", choices: ["than", "then", "as", "that"], answer: 0, ja: "彼らを裏切るくらいなら死んだほうがましだ。", note: "would sooner ~ than" },
    { q: "She is beautiful, and ___ intelligent.", choices: ["what is more", "what is worse", "what if", "what for"], answer: 0, ja: "彼女は美しく、さらに賢い。", note: "what is more=さらに" },
    { q: "___ his advice, I would have failed.", choices: ["Without", "With", "But", "For"], answer: 0, ja: "彼の助言がなければ失敗していた。", note: "Without=~がなければ(仮定)" },
    { q: "The moment he arrived, we ___.", choices: ["left", "leave", "had left", "leaving"], answer: 0, ja: "彼が着いた瞬間、私たちは出た。", note: "the moment=~するとすぐ" },
    { q: "It remains to be ___ whether he'll come.", choices: ["seen", "see", "seeing", "saw"], answer: 0, ja: "彼が来るかはまだ分からない。", note: "remain to be+pp" },
    { q: "He is above ___ a lie.", choices: ["telling", "tell", "to tell", "told"], answer: 0, ja: "彼は嘘をつくような人ではない。", note: "be above ~ing" },
    { q: "Nothing but a miracle ___ save him.", choices: ["can", "cans", "to", "being"], answer: 0, ja: "奇跡だけが彼を救える。", note: "nothing but=~だけ" },
    { q: "___ having little money, he was happy.", choices: ["Despite", "Although", "Because", "However"], answer: 0, ja: "お金は少なかったが幸せだった。", note: "despite+名詞/動名詞" },
    { q: "So long ___ you try, you'll improve.", choices: ["as", "than", "that", "for"], answer: 0, ja: "努力する限り上達する。", note: "so long as=~する限り" },
    { q: "He looked at me ___ if to say no.", choices: ["as", "so", "even", "just"], answer: 0, ja: "彼はノーと言うように私を見た。", note: "as if to do" },
    { q: "Rarely ___ we see such talent.", choices: ["do", "does", "is", "has"], answer: 0, ja: "そのような才能を見ることはめったにない。", note: "Rarely+倒置do we" },
    { q: "The taller of the two brothers ___ Ken.", choices: ["is", "are", "were", "have"], answer: 0, ja: "2人の兄弟のうち背が高い方はケンだ。", note: "the 比較級 of the two+単数is" },
    { q: "___ the situation, we did well.", choices: ["Given", "Giving", "Give", "To give"], answer: 0, ja: "状況を考えれば、よくやった。", note: "Given+名詞=~を考えると" },
    { q: "He worked hard, ___ made him successful.", choices: ["which", "that", "what", "who"], answer: 0, ja: "彼は懸命に働き、それが成功をもたらした。", note: "非制限用法which" },
    { q: "I can't but ___ he is right.", choices: ["think", "thinking", "to think", "thought"], answer: 0, ja: "彼が正しいと思わざるを得ない。", note: "cannot but+原形" },
    { q: "The reason ___ he failed is unclear.", choices: ["why", "which", "where", "how"], answer: 0, ja: "彼が失敗した理由は不明だ。", note: "関係副詞why" },
    { q: "That was the way ___ he solved it.", choices: ["in which", "which", "what", "why"], answer: 0, ja: "それが彼の解決方法だった。", note: "the way in which=how" },
    { q: "He is not so much a scholar ___ a writer.", choices: ["as", "than", "but", "that"], answer: 0, ja: "彼は学者というより作家だ。", note: "not so much A as B" },
    { q: "Try ___ you may, you can't win.", choices: ["as", "so", "that", "though"], answer: 0, ja: "どんなに頑張っても勝てない。", note: "Try as you may(譲歩)" },
    { q: "The book is worth ___ carefully.", choices: ["reading", "read", "to read", "readed"], answer: 0, ja: "その本は丁寧に読む価値がある。", note: "worth ~ing" },
    { q: "It was such a moving story ___ we cried.", choices: ["that", "as", "which", "than"], answer: 0, ja: "とても感動的な話で泣いた。", note: "such ~ that" },
    { q: "___ do I dream of giving up.", choices: ["Never", "Ever", "Always", "Often"], answer: 0, ja: "あきらめようとは決して思わない。", note: "Never文頭+倒置" },
    { q: "He made up his mind ___ abroad.", choices: ["to go", "going", "go", "went"], answer: 0, ja: "彼は海外へ行く決心をした。", note: "make up one's mind to do" },
    { q: "I object ___ being treated like this.", choices: ["to", "for", "of", "with"], answer: 0, ja: "こう扱われるのに反対だ。", note: "object to ~ing" },
    { q: "The house is ___ construction.", choices: ["under", "on", "in", "at"], answer: 0, ja: "その家は建設中だ。", note: "under construction" },
    { q: "He acted ___ behalf of the team.", choices: ["on", "in", "at", "for"], answer: 0, ja: "彼はチームを代表して行動した。", note: "on behalf of" },
    { q: "In ___ of the rain, the game went on.", choices: ["spite", "case", "front", "place"], answer: 0, ja: "雨にもかかわらず試合は続いた。", note: "in spite of" },
    { q: "By ___ means are you to enter.", choices: ["no", "any", "some", "all"], answer: 0, ja: "決して入ってはならない。", note: "by no means+倒置" },
    { q: "He owes his success ___ hard work.", choices: ["to", "for", "of", "on"], answer: 0, ja: "彼の成功は努力のおかげだ。", note: "owe A to B" },
    { q: "The plan fell ___.", choices: ["through", "down", "off", "in"], answer: 0, ja: "計画はだめになった。", note: "fall through=失敗する" },
    { q: "We must do away ___ this rule.", choices: ["with", "of", "to", "for"], answer: 0, ja: "この規則を廃止すべきだ。", note: "do away with=廃止する" },
    { q: "He looks down ___ others.", choices: ["on", "at", "to", "for"], answer: 0, ja: "彼は他人を見下す。", note: "look down on" },
    { q: "I came ___ this word by chance.", choices: ["across", "over", "off", "into"], answer: 0, ja: "偶然この単語に出会った。", note: "come across=偶然見つける" },
    { q: "She takes ___ her mother.", choices: ["after", "off", "up", "in"], answer: 0, ja: "彼女は母親似だ。", note: "take after=似ている" },
    { q: "Please account ___ your absence.", choices: ["for", "of", "to", "with"], answer: 0, ja: "欠席の理由を説明して。", note: "account for=説明する" },
    { q: "He is bound ___ succeed.", choices: ["to", "for", "of", "on"], answer: 0, ja: "彼はきっと成功する。", note: "be bound to=きっと~する" },
    { q: "I'm on the ___ of leaving.", choices: ["point", "verge to", "edge to", "way"], answer: 0, ja: "まさに出発しようとしている。", note: "on the point of ~ing" },
    { q: "___ all his faults, I like him.", choices: ["For", "With", "By", "To"], answer: 0, ja: "欠点はあるが彼が好きだ。", note: "for all=~にもかかわらず" },
    { q: "He is second ___ none.", choices: ["to", "than", "of", "for"], answer: 0, ja: "彼は誰にも劣らない。", note: "second to none" },
    { q: "This is where the accident ___.", choices: ["took place", "took part", "made", "did"], answer: 0, ja: "ここが事故の起きた場所だ。", note: "take place=起こる" },
    { q: "It dawned ___ me that he lied.", choices: ["on", "to", "for", "at"], answer: 0, ja: "彼が嘘をついたと気づき始めた。", note: "it dawns on ~" },
    { q: "If I had wings, I ___ fly to you.", choices: ["would", "will", "can", "must"], answer: 0, ja: "翼があれば君のもとへ飛ぶのに。", note: "仮定法過去would" },
    { q: "Were I rich, I ___ travel the world.", choices: ["would", "will", "can", "do"], answer: 0, ja: "金持ちなら世界を旅するのに。", note: "if省略の倒置Were I" },
    { q: "I wish it ___ true.", choices: ["were", "is", "will", "has"], answer: 0, ja: "それが本当ならなあ。", note: "I wish+were" },
    { q: "Seldom ___ he make mistakes.", choices: ["does", "do", "is", "has"], answer: 0, ja: "彼はめったに間違えない。", note: "Seldom+倒置does he" },
    { q: "Only then ___ I realize the truth.", choices: ["did", "does", "was", "have"], answer: 0, ja: "そのとき初めて真実に気づいた。", note: "Only then+倒置did I" },
    { q: "Not until midnight ___ he return.", choices: ["did", "does", "was", "has"], answer: 0, ja: "真夜中になって彼はやっと戻った。", note: "Not until+倒置did he" },
    { q: "So beautiful was the view ___ we stopped.", choices: ["that", "as", "which", "than"], answer: 0, ja: "景色が美しくて立ち止まった。", note: "So+形+倒置+that" },
    { q: "The work ___, we went home.", choices: ["done", "doing", "do", "to do"], answer: 0, ja: "仕事が終わって帰宅した。", note: "独立分詞構文(受動)done" },
    { q: "There ___ no bus, we walked.", choices: ["being", "is", "was", "been"], answer: 0, ja: "バスがなかったので歩いた。", note: "There being no ~(分詞構文)" },
    { q: "He is the very man ___ we need.", choices: ["that", "which", "what", "whose"], answer: 0, ja: "彼こそ私たちが必要とする人だ。", note: "the very+先行詞はthat" },
    { q: "He has no friend to rely ___.", choices: ["on", "to", "for", "with"], answer: 0, ja: "彼には頼れる友がいない。", note: "rely on(前置詞を残す)" },
    { q: "It is imperative that he ___ informed.", choices: ["be", "is", "was", "being"], answer: 0, ja: "彼に知らせることが絶対必要だ。", note: "imperative that S+(should)be" },
    { q: "The committee demanded that she ___.", choices: ["resign", "resigns", "resigned", "resigning"], answer: 0, ja: "委員会は彼女の辞任を要求した。", note: "demand that S+原形" },
    { q: "Such was the noise ___ nobody could sleep.", choices: ["that", "as", "which", "than"], answer: 0, ja: "騒音がひどく誰も眠れなかった。", note: "Such was ~ that" },
    { q: "No matter ___ hard it is, try.", choices: ["how", "what", "which", "who"], answer: 0, ja: "どんなに難しくても挑戦しろ。", note: "no matter how+形/副" },
    { q: "He is far too proud ___ apologize.", choices: ["to", "for", "that", "so"], answer: 0, ja: "彼はプライドが高すぎて謝れない。", note: "too ~ to do" },
    { q: "I can't help ___ that he is right.", choices: ["feeling", "feel", "to feel", "felt"], answer: 0, ja: "彼が正しいと感じずにいられない。", note: "can't help ~ing" },
    { q: "It's worth ___ the effort.", choices: ["making", "make", "to make", "made"], answer: 0, ja: "努力する価値がある。", note: "worth ~ing" },
    { q: "She objected ___ working late.", choices: ["to", "for", "of", "against"], answer: 0, ja: "彼女は遅くまで働くのに反対した。", note: "object to ~ing" },
    { q: "The plan is likely ___ succeed.", choices: ["to", "for", "of", "that"], answer: 0, ja: "その計画は成功しそうだ。", note: "be likely to do" },
    { q: "He looks as though he ___ seen a ghost.", choices: ["had", "has", "will", "is"], answer: 0, ja: "彼はまるで幽霊を見たような顔だ。", note: "as though+過去完了" },
    { q: "Had it not been ___ you, I'd be lost.", choices: ["for", "to", "of", "with"], answer: 0, ja: "あなたがいなければ途方に暮れていた。", note: "Had it not been for=~がなければ" },
    { q: "___ being poor, they were happy.", choices: ["Despite", "Although", "Because", "However"], answer: 0, ja: "貧しかったが彼らは幸せだった。", note: "despite+動名詞" },
    { q: "He devoted himself ___ helping others.", choices: ["to", "for", "of", "on"], answer: 0, ja: "彼は他人を助けることに専念した。", note: "devote oneself to ~ing" },
    { q: "I'm looking forward ___ hearing from you.", choices: ["to", "for", "of", "at"], answer: 0, ja: "ご連絡を楽しみにしています。", note: "look forward to ~ing" },
    { q: "Scarcely ___ we arrived when it rained.", choices: ["had", "has", "did", "was"], answer: 0, ja: "着くやいなや雨が降った。", note: "Scarcely had+S+pp" },
    { q: "By no ___ should you quit.", choices: ["means", "way", "matter", "doubt"], answer: 0, ja: "決してやめてはならない。", note: "by no means+倒置" },
  ],
};
