// ギルド依頼プール(事前定義)。ボードはこの中からランダムで3件出題する。
// type: "areaboss"(エリアボス討伐) / "hunt"(討伐) / "talk"(会話チャレンジ)
//  areaboss: boss(=AREA_BOSSESのキー), zone。受けるとフィールドにボスが出現(コマンドバトル)。
//  hunt : enemy(=ENEMIESの敵名, "any"なら何でも), count
//  talk : npcId(=対象NPCのid), goal_en(英語の達成目標), goal_ja(日本語のお題)
// 共通: title_ja(一覧の見出し), desc_ja(詳細説明), flavor_en(受付Fiaの一言)
// ※報酬(ゴールド/GP)はゲーム側(rewardFor)で自動計算するのでここには書かない。
// ※おつかい(fetch)は簡単すぎるため廃止。討伐と会話チャレンジ中心の構成。
const QUEST_POOL = [
  // ===== エリアボス討伐(areaboss) ===== 受けるとフィールドにボスが出現。普通のコマンドバトル(コトハ参戦)。
  { type: "areaboss", boss: "ogre",   zone: "field", title_ja: "オーガ将軍の討伐",   desc_ja: "フィールドに現れたオーガ将軍を討伐しよう。受けるとフィールドに出現する。", flavor_en: "A brutish ogre general is rampaging in the fields. Take it down!" },
  { type: "areaboss", boss: "golem",  zone: "field", title_ja: "石巨人の討伐",       desc_ja: "フィールドをさまよう石巨人ゴーレムを討伐しよう。受けるとフィールドに出現する。", flavor_en: "A stone golem blocks the road. Smash it to pieces!" },
  { type: "areaboss", boss: "wyvern", zone: "field", title_ja: "ワイバーンの討伐",   desc_ja: "フィールドの空を舞うワイバーンを討伐しよう。受けるとフィールドに出現する。", flavor_en: "A fierce wyvern hunts travelers from the sky. Bring it down!" },

  // ===== 討伐(hunt) =====
  { type: "hunt", enemy: "スライム",     count: 3, title_ja: "スライム退治",       desc_ja: "フィールドでスライムを3体たおそう。",       flavor_en: "Slimes are everywhere lately. Can you thin them out?" },
  { type: "hunt", enemy: "スライム",     count: 5, title_ja: "大量発生のスライム",   desc_ja: "フィールドでスライムを5体たおそう。",       flavor_en: "There's a slime outbreak! Five should do it." },
  { type: "hunt", enemy: "おおコウモリ", count: 3, title_ja: "おおコウモリ退治",     desc_ja: "フィールドでおおコウモリを3体たおそう。",   flavor_en: "Bats are scaring travelers. Please drive them off!" },
  { type: "hunt", enemy: "おおコウモリ", count: 5, title_ja: "コウモリの群れ退治",   desc_ja: "フィールドでおおコウモリを5体たおそう。",   flavor_en: "A whole swarm of bats! Five of them, please." },
  { type: "hunt", enemy: "ゴースト",     count: 4, title_ja: "ゴースト退治",       desc_ja: "フィールドでゴーストを4体たおそう。",       flavor_en: "Ghosts haunt the road at night. We need your help!" },
  { type: "hunt", enemy: "ゴースト",     count: 6, title_ja: "夜のゴースト掃討",     desc_ja: "フィールドでゴーストを6体たおそう。",       flavor_en: "The night road is thick with ghosts. Clear six of them!" },
  { type: "hunt", enemy: "アーマー兵",   count: 4, title_ja: "アーマー兵退治",     desc_ja: "フィールドでアーマー兵を4体たおそう。",     flavor_en: "Rogue armored soldiers are on the loose. Be careful!" },
  { type: "hunt", enemy: "アーマー兵",   count: 6, title_ja: "精鋭アーマー兵の討伐", desc_ja: "フィールドでアーマー兵を6体たおそう。",     flavor_en: "Elite armored troops are gathering. Take down six!" },
  { type: "hunt", enemy: "any",          count: 8, title_ja: "見回りの討伐",         desc_ja: "フィールドやダンジョンでモンスターを合計8体たおそう(種類はなんでもOK)。", flavor_en: "The roads are dangerous. Cull any eight monsters you meet!" },
  { type: "hunt", enemy: "any",          count: 12, title_ja: "大討伐依頼",         desc_ja: "モンスターを合計12体たおそう(種類はなんでもOK)。歯ごたえのある依頼だ。", flavor_en: "A big cull is needed. Twelve monsters — any kind will do!" },

  // ===== 会話チャレンジ(talk) ===== 対象NPCに英語で話しかけ、お題を英語で達成する。
  // --- 基本(たずねる・注文する) ---
  { type: "talk", npcId: "hospital",   goal_en: "describe your symptoms to the doctor and ask for advice", goal_ja: "医者に症状を説明して助言をもらう", title_ja: "医者に症状を相談する", desc_ja: "病院のHaleに英語で話しかけ、症状を説明して助言をもらおう。",       flavor_en: "A patient is shy. Show them how to explain symptoms to the doctor!" },
  { type: "talk", npcId: "bar",        goal_en: "order a drink and ask the bartender about a local rumor", goal_ja: "飲み物を注文し、町の噂を聞き出す", title_ja: "一杯注文して噂を聞く", desc_ja: "バーのSalに英語で話しかけ、飲み物を注文しつつ町の噂を聞き出そう。", flavor_en: "Sal knows all the gossip — order a drink and get him talking!" },
  { type: "talk", npcId: "police",     goal_en: "ask the guard for directions to the castle and whether the road is safe", goal_ja: "衛兵に城への道と安全を確認する", title_ja: "城への道をたずねる", desc_ja: "警察署のBrunoに英語で話しかけ、城への道と道中の安全をたずねよう。", flavor_en: "A traveler is lost. Ask the guard the way — and if it's safe!" },
  { type: "talk", npcId: "restaurant", goal_en: "ask the cook to recommend today's special and how much it costs", goal_ja: "本日のおすすめと値段を聞く", title_ja: "おすすめと値段を聞く", desc_ja: "飲食店のTomに英語で話しかけ、本日のおすすめとその値段を聞こう。", flavor_en: "Tom loves to recommend his dishes. Go ask him — and the price!" },
  { type: "talk", npcId: "bank",       goal_en: "ask how to open a bank account and how to keep your gold safe", goal_ja: "口座の開き方と貯金の相談をする", title_ja: "口座について相談する", desc_ja: "銀行のGretaに英語で話しかけ、口座の開き方や貯金の方法を聞こう。", flavor_en: "Greta can explain banking. Practice asking her!" },
  { type: "talk", npcId: "church",     goal_en: "ask the sister for a blessing and explain where your journey will take you", goal_ja: "旅の祝福を願い、行き先を伝える", title_ja: "旅の祝福をお願いする", desc_ja: "教会のClaraに英語で話しかけ、旅の祝福を願い、これから行く先を伝えよう。", flavor_en: "Before a long trip, ask Clara for a blessing." },

  // --- 説明する・語る(少し歯ごたえあり) ---
  { type: "talk", npcId: "adv_rex",    goal_en: "describe a monster you fought and ask the veteran for a tip to beat it", goal_ja: "戦ったモンスターを描写し、攻略のコツを聞く", title_ja: "モンスター攻略を相談する", desc_ja: "ギルドの冒険者Rexに英語で話しかけ、戦ったモンスターを説明して攻略のコツを聞こう。", flavor_en: "Rex loves monster talk. Describe your foe and ask his advice!" },
  { type: "talk", npcId: "adv_mina",   goal_en: "explain why you became an adventurer and ask the mage about magic", goal_ja: "冒険者になった理由を語り、魔法を聞く", title_ja: "冒険の動機を語る", desc_ja: "ギルドの魔法使いMinaに英語で話しかけ、冒険者になった理由を語り、魔法について聞こう。", flavor_en: "Mina is curious about people. Tell her your story!" },
  { type: "talk", npcId: "adv_pip",    goal_en: "encourage the nervous rookie and give him one piece of advice for his quest", goal_ja: "新人を励まし、助言を一つ贈る", title_ja: "新人を励ます", desc_ja: "ギルドの新人冒険者Pipに英語で話しかけ、励ましつつ助言を一つ贈ろう。", flavor_en: "Pip's nervous about a quest. Give him courage and a tip!" },
  { type: "talk", npcId: "school",     goal_en: "introduce yourself to the teacher and ask him to explain an English word", goal_ja: "自己紹介し、英単語の意味を教わる", title_ja: "自己紹介して質問する", desc_ja: "学校のEdwinに英語で話しかけ、自己紹介をしてから英単語の意味を教わろう。", flavor_en: "Edwin welcomes new faces. Introduce yourself and ask a question!" },
  { type: "talk", npcId: "smith",      goal_en: "ask the blacksmith to compare two weapons and recommend one for you", goal_ja: "2つの武器を比べて、おすすめを聞く", title_ja: "武器を比べて相談する", desc_ja: "鍛冶屋のBorinに英語で話しかけ、2つの武器を比べてもらい、おすすめを聞こう。", flavor_en: "Borin's proud of his blades. Ask him to compare two!" },
  { type: "talk", npcId: "bard",       goal_en: "compliment the bard's song and ask her to teach you the words", goal_ja: "歌をほめ、歌詞を教わる", title_ja: "歌をほめて教わる", desc_ja: "町の吟遊詩人Lyraに英語で話しかけ、歌をほめてから歌詞を教わろう。", flavor_en: "Lyra's been gloomy. Praise her song and ask to learn it!" },
  { type: "talk", npcId: "innkeeper",  goal_en: "check in for the night and ask the innkeeper about the room and breakfast", goal_ja: "宿にチェックインし、部屋と朝食を確認する", title_ja: "宿の予約をする", desc_ja: "宿屋のMarianに英語で話しかけ、宿泊の手続きをして部屋や朝食について聞こう。", flavor_en: "Show a traveler how to check in and ask about the room!" },

  // --- 新しい町の店(不動産・家電・花屋・美容院) ---
  { type: "talk", npcId: "realestate", goal_en: "describe your dream house to the agent and ask what she recommends", goal_ja: "理想の家を伝え、おすすめを聞く", title_ja: "理想の家を相談する", desc_ja: "不動産屋のEstelleに英語で話しかけ、理想の家を説明しておすすめを聞こう。", flavor_en: "Estelle loves matching people to homes. Describe your dream house!" },
  { type: "talk", npcId: "appliance",  goal_en: "ask Den to recommend an appliance for your new home and why", goal_ja: "新居におすすめの家電とその理由を聞く", title_ja: "家電のおすすめを聞く", desc_ja: "家電屋のDenに英語で話しかけ、新居におすすめの家電とその理由を聞こう。", flavor_en: "Den loves his appliances. Ask him what to buy for a new home!" },
  { type: "talk", npcId: "florist",    goal_en: "ask the florist to recommend flowers for a gift and explain who they are for", goal_ja: "贈り物の花を相談し、相手を伝える", title_ja: "贈り物の花を選ぶ", desc_ja: "花屋のLilyに英語で話しかけ、贈り物の花を相談して、誰への贈り物か伝えよう。", flavor_en: "Lily lights up for kind words. Ask her to pick a gift bouquet!" },
  { type: "talk", npcId: "salon",      goal_en: "tell the stylist how you want your hair and ask her opinion", goal_ja: "希望の髪型を伝え、意見を聞く", title_ja: "髪型を相談する", desc_ja: "美容院のCocoに英語で話しかけ、希望の髪型を伝えて意見を聞こう。", flavor_en: "Coco loves a makeover chat. Tell her your style!" },

  // --- 食料品店(市場)の店主たち ---
  { type: "talk", npcId: "fish",       goal_en: "ask the fishmonger what the freshest catch is today and how to cook it", goal_ja: "今日の一番の魚と調理法を聞く", title_ja: "おすすめの魚を聞く", desc_ja: "魚屋のFinnに英語で話しかけ、今日の一番の魚とその調理法を聞こう。", flavor_en: "Finn knows his fish. Ask about the day's best catch!" },
  { type: "talk", npcId: "green",      goal_en: "ask the greengrocer which vegetables are in season and why they're good", goal_ja: "旬の野菜とその良さを聞く", title_ja: "旬の野菜を聞く", desc_ja: "八百屋のVeraに英語で話しかけ、旬の野菜とその良さを聞こう。", flavor_en: "Vera knows what's fresh. Ask what's in season!" },
  { type: "talk", npcId: "meat",       goal_en: "ask the butcher to recommend meat for a barbecue and how much you need", goal_ja: "バーベキュー用の肉と量を相談する", title_ja: "バーベキューの相談", desc_ja: "肉屋のOttoに英語で話しかけ、バーベキュー用の肉とその量を相談しよう。", flavor_en: "Otto loves a barbecue. Ask him what to grill!" },
  { type: "talk", npcId: "grocery",    goal_en: "ask the grocer for a simple recipe and what ingredients you need", goal_ja: "簡単なレシピと必要な材料を聞く", title_ja: "レシピを教わる", desc_ja: "食料品店のMarcoに英語で話しかけ、簡単なレシピと必要な材料を教わろう。", flavor_en: "Marco loves cooking tips. Ask him for a recipe!" },

  // --- ギルド・武器屋・素材屋(冒険まわり) ---
  { type: "talk", npcId: "guild_receptionist", goal_en: "ask the receptionist how the guild ranking system works", goal_ja: "ギルドのランク制度を聞く", title_ja: "ギルドの仕組みを聞く", desc_ja: "ギルド受付のFiaに英語で話しかけ、ギルドのランク制度の仕組みを聞こう。", flavor_en: "Fia can explain how the guild works. Ask her about ranks!" },
  { type: "talk", npcId: "guild_receptionist", goal_en: "ask the receptionist to recommend a good quest for you today", goal_ja: "今日のおすすめ依頼を聞く", title_ja: "おすすめ依頼を聞く", desc_ja: "ギルド受付のFiaに英語で話しかけ、今日のおすすめの依頼を聞こう。", flavor_en: "Not sure what to take? Ask Fia for a recommendation!" },
  { type: "talk", npcId: "guild_receptionist", goal_en: "ask the receptionist how to earn more guild points", goal_ja: "ギルドポイントの稼ぎ方を聞く", title_ja: "ポイントの稼ぎ方を聞く", desc_ja: "ギルド受付のFiaに英語で話しかけ、ギルドポイントを多く稼ぐ方法を聞こう。", flavor_en: "Fia knows the ins and outs. Ask how to earn more points!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper to recommend a weapon for a beginner", goal_ja: "初心者向けの武器を聞く", title_ja: "初心者の武器を相談する", desc_ja: "武器屋のDunnに英語で話しかけ、初心者向けのおすすめ武器を聞こう。", flavor_en: "Dunn takes pride in his wares. Ask what suits a beginner!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper how to take care of your sword", goal_ja: "剣の手入れ方法を聞く", title_ja: "剣の手入れを聞く", desc_ja: "武器屋のDunnに英語で話しかけ、剣の手入れの仕方を教わろう。", flavor_en: "A good blade needs care. Ask Dunn how to keep it sharp!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper about the strongest weapon he has ever made", goal_ja: "今まで作った最強の武器を聞く", title_ja: "最強の武器を聞く", desc_ja: "武器屋のDunnに英語で話しかけ、今まで作った最強の武器の話を聞こう。", flavor_en: "Dunn loves to boast. Ask about his finest blade!" },
  { type: "talk", npcId: "matshop",    goal_en: "haggle with the trader for a better price on your materials", goal_ja: "素材を高く買ってもらうよう値切る", title_ja: "素材を値切る", desc_ja: "素材屋のGilに英語で話しかけ、素材をもっと高く買ってもらうよう交渉しよう。", flavor_en: "Gil loves a deal. See if you can haggle a better price!" },
  { type: "talk", npcId: "matshop",    goal_en: "ask the trader which monster materials sell for the most", goal_ja: "高く売れる素材を聞く", title_ja: "高く売れる素材を聞く", desc_ja: "素材屋のGilに英語で話しかけ、どの素材が高く売れるのか聞こう。", flavor_en: "Gil knows the market. Ask which drops are worth the most!" },

  // --- 語る・相談する(やや高度: 描写/説明/交渉/仮定) ---
  { type: "talk", npcId: "adv_rex",    goal_en: "ask the veteran to tell the story of his greatest battle", goal_ja: "一番の武勇伝を聞く", title_ja: "武勇伝を聞く", desc_ja: "冒険者Rexに英語で話しかけ、彼の一番の武勇伝を聞き出そう。", flavor_en: "Rex has a thousand tales. Ask for his greatest one!" },
  { type: "talk", npcId: "adv_mina",   goal_en: "ask the mage to recommend a book and explain what it's about", goal_ja: "おすすめの本とその内容を聞く", title_ja: "おすすめの本を聞く", desc_ja: "魔法使いMinaに英語で話しかけ、おすすめの本とその内容を聞こう。", flavor_en: "Mina reads endlessly. Ask her for a book to enjoy!" },
  { type: "talk", npcId: "adv_pip",    goal_en: "invite the rookie to team up with you for a quest", goal_ja: "新人を依頼に誘う", title_ja: "新人を誘う", desc_ja: "新人冒険者Pipに英語で話しかけ、一緒に依頼へ行こうと誘おう。", flavor_en: "Pip would love a partner. Invite him on a quest!" },
  { type: "talk", npcId: "restaurant", goal_en: "explain a dish from your homeland to the cook", goal_ja: "故郷の料理を料理人に説明する", title_ja: "故郷の料理を紹介する", desc_ja: "飲食店のTomに英語で話しかけ、故郷の料理がどんなものか説明しよう。", flavor_en: "Tom's curious about foreign food. Describe a dish!" },
  { type: "talk", npcId: "bar",        goal_en: "tell the bartender about your day and how you feel", goal_ja: "今日の出来事と気分を話す", title_ja: "今日のことを話す", desc_ja: "バーのSalに英語で話しかけ、今日あった出来事と今の気分を話そう。", flavor_en: "Sal's a good listener. Tell him about your day!" },
  { type: "talk", npcId: "bank",       goal_en: "ask the teller about a loan to buy a house", goal_ja: "家を買うためのローンを相談する", title_ja: "ローンを相談する", desc_ja: "銀行のGretaに英語で話しかけ、家を買うためのローンについて相談しよう。", flavor_en: "Dreaming of a home? Ask Greta about a loan!" },
  { type: "talk", npcId: "school",     goal_en: "ask the teacher for advice on how to study English", goal_ja: "英語の勉強法を相談する", title_ja: "英語の勉強法を聞く", desc_ja: "学校のEdwinに英語で話しかけ、英語の勉強のコツを相談しよう。", flavor_en: "Edwin loves teaching. Ask him how to study well!" },
  { type: "talk", npcId: "church",     goal_en: "share a worry with the sister and ask for comfort", goal_ja: "悩みを打ち明けて励ましてもらう", title_ja: "悩みを打ち明ける", desc_ja: "教会のClaraに英語で話しかけ、悩みを打ち明けて励ましてもらおう。", flavor_en: "Clara offers comfort to all. Share what troubles you." },
  { type: "talk", npcId: "hospital",   goal_en: "ask the doctor for tips to sleep better at night", goal_ja: "よく眠るコツを聞く", title_ja: "睡眠のコツを聞く", desc_ja: "病院のHaleに英語で話しかけ、夜ぐっすり眠るコツを聞こう。", flavor_en: "Trouble sleeping? Ask Hale for advice!" },
  { type: "talk", npcId: "police",     goal_en: "report a lost item to the guard and describe it in detail", goal_ja: "落とし物を届け出て特徴を説明する", title_ja: "落とし物を届け出る", desc_ja: "警察署のBrunoに英語で話しかけ、落とし物を届け出て、その特徴を説明しよう。", flavor_en: "Found something lost? Report it and describe it to Bruno!" },
  { type: "talk", npcId: "smith",      goal_en: "ask the blacksmith to repair your armor and how long it will take", goal_ja: "防具の修理と所要時間を聞く", title_ja: "防具の修理を頼む", desc_ja: "鍛冶屋のBorinに英語で話しかけ、防具の修理を頼み、どれくらいかかるか聞こう。", flavor_en: "Armor worn out? Ask Borin to fix it — and how long it takes!" },
  { type: "talk", npcId: "bard",       goal_en: "ask the bard to tell a legend about the Demon King", goal_ja: "魔王の伝説を聞く", title_ja: "魔王の伝説を聞く", desc_ja: "吟遊詩人Lyraに英語で話しかけ、魔王にまつわる伝説を聞かせてもらおう。", flavor_en: "Lyra knows old legends. Ask her about the Demon King!" },
  { type: "talk", npcId: "innkeeper",  goal_en: "ask the innkeeper what there is to do around town", goal_ja: "町での過ごし方をたずねる", title_ja: "町の楽しみ方を聞く", desc_ja: "宿屋のMarianに英語で話しかけ、町でできることをたずねよう。", flavor_en: "New in town? Ask Marian what to see and do!" },

  // --- お店で相談する(新しい店・市場) ---
  { type: "talk", npcId: "realestate", goal_en: "ask the agent to compare a cottage and a manor and their prices", goal_ja: "コテージと邸宅を比べてもらう", title_ja: "物件を比べて相談する", desc_ja: "不動産屋のEstelleに英語で話しかけ、コテージと邸宅を値段も含めて比べてもらおう。", flavor_en: "Cottage or manor? Ask Estelle to compare them!" },
  { type: "talk", npcId: "appliance",  goal_en: "ask Den whether he delivers and installs the appliance at your home", goal_ja: "配送と設置をしてくれるか聞く", title_ja: "配送・設置を頼めるか聞く", desc_ja: "家電屋のDenに英語で話しかけ、買った家電を家まで配送・設置してくれるか聞こう。", flavor_en: "Big appliance to carry? Ask Den about delivery and setup!" },
  { type: "talk", npcId: "florist",    goal_en: "ask the florist the meaning of a flower you like", goal_ja: "好きな花の花言葉を聞く", title_ja: "花言葉を聞く", desc_ja: "花屋のLilyに英語で話しかけ、好きな花の花言葉を聞いてみよう。", flavor_en: "Flowers carry meaning. Ask Lily what yours says!" },
  { type: "talk", npcId: "salon",      goal_en: "ask the stylist for advice to look good for a party", goal_ja: "パーティー向けの身だしなみを相談する", title_ja: "パーティーの準備を相談する", desc_ja: "美容院のCocoに英語で話しかけ、パーティーで映える身だしなみを相談しよう。", flavor_en: "Big party coming? Ask Coco how to look your best!" },
  { type: "talk", npcId: "fish",       goal_en: "ask the fishmonger for a discount on the tuna and explain why", goal_ja: "マグロの値引きを理由つきで頼む", title_ja: "マグロを値切る", desc_ja: "魚屋のFinnに英語で話しかけ、理由を添えてマグロの値引きを頼もう。", flavor_en: "Feeling bold? Ask Finn for a discount on the tuna!" },
  { type: "talk", npcId: "green",      goal_en: "ask the greengrocer how to keep vegetables fresh at home", goal_ja: "野菜を長持ちさせる方法を聞く", title_ja: "野菜の保存を聞く", desc_ja: "八百屋のVeraに英語で話しかけ、野菜を家で長持ちさせる方法を聞こう。", flavor_en: "Vera knows her produce. Ask how to keep it fresh!" },
  { type: "talk", npcId: "meat",       goal_en: "ask the butcher how to grill meat so it turns out perfect", goal_ja: "肉を上手に焼くコツを聞く", title_ja: "肉の焼き方を聞く", desc_ja: "肉屋のOttoに英語で話しかけ、肉を上手に焼くコツを聞こう。", flavor_en: "Otto's a grill master. Ask him for the perfect sear!" },
  { type: "talk", npcId: "grocery",    goal_en: "ask the grocer which seasoning goes well with fish", goal_ja: "魚に合う調味料を聞く", title_ja: "魚に合う調味料を聞く", desc_ja: "食料品店のMarcoに英語で話しかけ、魚料理に合う調味料を聞こう。", flavor_en: "Marco knows his pantry. Ask what pairs with fish!" },

  // ===== 会話チャレンジ 追加分(合計100件へ) =====
  // --- 病院・バー・警察・飲食店・銀行・教会 ---
  { type: "talk", npcId: "hospital",   goal_en: "describe a friend's injury to the doctor and ask what to do", goal_ja: "友人のケガを説明して対処を聞く", title_ja: "友人のケガを相談する", desc_ja: "病院のHaleに英語で話しかけ、友人のケガの様子を説明して、どうすればいいか聞こう。", flavor_en: "A friend got hurt? Explain it to Hale and ask for help!" },
  { type: "talk", npcId: "hospital",   goal_en: "ask the doctor what foods are good for staying healthy", goal_ja: "体にいい食べ物を聞く", title_ja: "体にいい食べ物を聞く", desc_ja: "病院のHaleに英語で話しかけ、健康にいい食べ物を教わろう。", flavor_en: "Hale knows nutrition. Ask what's good to eat!" },
  { type: "talk", npcId: "bar",        goal_en: "ask the bartender to recommend a drink for someone who dislikes alcohol", goal_ja: "お酒が苦手な人向けの一杯を聞く", title_ja: "ノンアルの一杯を聞く", desc_ja: "バーのSalに英語で話しかけ、お酒が苦手な人向けの飲み物を聞こう。", flavor_en: "Not a drinker? Ask Sal for something soft!" },
  { type: "talk", npcId: "bar",        goal_en: "tell the bartender a funny thing that happened on your journey", goal_ja: "旅で起きた面白い話をする", title_ja: "旅の面白い話をする", desc_ja: "バーのSalに英語で話しかけ、旅の途中で起きた面白い出来事を話そう。", flavor_en: "Sal loves a good yarn. Share a funny travel tale!" },
  { type: "talk", npcId: "police",     goal_en: "ask the guard what to do if you get lost outside town", goal_ja: "町の外で迷ったときの対処を聞く", title_ja: "迷ったときの対処を聞く", desc_ja: "警察署のBrunoに英語で話しかけ、町の外で迷ったらどうすべきか聞こう。", flavor_en: "Worried about getting lost? Ask Bruno what to do!" },
  { type: "talk", npcId: "police",     goal_en: "thank the guard for keeping the town safe", goal_ja: "町を守る衛兵に感謝を伝える", title_ja: "衛兵に感謝する", desc_ja: "警察署のBrunoに英語で話しかけ、町を守ってくれていることに感謝を伝えよう。", flavor_en: "Bruno works hard. A word of thanks would mean a lot!" },
  { type: "talk", npcId: "restaurant", goal_en: "ask the cook to make a dish without a certain ingredient you can't eat", goal_ja: "苦手な食材を抜いてもらうよう頼む", title_ja: "苦手な食材を抜いてもらう", desc_ja: "飲食店のTomに英語で話しかけ、食べられない食材を抜いて作ってもらえるか頼もう。", flavor_en: "Got a dislike? Ask Tom to leave it out!" },
  { type: "talk", npcId: "restaurant", goal_en: "compliment the meal and ask the cook what's in it", goal_ja: "料理をほめて中身を聞く", title_ja: "料理をほめて中身を聞く", desc_ja: "飲食店のTomに英語で話しかけ、料理をほめてから何が入っているか聞こう。", flavor_en: "Enjoyed the food? Praise it and ask the recipe!" },
  { type: "talk", npcId: "bank",       goal_en: "ask the teller how to send money to a friend in another town", goal_ja: "遠くの友人への送金方法を聞く", title_ja: "送金の方法を聞く", desc_ja: "銀行のGretaに英語で話しかけ、別の町の友人にお金を送る方法を聞こう。", flavor_en: "Need to send gold far away? Ask Greta how!" },
  { type: "talk", npcId: "bank",       goal_en: "report that you lost your wallet and ask the teller what to do", goal_ja: "財布をなくしたと相談する", title_ja: "財布の紛失を相談する", desc_ja: "銀行のGretaに英語で話しかけ、財布をなくしたことを伝えて対処を相談しよう。", flavor_en: "Lost your wallet? Tell Greta and ask for help!" },
  { type: "talk", npcId: "church",     goal_en: "ask the sister to pray for a sick friend", goal_ja: "病気の友人のために祈ってもらう", title_ja: "友人の快復を祈ってもらう", desc_ja: "教会のClaraに英語で話しかけ、病気の友人のために祈ってもらおう。", flavor_en: "A friend is ill? Ask Clara for a prayer." },
  { type: "talk", npcId: "church",     goal_en: "ask the sister about the history of the church", goal_ja: "教会の歴史をたずねる", title_ja: "教会の歴史を聞く", desc_ja: "教会のClaraに英語で話しかけ、この教会の歴史をたずねよう。", flavor_en: "Curious about the old church? Ask Clara its story!" },

  // --- ギルドの冒険者たち ---
  { type: "talk", npcId: "adv_rex",    goal_en: "ask the veteran how he stays so strong", goal_ja: "強さの秘訣を聞く", title_ja: "強さの秘訣を聞く", desc_ja: "冒険者Rexに英語で話しかけ、どうしてそんなに強いのか秘訣を聞こう。", flavor_en: "Want to get stronger? Ask Rex his secret!" },
  { type: "talk", npcId: "adv_rex",    goal_en: "ask the veteran for advice before a big boss battle", goal_ja: "ボス戦前の心得を聞く", title_ja: "ボス戦の心得を聞く", desc_ja: "冒険者Rexに英語で話しかけ、強敵と戦う前の心得を聞こう。", flavor_en: "Big fight coming? Ask Rex how to prepare!" },
  { type: "talk", npcId: "adv_mina",   goal_en: "ask the mage what magic and studying English have in common", goal_ja: "魔法と英語学習の共通点を聞く", title_ja: "魔法と英語の共通点を聞く", desc_ja: "魔法使いMinaに英語で話しかけ、魔法と英語の勉強に共通することを聞こう。", flavor_en: "Mina has clever ideas. Ask how magic is like learning!" },
  { type: "talk", npcId: "adv_mina",   goal_en: "ask the mage what she is reading right now", goal_ja: "今読んでいる本を聞く", title_ja: "今読んでる本を聞く", desc_ja: "魔法使いMinaに英語で話しかけ、今どんな本を読んでいるか聞こう。", flavor_en: "Mina always has a book. Ask what she's reading!" },
  { type: "talk", npcId: "adv_pip",    goal_en: "teach the rookie one English word and what it means", goal_ja: "新人に英単語を一つ教える", title_ja: "新人に単語を教える", desc_ja: "新人冒険者Pipに英語で話しかけ、英単語を一つ、意味つきで教えてあげよう。", flavor_en: "Pip wants to learn. Teach him a new word!" },
  { type: "talk", npcId: "adv_pip",    goal_en: "ask the rookie about his dream as an adventurer", goal_ja: "新人の夢を聞く", title_ja: "新人の夢を聞く", desc_ja: "新人冒険者Pipに英語で話しかけ、冒険者としての夢を聞いてみよう。", flavor_en: "Pip has big dreams. Ask him about them!" },

  // --- 学校・鍛冶屋・吟遊詩人・宿屋 ---
  { type: "talk", npcId: "school",     goal_en: "ask the teacher to check your pronunciation of a word", goal_ja: "発音をチェックしてもらう", title_ja: "発音を見てもらう", desc_ja: "学校のEdwinに英語で話しかけ、ある単語の発音をチェックしてもらおう。", flavor_en: "Edwin has a good ear. Ask him to check your accent!" },
  { type: "talk", npcId: "school",     goal_en: "tell the teacher what you did last weekend", goal_ja: "週末にしたことを話す", title_ja: "週末のことを話す", desc_ja: "学校のEdwinに英語で話しかけ、先週末にしたことを話そう。", flavor_en: "Edwin loves to listen. Tell him about your weekend!" },
  { type: "talk", npcId: "smith",      goal_en: "ask the blacksmith what materials he needs to forge a sword", goal_ja: "剣づくりに必要な素材を聞く", title_ja: "剣の材料を聞く", desc_ja: "鍛冶屋のBorinに英語で話しかけ、剣を打つのに必要な素材を聞こう。", flavor_en: "Curious how swords are made? Ask Borin what he needs!" },
  { type: "talk", npcId: "smith",      goal_en: "ask the blacksmith how he became a smith", goal_ja: "鍛冶屋になった経緯を聞く", title_ja: "鍛冶屋の来歴を聞く", desc_ja: "鍛冶屋のBorinに英語で話しかけ、どうして鍛冶屋になったのか聞こう。", flavor_en: "Borin has history. Ask how he took up the hammer!" },
  { type: "talk", npcId: "bard",       goal_en: "ask the bard to make up a short song about you", goal_ja: "自分の歌を作ってもらう", title_ja: "自分の歌を作ってもらう", desc_ja: "吟遊詩人Lyraに英語で話しかけ、自分についての短い歌を作ってもらおう。", flavor_en: "Lyra improvises! Ask her to sing a song about you!" },
  { type: "talk", npcId: "bard",       goal_en: "ask the bard where she has traveled", goal_ja: "旅した場所を聞く", title_ja: "旅した場所を聞く", desc_ja: "吟遊詩人Lyraに英語で話しかけ、これまで旅した場所を聞いてみよう。", flavor_en: "Lyra's been everywhere. Ask about her travels!" },
  { type: "talk", npcId: "innkeeper",  goal_en: "ask the innkeeper to wake you up early tomorrow morning", goal_ja: "明日の早起きを頼む", title_ja: "早起きを頼む", desc_ja: "宿屋のMarianに英語で話しかけ、明日の朝早く起こしてもらうよう頼もう。", flavor_en: "Early start tomorrow? Ask Marian for a wake-up!" },
  { type: "talk", npcId: "innkeeper",  goal_en: "ask the innkeeper what the best food in town is", goal_ja: "町の一番の料理を聞く", title_ja: "町の名物を聞く", desc_ja: "宿屋のMarianに英語で話しかけ、この町で一番おいしい料理を聞こう。", flavor_en: "Marian knows the local flavors. Ask what's best!" },

  // --- 新しい店・市場 ---
  { type: "talk", npcId: "realestate", goal_en: "ask the agent whether it's better to buy or rent a home", goal_ja: "購入と賃貸どちらがいいか聞く", title_ja: "買うか借りるか相談する", desc_ja: "不動産屋のEstelleに英語で話しかけ、家は買うのと借りるのどちらがいいか相談しよう。", flavor_en: "Buy or rent? Ask Estelle which suits you!" },
  { type: "talk", npcId: "realestate", goal_en: "describe your ideal garden to the agent", goal_ja: "理想の庭を伝える", title_ja: "理想の庭を伝える", desc_ja: "不動産屋のEstelleに英語で話しかけ、理想の庭がどんなものか説明しよう。", flavor_en: "Dreaming of a garden? Describe it to Estelle!" },
  { type: "talk", npcId: "appliance",  goal_en: "ask Den how to keep food fresh in the refrigerator", goal_ja: "冷蔵庫で食材を長持ちさせる方法を聞く", title_ja: "冷蔵庫の使いこなしを聞く", desc_ja: "家電屋のDenに英語で話しかけ、冷蔵庫で食材を長持ちさせるコツを聞こう。", flavor_en: "Den knows fridges. Ask how to keep food fresh!" },
  { type: "talk", npcId: "appliance",  goal_en: "ask Den which appliance is the most popular", goal_ja: "一番人気の家電を聞く", title_ja: "人気の家電を聞く", desc_ja: "家電屋のDenに英語で話しかけ、一番人気の家電を聞こう。", flavor_en: "Den loves to chat shop. Ask what's selling best!" },
  { type: "talk", npcId: "florist",    goal_en: "ask the florist to make a bouquet within your budget", goal_ja: "予算内で花束を頼む", title_ja: "予算内で花束を頼む", desc_ja: "花屋のLilyに英語で話しかけ、予算を伝えて花束を作ってもらおう。", flavor_en: "On a budget? Ask Lily for a bouquet to fit it!" },
  { type: "talk", npcId: "florist",    goal_en: "ask the florist how to take care of cut flowers at home", goal_ja: "家での花の世話を聞く", title_ja: "花の世話を聞く", desc_ja: "花屋のLilyに英語で話しかけ、切り花を家で長持ちさせる世話の仕方を聞こう。", flavor_en: "Want blooms to last? Ask Lily how to care for them!" },
  { type: "talk", npcId: "salon",      goal_en: "ask the stylist about her beloved pet cat", goal_ja: "飼い猫について聞く", title_ja: "飼い猫について聞く", desc_ja: "美容院のCocoに英語で話しかけ、彼女の飼い猫について聞いてみよう。", flavor_en: "Coco adores her cat. Ask her all about it!" },
  { type: "talk", npcId: "salon",      goal_en: "ask the stylist to suggest a new hairstyle for a fresh start", goal_ja: "心機一転の髪型を提案してもらう", title_ja: "新しい髪型を提案してもらう", desc_ja: "美容院のCocoに英語で話しかけ、心機一転の新しい髪型を提案してもらおう。", flavor_en: "Time for a change? Ask Coco for a new look!" },
  { type: "talk", npcId: "fish",       goal_en: "ask the fishmonger which fish is best for a beginner cook", goal_ja: "料理初心者向けの魚を聞く", title_ja: "初心者向けの魚を聞く", desc_ja: "魚屋のFinnに英語で話しかけ、料理初心者でも扱いやすい魚を聞こう。", flavor_en: "New to cooking fish? Ask Finn what's easy!" },
  { type: "talk", npcId: "fish",       goal_en: "ask the fishmonger where the fish comes from", goal_ja: "魚の産地を聞く", title_ja: "魚の産地を聞く", desc_ja: "魚屋のFinnに英語で話しかけ、その魚がどこで獲れたのか聞こう。", flavor_en: "Finn knows his waters. Ask where the catch is from!" },
  { type: "talk", npcId: "green",      goal_en: "ask the greengrocer to recommend vegetables for a salad", goal_ja: "サラダ向けの野菜を相談する", title_ja: "サラダの野菜を相談する", desc_ja: "八百屋のVeraに英語で話しかけ、サラダに合う野菜を相談しよう。", flavor_en: "Making a salad? Ask Vera what to toss in!" },
  { type: "talk", npcId: "green",      goal_en: "ask the greengrocer which fruit is sweetest right now", goal_ja: "今一番甘い果物を聞く", title_ja: "甘い果物を聞く", desc_ja: "八百屋のVeraに英語で話しかけ、今一番甘い果物を聞こう。", flavor_en: "Sweet tooth? Ask Vera which fruit is best now!" },
  { type: "talk", npcId: "meat",       goal_en: "ask the butcher how much meat you need for four people", goal_ja: "4人分の肉の量を聞く", title_ja: "肉の量を相談する", desc_ja: "肉屋のOttoに英語で話しかけ、4人分に必要な肉の量を聞こう。", flavor_en: "Cooking for a group? Ask Otto how much to buy!" },
  { type: "talk", npcId: "meat",       goal_en: "ask the butcher about the best cut of meat for a stew", goal_ja: "煮込みに合う部位を聞く", title_ja: "煮込みの肉を聞く", desc_ja: "肉屋のOttoに英語で話しかけ、煮込み料理に合う肉の部位を聞こう。", flavor_en: "Making a stew? Ask Otto for the right cut!" },
  { type: "talk", npcId: "grocery",    goal_en: "ask the grocer to recommend a snack", goal_ja: "おやつのおすすめを聞く", title_ja: "おやつを相談する", desc_ja: "食料品店のMarcoに英語で話しかけ、おすすめのおやつを聞こう。", flavor_en: "Peckish? Ask Marco for a tasty snack!" },
  { type: "talk", npcId: "grocery",    goal_en: "ask the grocer whether he has run out of anything today", goal_ja: "今日売り切れた物を聞く", title_ja: "売り切れを聞く", desc_ja: "食料品店のMarcoに英語で話しかけ、今日売り切れた品があるか聞こう。", flavor_en: "Marco restocks daily. Ask what sold out today!" },

  // --- 受付・武器屋・素材屋 ---
  { type: "talk", npcId: "guild_receptionist", goal_en: "ask the receptionist if there is any news about the Demon King", goal_ja: "魔王の情報をたずねる", title_ja: "魔王の情報を聞く", desc_ja: "ギルド受付のFiaに英語で話しかけ、魔王に関する最新の情報を聞こう。", flavor_en: "Fia hears everything. Ask about the Demon King!" },
  { type: "talk", npcId: "guild_receptionist", goal_en: "thank the receptionist for all her help", goal_ja: "受付に感謝を伝える", title_ja: "受付に感謝する", desc_ja: "ギルド受付のFiaに英語で話しかけ、いつも助けてくれることに感謝を伝えよう。", flavor_en: "Fia works hard for adventurers. Say thank you!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper if he can make a custom weapon for you", goal_ja: "特注の武器を頼む", title_ja: "特注の武器を頼む", desc_ja: "武器屋のDunnに英語で話しかけ、自分だけの特注武器を作れるか頼もう。", flavor_en: "Want something unique? Ask Dunn for a custom blade!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper the difference between a sword and an axe", goal_ja: "剣と斧の違いを聞く", title_ja: "剣と斧の違いを聞く", desc_ja: "武器屋のDunnに英語で話しかけ、剣と斧の違いや使い分けを聞こう。", flavor_en: "Sword or axe? Ask Dunn which fits your style!" },
  { type: "talk", npcId: "weaponshop", goal_en: "ask the shopkeeper to recommend armor for a tough boss fight", goal_ja: "ボス戦向けの防具を相談する", title_ja: "ボス用の防具を相談する", desc_ja: "武器屋のDunnに英語で話しかけ、強敵との戦いに向いた防具を相談しよう。", flavor_en: "Facing a boss? Ask Dunn what armor to wear!" },
  { type: "talk", npcId: "matshop",    goal_en: "ask the trader if he pays more gold for rare materials", goal_ja: "レア素材を高く買うか聞く", title_ja: "レア素材の値を聞く", desc_ja: "素材屋のGilに英語で話しかけ、珍しい素材は高く買ってくれるのか聞こう。", flavor_en: "Got something rare? Ask Gil if he pays extra!" },
  { type: "talk", npcId: "matshop",    goal_en: "ask the trader what he does with all the materials he buys", goal_ja: "買った素材の使い道を聞く", title_ja: "素材の使い道を聞く", desc_ja: "素材屋のGilに英語で話しかけ、買い取った素材を何に使うのか聞こう。", flavor_en: "Ever wonder where it all goes? Ask Gil!" },
  { type: "talk", npcId: "bard",       goal_en: "ask the bard to recommend a song for a celebration", goal_ja: "お祝いにぴったりの歌を聞く", title_ja: "お祝いの歌を聞く", desc_ja: "吟遊詩人Lyraに英語で話しかけ、お祝いの席にぴったりの歌をおすすめしてもらおう。", flavor_en: "Something to celebrate? Ask Lyra for the perfect song!" },
];
