// タワー専用の熟語(イディオム)データ。各難易度200個。
// 形式は words.js と同じ: { en:熟語, ja:意味, wrong:[3つの誤答] }
const TOWER_WORD_DATA = {
  500: [
    { en: "get up",        ja: "起きる",         wrong: ["寝る", "座る", "歩く"] },
    { en: "wake up",       ja: "目を覚ます",     wrong: ["眠る", "横になる", "夢を見る"] },
    { en: "stand up",      ja: "立ち上がる",     wrong: ["座る", "寝る", "しゃがむ"] },
    { en: "sit down",      ja: "座る",           wrong: ["立つ", "寝る", "走る"] },
    { en: "lie down",      ja: "横になる",       wrong: ["立つ", "座る", "跳ぶ"] },
    { en: "look at",       ja: "〜を見る",       wrong: ["〜を聞く", "〜を探す", "〜に話す"] },
    { en: "look for",      ja: "〜を探す",       wrong: ["〜を見つける", "〜を見る", "〜を待つ"] },
    { en: "look up",       ja: "見上げる",       wrong: ["見下ろす", "振り返る", "目を閉じる"] },
    { en: "look down",     ja: "見下ろす",       wrong: ["見上げる", "振り向く", "前を見る"] },
    { en: "listen to",     ja: "〜を聞く",       wrong: ["〜を見る", "〜に話す", "〜を読む"] },
    { en: "wait for",      ja: "〜を待つ",       wrong: ["〜を探す", "〜に会う", "〜を呼ぶ"] },
    { en: "look after",    ja: "〜の世話をする", wrong: ["〜を無視する", "〜を探す", "〜を追う"] },
    { en: "take care of",  ja: "〜の世話をする", wrong: ["〜を壊す", "〜を売る", "〜を捨てる"] },
    { en: "get on",        ja: "〜に乗る",       wrong: ["〜を降りる", "〜を押す", "〜を運ぶ"] },
    { en: "get off",       ja: "〜を降りる",     wrong: ["〜に乗る", "〜を運ぶ", "〜を押す"] },
    { en: "get in",        ja: "(車に)乗り込む", wrong: ["降りる", "出る", "押す"] },
    { en: "get out",       ja: "出る",           wrong: ["入る", "乗る", "座る"] },
    { en: "put on",        ja: "〜を着る",       wrong: ["〜を脱ぐ", "〜を洗う", "〜をたたむ"] },
    { en: "take off",      ja: "〜を脱ぐ",       wrong: ["〜を着る", "〜を洗う", "〜を干す"] },
    { en: "turn on",       ja: "(電気を)つける", wrong: ["消す", "壊す", "直す"] },
    { en: "turn off",      ja: "(電気を)消す",   wrong: ["つける", "回す", "押す"] },
    { en: "turn up",       ja: "音量を上げる",   wrong: ["下げる", "消す", "止める"] },
    { en: "turn down",     ja: "音量を下げる",   wrong: ["上げる", "つける", "回す"] },
    { en: "come in",       ja: "入る",           wrong: ["出る", "戻る", "座る"] },
    { en: "come back",     ja: "戻ってくる",     wrong: ["出かける", "去る", "進む"] },
    { en: "come out",      ja: "出てくる",       wrong: ["入る", "隠れる", "戻る"] },
    { en: "go out",        ja: "外出する",       wrong: ["帰る", "入る", "残る"] },
    { en: "go back",       ja: "帰る",           wrong: ["進む", "出かける", "残る"] },
    { en: "go away",       ja: "立ち去る",       wrong: ["近づく", "戻る", "留まる"] },
    { en: "go on",         ja: "続ける",         wrong: ["やめる", "止まる", "休む"] },
    { en: "run away",      ja: "逃げる",         wrong: ["追う", "立ち向かう", "留まる"] },
    { en: "give up",       ja: "あきらめる",     wrong: ["続ける", "挑戦する", "始める"] },
    { en: "pick up",       ja: "拾う",           wrong: ["落とす", "投げる", "置く"] },
    { en: "put down",      ja: "下に置く",       wrong: ["持ち上げる", "投げる", "運ぶ"] },
    { en: "throw away",    ja: "捨てる",         wrong: ["拾う", "集める", "保つ"] },
    { en: "pick out",      ja: "選び出す",       wrong: ["捨てる", "隠す", "混ぜる"] },
    { en: "take out",      ja: "取り出す",       wrong: ["しまう", "入れる", "隠す"] },
    { en: "put away",      ja: "片づける",       wrong: ["散らかす", "出す", "壊す"] },
    { en: "put back",      ja: "元に戻す",       wrong: ["取り出す", "捨てる", "動かす"] },
    { en: "hurry up",      ja: "急ぐ",           wrong: ["ゆっくりする", "休む", "待つ"] },
    { en: "calm down",     ja: "落ち着く",       wrong: ["興奮する", "怒る", "急ぐ"] },
    { en: "cheer up",      ja: "元気を出す",     wrong: ["落ち込む", "泣く", "怒る"] },
    { en: "grow up",       ja: "成長する",       wrong: ["縮む", "老ける", "生まれる"] },
    { en: "show up",       ja: "現れる",         wrong: ["消える", "隠れる", "去る"] },
    { en: "hold on",       ja: "(切らずに)待つ", wrong: ["電話を切る", "話す", "急ぐ"] },
    { en: "hang up",       ja: "電話を切る",     wrong: ["かける", "待つ", "話す"] },
    { en: "hang on",       ja: "しっかりつかまる", wrong: ["手を放す", "落ちる", "休む"] },
    { en: "find out",      ja: "見つけ出す",     wrong: ["隠す", "失う", "忘れる"] },
    { en: "work out",      ja: "運動する",       wrong: ["休む", "食べる", "眠る"] },
    { en: "eat out",       ja: "外食する",       wrong: ["自炊する", "断食する", "料理する"] },
    { en: "get back",      ja: "戻る",           wrong: ["進む", "出かける", "残る"] },
    { en: "move on",       ja: "先へ進む",       wrong: ["立ち止まる", "戻る", "休む"] },
    { en: "slow down",     ja: "速度を落とす",   wrong: ["加速する", "止まる", "進む"] },
    { en: "speed up",      ja: "加速する",       wrong: ["減速する", "止まる", "休む"] },
    { en: "ask for",       ja: "〜を求める",     wrong: ["〜を断る", "〜を与える", "〜を返す"] },
    { en: "care for",      ja: "〜を大切にする", wrong: ["〜を嫌う", "〜を捨てる", "〜を壊す"] },
    { en: "depend on",     ja: "〜に頼る",       wrong: ["〜を助ける", "〜を疑う", "〜を避ける"] },
    { en: "belong to",     ja: "〜に属する",     wrong: ["〜を離れる", "〜を訪れる", "〜を売る"] },
    { en: "stay up",       ja: "夜更かしする",   wrong: ["早寝する", "昼寝する", "起きる"] },
    { en: "sleep in",      ja: "朝寝坊する",     wrong: ["早起きする", "徹夜する", "昼寝する"] },
    { en: "break down",    ja: "故障する",       wrong: ["直る", "動く", "完成する"] },
    { en: "break up",      ja: "別れる",         wrong: ["仲直りする", "出会う", "結婚する"] },
    { en: "make up",       ja: "仲直りする",     wrong: ["けんかする", "別れる", "謝る"] },
    { en: "set up",        ja: "設置する",       wrong: ["片づける", "壊す", "倒す"] },
    { en: "clean up",      ja: "片づける",       wrong: ["散らかす", "汚す", "壊す"] },
    { en: "dress up",      ja: "着飾る",         wrong: ["着替える", "脱ぐ", "普段着でいる"] },
    { en: "line up",       ja: "並ぶ",           wrong: ["散らばる", "座る", "前に出る"] },
    { en: "stand by",      ja: "待機する",       wrong: ["立ち去る", "動く", "逃げる"] },
    { en: "come over",     ja: "遊びに来る",     wrong: ["帰る", "通り過ぎる", "断る"] },
    { en: "drop by",       ja: "立ち寄る",       wrong: ["通り過ぎる", "引っ越す", "去る"] },
    { en: "drop off",      ja: "(車から)降ろす", wrong: ["乗せる", "拾う", "運ぶ"] },
    { en: "fill in",       ja: "記入する",       wrong: ["消す", "空ける", "破る"] },
    { en: "fill out",      ja: "(用紙に)記入する", wrong: ["提出する", "破る", "折る"] },
    { en: "hand in",       ja: "提出する",       wrong: ["受け取る", "返す", "破る"] },
    { en: "hand out",      ja: "配る",           wrong: ["集める", "隠す", "捨てる"] },
    { en: "give back",     ja: "返す",           wrong: ["借りる", "奪う", "もらう"] },
    { en: "take back",     ja: "取り返す",       wrong: ["与える", "捨てる", "貸す"] },
    { en: "try on",        ja: "試着する",       wrong: ["脱ぐ", "洗う", "買う"] },
    { en: "try out",       ja: "試してみる",     wrong: ["あきらめる", "壊す", "隠す"] },
    { en: "put off",       ja: "延期する",       wrong: ["早める", "中止する", "始める"] },
    { en: "call back",     ja: "電話をかけ直す", wrong: ["電話を切る", "無視する", "出る"] },
    { en: "call off",      ja: "中止する",       wrong: ["開始する", "続ける", "延期する"] },
    { en: "turn around",   ja: "振り返る",       wrong: ["まっすぐ進む", "止まる", "座る"] },
    { en: "walk around",   ja: "歩き回る",       wrong: ["走る", "立ち止まる", "座る"] },
    { en: "get together",  ja: "集まる",         wrong: ["別れる", "散る", "逃げる"] },
    { en: "hang out",      ja: "ぶらぶらする",   wrong: ["急ぐ", "働く", "勉強する"] },
    { en: "come along",    ja: "一緒に来る",     wrong: ["残る", "断る", "先に行く"] },
    { en: "go ahead",      ja: "先に行く",       wrong: ["戻る", "止まる", "待つ"] },
    { en: "keep on",       ja: "続ける",         wrong: ["やめる", "止まる", "休む"] },
    { en: "carry on",      ja: "続ける",         wrong: ["中断する", "やめる", "休む"] },
    { en: "hold up",       ja: "持ち上げる",     wrong: ["落とす", "下ろす", "押す"] },
    { en: "set off",       ja: "出発する",       wrong: ["到着する", "止まる", "戻る"] },
    { en: "take place",    ja: "行われる",       wrong: ["中止になる", "延期する", "失敗する"] },
    { en: "look around",   ja: "見回す",         wrong: ["一点を見る", "目を閉じる", "下を向く"] },
    { en: "watch out",     ja: "気をつける",     wrong: ["油断する", "無視する", "休む"] },
    { en: "be afraid of",  ja: "〜を怖がる",     wrong: ["〜を好む", "〜を信じる", "〜を求める"] },
    { en: "be good at",    ja: "〜が得意だ",     wrong: ["〜が苦手だ", "〜を嫌う", "〜を避ける"] },
    { en: "be proud of",   ja: "〜を誇りに思う", wrong: ["〜を恥じる", "〜を疑う", "〜を嫌う"] },
    { en: "be interested in", ja: "〜に興味がある", wrong: ["〜に飽きる", "〜を嫌う", "〜を恐れる"] },
    { en: "be full of",    ja: "〜でいっぱいだ", wrong: ["〜が空だ", "〜が足りない", "〜を欠く"] },
    { en: "be late for",   ja: "〜に遅れる",     wrong: ["〜に間に合う", "〜を休む", "〜を早める"] },
    { en: "be ready for",  ja: "〜の準備ができている", wrong: ["〜に遅れる", "〜を忘れる", "〜を断る"] },
    { en: "be famous for", ja: "〜で有名だ",     wrong: ["〜で無名だ", "〜を隠す", "〜を恥じる"] },
    { en: "be different from", ja: "〜と違う",   wrong: ["〜と同じだ", "〜に似る", "〜と等しい"] },
    { en: "be kind to",    ja: "〜に親切だ",     wrong: ["〜に冷たい", "〜を無視する", "〜を怒る"] },
    { en: "be sure of",    ja: "〜を確信する",   wrong: ["〜を疑う", "〜を忘れる", "〜を恐れる"] },
    { en: "a lot of",      ja: "たくさんの",     wrong: ["少しの", "全くない", "半分の"] },
    { en: "a few",         ja: "少数の",         wrong: ["多数の", "ゼロの", "全部の"] },
    { en: "a little",      ja: "少量の",         wrong: ["多量の", "ゼロの", "全部の"] },
    { en: "plenty of",     ja: "たっぷりの",     wrong: ["わずかの", "不足の", "ゼロの"] },
    { en: "kind of",       ja: "いくらか",       wrong: ["全く", "完全に", "決して"] },
    { en: "a kind of",     ja: "一種の",         wrong: ["全種類の", "反対の", "半分の"] },
    { en: "for example",   ja: "例えば",         wrong: ["結局", "しかし", "だから"] },
    { en: "for a while",   ja: "しばらくの間",   wrong: ["永遠に", "一瞬で", "いつも"] },
    { en: "at first",      ja: "最初は",         wrong: ["最後に", "いつも", "決して"] },
    { en: "at last",       ja: "ついに",         wrong: ["最初に", "途中で", "すぐに"] },
    { en: "at once",       ja: "すぐに",         wrong: ["後で", "決して", "たまに"] },
    { en: "right now",     ja: "今すぐ",         wrong: ["後で", "昨日", "いつか"] },
    { en: "right away",    ja: "すぐに",         wrong: ["ゆっくり", "後で", "決して"] },
    { en: "by the way",    ja: "ところで",       wrong: ["結局", "だから", "しかし"] },
    { en: "of course",     ja: "もちろん",       wrong: ["まさか", "たぶん", "決して"] },
    { en: "in fact",       ja: "実際は",         wrong: ["うわべは", "たぶん", "決して"] },
    { en: "in time",       ja: "間に合って",     wrong: ["遅れて", "早すぎて", "いつも"] },
    { en: "on time",       ja: "時間どおりに",   wrong: ["遅れて", "早めに", "いつも"] },
    { en: "these days",    ja: "最近は",         wrong: ["昔は", "いつか", "永遠に"] },
    { en: "all day",       ja: "一日中",         wrong: ["一瞬", "夜だけ", "たまに"] },
    { en: "all the time",  ja: "いつも",         wrong: ["たまに", "決して", "昨日"] },
    { en: "every day",     ja: "毎日",           wrong: ["たまに", "昨日", "一度"] },
    { en: "once a week",   ja: "週に一度",       wrong: ["毎日", "月に一度", "年に一度"] },
    { en: "more and more", ja: "ますます",       wrong: ["だんだん少なく", "急に", "全く"] },
    { en: "again and again", ja: "何度も",       wrong: ["一度だけ", "決して", "たまに"] },
    { en: "each other",    ja: "お互いに",       wrong: ["一人で", "別々に", "順番に"] },
    { en: "one by one",    ja: "一つずつ",       wrong: ["全部いっぺんに", "半分ずつ", "適当に"] },
    { en: "over there",    ja: "あそこに",       wrong: ["ここに", "どこにも", "内側に"] },
    { en: "far away",      ja: "遠くに",         wrong: ["近くに", "ここに", "内側に"] },
    { en: "next to",       ja: "〜の隣に",       wrong: ["〜の遠くに", "〜の上に", "〜の中に"] },
    { en: "in front of",   ja: "〜の前に",       wrong: ["〜の後ろに", "〜の中に", "〜の上に"] },
    { en: "instead of",    ja: "〜の代わりに",   wrong: ["〜と一緒に", "〜のために", "〜のように"] },
    { en: "because of",    ja: "〜のために",     wrong: ["〜にもかかわらず", "〜の代わりに", "〜のように"] },
    { en: "thanks to",     ja: "〜のおかげで",   wrong: ["〜のせいで", "〜に反して", "〜の代わりに"] },
    { en: "such as",       ja: "〜のような",     wrong: ["〜を除いて", "〜と違って", "〜の代わりに"] },
    { en: "as well",       ja: "〜も(また)",     wrong: ["〜だけ", "〜ではなく", "〜の代わりに"] },
    { en: "as soon as",    ja: "〜するとすぐに", wrong: ["〜する前に", "〜した後で", "〜する間"] },
    { en: "as long as",    ja: "〜する限り",     wrong: ["〜する前に", "〜なしで", "〜の代わりに"] },
    { en: "more than",     ja: "〜より多く",     wrong: ["〜より少なく", "〜と同じ", "〜まで"] },
    { en: "less than",     ja: "〜より少なく",   wrong: ["〜より多く", "〜と等しい", "〜以上"] },
    { en: "at home",       ja: "家で",           wrong: ["学校で", "外で", "職場で"] },
    { en: "at school",     ja: "学校で",         wrong: ["家で", "職場で", "公園で"] },
    { en: "at night",      ja: "夜に",           wrong: ["朝に", "昼に", "夕方に"] },
    { en: "in the morning", ja: "朝に",          wrong: ["夜に", "昼に", "夕方に"] },
    { en: "on foot",       ja: "徒歩で",         wrong: ["車で", "電車で", "自転車で"] },
    { en: "by bus",        ja: "バスで",         wrong: ["徒歩で", "電車で", "船で"] },
    { en: "by train",      ja: "電車で",         wrong: ["バスで", "徒歩で", "飛行機で"] },
    { en: "by car",        ja: "車で",           wrong: ["徒歩で", "電車で", "船で"] },
    { en: "get ready",     ja: "準備する",       wrong: ["片づける", "休む", "終える"] },
    { en: "get well",      ja: "よくなる",       wrong: ["悪化する", "疲れる", "倒れる"] },
    { en: "get angry",     ja: "怒る",           wrong: ["喜ぶ", "落ち着く", "笑う"] },
    { en: "get lost",      ja: "道に迷う",       wrong: ["道を見つける", "到着する", "戻る"] },
    { en: "get married",   ja: "結婚する",       wrong: ["離婚する", "別れる", "出会う"] },
    { en: "get tired",     ja: "疲れる",         wrong: ["元気になる", "休む", "眠る"] },
    { en: "get hungry",    ja: "おなかがすく",   wrong: ["満腹になる", "のどが渇く", "疲れる"] },
    { en: "fall down",     ja: "転ぶ",           wrong: ["立ち上がる", "登る", "跳ぶ"] },
    { en: "fall asleep",   ja: "眠りに落ちる",   wrong: ["目を覚ます", "起きる", "夢を見る"] },
    { en: "take a walk",   ja: "散歩する",       wrong: ["走る", "休む", "眠る"] },
    { en: "take a rest",   ja: "休憩する",       wrong: ["働く", "走る", "急ぐ"] },
    { en: "take a bath",   ja: "入浴する",       wrong: ["泳ぐ", "洗濯する", "掃除する"] },
    { en: "take a picture", ja: "写真を撮る",    wrong: ["絵を描く", "撮られる", "消す"] },
    { en: "take a trip",   ja: "旅行する",       wrong: ["出勤する", "帰宅する", "残る"] },
    { en: "make friends",  ja: "友達になる",     wrong: ["けんかする", "別れる", "断る"] },
    { en: "make a noise",  ja: "物音を立てる",   wrong: ["静かにする", "黙る", "聞く"] },
    { en: "make a mistake", ja: "間違える",      wrong: ["正解する", "直す", "避ける"] },
    { en: "make money",    ja: "お金をかせぐ",   wrong: ["お金を使う", "お金を失う", "貯金する"] },
    { en: "do one's best", ja: "全力をつくす",   wrong: ["手を抜く", "あきらめる", "休む"] },
    { en: "do the dishes", ja: "皿を洗う",       wrong: ["料理する", "食べる", "片づける"] },
    { en: "have a cold",   ja: "風邪をひいている", wrong: ["元気だ", "熱がない", "治る"] },
    { en: "have fun",      ja: "楽しむ",         wrong: ["退屈する", "働く", "我慢する"] },
    { en: "have a good time", ja: "楽しい時を過ごす", wrong: ["退屈する", "失敗する", "急ぐ"] },
    { en: "have to",       ja: "〜しなければならない", wrong: ["〜してもよい", "〜できない", "〜したい"] },
    { en: "would like",    ja: "〜がほしい",     wrong: ["〜が嫌いだ", "〜を断る", "〜を返す"] },
    { en: "had better",    ja: "〜したほうがよい", wrong: ["〜してはいけない", "〜したい", "〜できる"] },
    { en: "used to",       ja: "以前は〜だった", wrong: ["これから〜する", "今〜している", "決して〜しない"] },
    { en: "be going to",   ja: "〜するつもりだ", wrong: ["〜したくない", "〜を終えた", "〜できない"] },
    { en: "be able to",    ja: "〜できる",       wrong: ["〜できない", "〜したい", "〜すべきだ"] },
    { en: "thank you for", ja: "〜をありがとう", wrong: ["〜を謝る", "〜を断る", "〜を頼む"] },
    { en: "how about",     ja: "〜はどうですか", wrong: ["なぜ〜か", "いつ〜か", "だれが〜か"] },
    { en: "here you are",  ja: "はい、どうぞ",   wrong: ["さようなら", "ごめんなさい", "ありがとう"] },
    { en: "no longer",     ja: "もはや〜ない",   wrong: ["まだ〜だ", "いつも〜だ", "さらに〜だ"] },
    { en: "not at all",    ja: "全く〜ない",     wrong: ["とても〜だ", "いくらか〜だ", "たいてい〜だ"] },
    { en: "so far",        ja: "今までのところ", wrong: ["これから", "決して", "すぐに"] },
    { en: "first of all",  ja: "まず第一に",     wrong: ["最後に", "ついでに", "例えば"] },
    { en: "after all",     ja: "結局",           wrong: ["最初に", "例えば", "そのうえ"] },
    { en: "as a result",   ja: "その結果",       wrong: ["その原因で", "例えば", "ところで"] },
    { en: "in other words", ja: "言い換えれば",  wrong: ["反対に", "例えば", "ところで"] },
    { en: "on the other hand", ja: "一方で",     wrong: ["同様に", "結局", "だから"] },
    { en: "all of a sudden", ja: "突然",         wrong: ["徐々に", "予定通り", "いつも"] },
    { en: "no problem",    ja: "問題ない",       wrong: ["大問題だ", "残念だ", "ありがとう"] },
    { en: "come true",     ja: "実現する",       wrong: ["消える", "失敗する", "始まる"] },
    { en: "take a break",  ja: "休憩を取る",     wrong: ["働き続ける", "急ぐ", "出発する"] },
    { en: "get on well",   ja: "うまくやっていく", wrong: ["仲が悪い", "失敗する", "別れる"] },
    { en: "in a hurry",    ja: "急いで",         wrong: ["のんびりと", "予定通りに", "いつも"] },
  ],
  700: [
    { en: "account for",   ja: "説明する",       wrong: ["無視する", "要約する", "隠す"] },
    { en: "bring about",   ja: "引き起こす",     wrong: ["防ぐ", "終わらせる", "遅らせる"] },
    { en: "carry out",     ja: "実行する",       wrong: ["中止する", "計画する", "延期する"] },
    { en: "come across",   ja: "(偶然)出会う",   wrong: ["避ける", "探す", "別れる"] },
    { en: "come up with",  ja: "思いつく",       wrong: ["忘れる", "拒否する", "真似る"] },
    { en: "deal with",     ja: "対処する",       wrong: ["無視する", "放置する", "悪化させる"] },
    { en: "figure out",    ja: "理解する",       wrong: ["混乱する", "見逃す", "忘れる"] },
    { en: "get over",      ja: "克服する",       wrong: ["あきらめる", "悪化させる", "引きずる"] },
    { en: "give in",       ja: "屈する",         wrong: ["抵抗する", "勝つ", "拒む"] },
    { en: "go over",       ja: "復習する",       wrong: ["飛ばす", "無視する", "忘れる"] },
    { en: "look forward to", ja: "〜を楽しみにする", wrong: ["〜を恐れる", "〜を後悔する", "〜を避ける"] },
    { en: "make up for",   ja: "埋め合わせる",   wrong: ["悪化させる", "放置する", "無視する"] },
    { en: "put up with",   ja: "我慢する",       wrong: ["抗議する", "逃げる", "楽しむ"] },
    { en: "run into",      ja: "(偶然)出会う",   wrong: ["避ける", "別れる", "探す"] },
    { en: "take after",    ja: "〜に似ている",   wrong: ["〜と違う", "〜を追う", "〜を世話する"] },
    { en: "take over",     ja: "引き継ぐ",       wrong: ["手放す", "放棄する", "始める"] },
    { en: "turn out",      ja: "結局〜となる",   wrong: ["計画する", "失敗する", "中止する"] },
    { en: "work on",       ja: "取り組む",       wrong: ["放棄する", "休む", "完成する"] },
    { en: "point out",     ja: "指摘する",       wrong: ["見逃す", "隠す", "無視する"] },
    { en: "set out",       ja: "出発する",       wrong: ["到着する", "留まる", "引き返す"] },
    { en: "bring up",      ja: "育てる",         wrong: ["見捨てる", "黙る", "壊す"] },
    { en: "call for",      ja: "必要とする",     wrong: ["拒否する", "中止する", "与える"] },
    { en: "count on",      ja: "頼る",           wrong: ["疑う", "避ける", "助ける"] },
    { en: "cut down",      ja: "削減する",       wrong: ["増やす", "維持する", "加える"] },
    { en: "end up",        ja: "結局〜になる",   wrong: ["始める", "計画する", "中断する"] },
    { en: "fall behind",   ja: "遅れる",         wrong: ["追いつく", "先んじる", "並ぶ"] },
    { en: "get rid of",    ja: "取り除く",       wrong: ["ためる", "増やす", "集める"] },
    { en: "hold back",     ja: "抑える",         wrong: ["解き放つ", "促す", "助長する"] },
    { en: "keep up with",  ja: "(遅れず)ついていく", wrong: ["遅れる", "先導する", "離れる"] },
    { en: "lay off",       ja: "解雇する",       wrong: ["雇う", "昇進させる", "採用する"] },
    { en: "leave out",     ja: "省く",           wrong: ["含める", "加える", "強調する"] },
    { en: "look into",     ja: "調査する",       wrong: ["無視する", "隠す", "放置する"] },
    { en: "make sense",    ja: "意味をなす",     wrong: ["矛盾する", "混乱させる", "失敗する"] },
    { en: "pass away",     ja: "亡くなる",       wrong: ["生まれる", "回復する", "通り過ぎる"] },
    { en: "put together",  ja: "組み立てる",     wrong: ["分解する", "壊す", "散らす"] },
    { en: "rule out",      ja: "除外する",       wrong: ["含める", "選ぶ", "認める"] },
    { en: "sort out",      ja: "整理する",       wrong: ["散らかす", "混ぜる", "壊す"] },
    { en: "stand for",     ja: "表す",           wrong: ["反対する", "隠す", "無視する"] },
    { en: "take up",       ja: "(趣味を)始める", wrong: ["やめる", "断る", "続ける"] },
    { en: "break out",     ja: "突発する",       wrong: ["終息する", "防ぐ", "収まる"] },
    { en: "bring back",    ja: "持ち帰る",       wrong: ["持ち去る", "捨てる", "隠す"] },
    { en: "call on",       ja: "訪問する",       wrong: ["無視する", "避ける", "断る"] },
    { en: "catch up",      ja: "追いつく",       wrong: ["遅れる", "先んじる", "離れる"] },
    { en: "check out",     ja: "確認する",       wrong: ["無視する", "隠す", "放置する"] },
    { en: "come about",    ja: "起こる",         wrong: ["防ぐ", "終わる", "消える"] },
    { en: "cut off",       ja: "切断する",       wrong: ["つなぐ", "続ける", "延ばす"] },
    { en: "do without",    ja: "〜なしで済ます", wrong: ["〜を必要とする", "〜を買う", "〜を使う"] },
    { en: "drop out",      ja: "中退する",       wrong: ["入学する", "卒業する", "続ける"] },
    { en: "fall apart",    ja: "ばらばらになる", wrong: ["まとまる", "完成する", "強くなる"] },
    { en: "get along with", ja: "〜と仲良くする", wrong: ["〜とけんかする", "〜を避ける", "〜を無視する"] },
    { en: "give away",     ja: "ただであげる",   wrong: ["売る", "借りる", "隠す"] },
    { en: "give off",      ja: "(においを)発する", wrong: ["吸収する", "隠す", "消す"] },
    { en: "go through",    ja: "経験する",       wrong: ["避ける", "飛ばす", "やめる"] },
    { en: "hand over",     ja: "引き渡す",       wrong: ["受け取る", "奪う", "隠す"] },
    { en: "hold on to",    ja: "〜を手放さない", wrong: ["〜を捨てる", "〜を売る", "〜を渡す"] },
    { en: "keep up",       ja: "維持する",       wrong: ["落とす", "やめる", "遅れる"] },
    { en: "let down",      ja: "失望させる",     wrong: ["励ます", "助ける", "喜ばせる"] },
    { en: "look up to",    ja: "〜を尊敬する",   wrong: ["〜を見下す", "〜を無視する", "〜を疑う"] },
    { en: "look down on",  ja: "〜を見下す",     wrong: ["〜を尊敬する", "〜を助ける", "〜を頼る"] },
    { en: "make out",      ja: "理解する",       wrong: ["見失う", "混乱する", "隠す"] },
    { en: "pass on",       ja: "伝える",         wrong: ["隠す", "失う", "止める"] },
    { en: "pay off",       ja: "報われる",       wrong: ["損する", "借りる", "失敗する"] },
    { en: "pull over",     ja: "(車を)わきに停める", wrong: ["加速する", "発進する", "追い越す"] },
    { en: "put aside",     ja: "取っておく",     wrong: ["使い果たす", "捨てる", "配る"] },
    { en: "result in",     ja: "〜という結果になる", wrong: ["〜が原因だ", "〜を防ぐ", "〜を始める"] },
    { en: "result from",   ja: "〜に起因する",   wrong: ["〜を引き起こす", "〜を防ぐ", "〜を終える"] },
    { en: "run out of",    ja: "〜を使い果たす", wrong: ["〜をためる", "〜が余る", "〜を補う"] },
    { en: "see off",       ja: "見送る",         wrong: ["出迎える", "追い払う", "招く"] },
    { en: "set aside",     ja: "取っておく",     wrong: ["使い切る", "捨てる", "配る"] },
    { en: "settle down",   ja: "落ち着く",       wrong: ["引っ越す", "動き回る", "興奮する"] },
    { en: "show off",      ja: "見せびらかす",   wrong: ["隠す", "謙遜する", "しまう"] },
    { en: "take in",       ja: "理解する",       wrong: ["見逃す", "正直に言う", "放す"] },
    { en: "tell apart",    ja: "見分ける",       wrong: ["混同する", "隠す", "まとめる"] },
    { en: "think over",    ja: "じっくり考える", wrong: ["即決する", "無視する", "忘れる"] },
    { en: "throw up",      ja: "吐く",           wrong: ["飲み込む", "食べる", "投げる"] },
    { en: "turn into",     ja: "〜に変わる",     wrong: ["〜のままだ", "〜に戻る", "〜を保つ"] },
    { en: "use up",        ja: "使い果たす",     wrong: ["ためる", "余らせる", "補充する"] },
    { en: "watch over",    ja: "見守る",         wrong: ["見捨てる", "無視する", "放置する"] },
    { en: "wear out",      ja: "すり減らす",     wrong: ["新調する", "直す", "磨く"] },
    { en: "break into",    ja: "押し入る",       wrong: ["立ち去る", "鍵をかける", "守る"] },
    { en: "come down with", ja: "(病気に)かかる", wrong: ["回復する", "予防する", "広める"] },
    { en: "cope with",     ja: "対処する",       wrong: ["放置する", "逃げる", "悪化させる"] },
    { en: "fit in",        ja: "溶け込む",       wrong: ["浮く", "対立する", "孤立する"] },
    { en: "get away",      ja: "逃げる",         wrong: ["捕まる", "留まる", "戻る"] },
    { en: "get by",        ja: "何とかやっていく", wrong: ["失敗する", "豊かに暮らす", "あきらめる"] },
    { en: "go after",      ja: "〜を追う",       wrong: ["〜から逃げる", "〜を待つ", "〜を見送る"] },
    { en: "go for",        ja: "〜を選ぶ",       wrong: ["〜を拒む", "〜を避ける", "〜を返す"] },
    { en: "hang around",   ja: "うろつく",       wrong: ["急いで去る", "座る", "働く"] },
    { en: "head for",      ja: "〜へ向かう",     wrong: ["〜から離れる", "〜を避ける", "〜に着く"] },
    { en: "hold off",      ja: "延期する",       wrong: ["早める", "屈する", "始める"] },
    { en: "lay out",       ja: "配置する",       wrong: ["片づける", "隠す", "混ぜる"] },
    { en: "let in",        ja: "中に入れる",     wrong: ["締め出す", "追い出す", "閉じ込める"] },
    { en: "live up to",    ja: "〜に応える",     wrong: ["〜を裏切る", "〜を下回る", "〜を無視する"] },
    { en: "look out",      ja: "注意する",       wrong: ["油断する", "見逃す", "無視する"] },
    { en: "make for",      ja: "〜へ向かう",     wrong: ["〜から離れる", "〜を避ける", "〜を作る"] },
    { en: "mix up",        ja: "混同する",       wrong: ["区別する", "整理する", "並べる"] },
    { en: "narrow down",   ja: "絞り込む",       wrong: ["広げる", "増やす", "散らす"] },
    { en: "own up",        ja: "白状する",       wrong: ["隠す", "否定する", "言い逃れる"] },
    { en: "pick on",       ja: "いじめる",       wrong: ["かばう", "ほめる", "助ける"] },
    { en: "put forward",   ja: "提案する",       wrong: ["撤回する", "却下する", "延期する"] },
    { en: "stick to",      ja: "〜を守り通す",   wrong: ["〜をやめる", "〜を変える", "〜を破る"] },
    { en: "take on",       ja: "引き受ける",     wrong: ["断る", "手放す", "放棄する"] },
    { en: "take to",       ja: "〜を好きになる", wrong: ["〜を嫌う", "〜を避ける", "〜を忘れる"] },
    { en: "throw out",     ja: "捨てる",         wrong: ["拾う", "招き入れる", "保管する"] },
    { en: "tie up",        ja: "縛る",           wrong: ["ほどく", "解放する", "自由にする"] },
    { en: "wind up",       ja: "結局〜になる",   wrong: ["始める", "計画する", "避ける"] },
    { en: "act up",        ja: "不調になる",     wrong: ["順調に動く", "落ち着く", "直る"] },
    { en: "add up",        ja: "計算が合う",     wrong: ["矛盾する", "引く", "割る"] },
    { en: "back up",       ja: "支援する",       wrong: ["妨害する", "削除する", "放棄する"] },
    { en: "blow up",       ja: "爆発する",       wrong: ["しぼむ", "消す", "固める"] },
    { en: "bring down",    ja: "倒す",           wrong: ["上げる", "支える", "建てる"] },
    { en: "build up",      ja: "築き上げる",     wrong: ["取り壊す", "減らす", "放棄する"] },
    { en: "burn out",      ja: "燃え尽きる",     wrong: ["元気になる", "点火する", "冷える"] },
    { en: "call up",       ja: "電話する",       wrong: ["電話を切る", "訪問する", "無視する"] },
    { en: "clear up",      ja: "(天気が)晴れる", wrong: ["曇る", "複雑にする", "汚す"] },
    { en: "come round",    ja: "意識を取り戻す", wrong: ["気を失う", "立ち去る", "眠る"] },
    { en: "cut in",        ja: "割り込む",       wrong: ["譲る", "並ぶ", "待つ"] },
    { en: "die out",       ja: "絶滅する",       wrong: ["繁栄する", "増える", "生まれる"] },
    { en: "dig up",        ja: "掘り出す",       wrong: ["埋める", "隠す", "捨てる"] },
    { en: "draw up",       ja: "作成する",       wrong: ["破棄する", "消す", "省く"] },
    { en: "fall through",  ja: "計画が頓挫する", wrong: ["成功する", "進む", "完成する"] },
    { en: "get across",    ja: "理解させる",     wrong: ["誤解させる", "隠す", "黙る"] },
    { en: "give out",      ja: "配る",           wrong: ["集める", "ためる", "受け取る"] },
    { en: "grow out of",   ja: "(服が)着られなくなる", wrong: ["似合う", "新調する", "縮む"] },
    { en: "hand down",     ja: "受け継がせる",   wrong: ["奪う", "捨てる", "借りる"] },
    { en: "hold out",      ja: "持ちこたえる",   wrong: ["屈する", "あきらめる", "崩れる"] },
    { en: "iron out",      ja: "(問題を)解決する", wrong: ["複雑にする", "放置する", "悪化させる"] },
    { en: "jot down",      ja: "書き留める",     wrong: ["消す", "暗記する", "破る"] },
    { en: "keep away",     ja: "近づけない",     wrong: ["招く", "触れる", "集める"] },
    { en: "knock down",    ja: "殴り倒す",       wrong: ["建てる", "起こす", "支える"] },
    { en: "lay down",      ja: "定める",         wrong: ["取り消す", "持ち上げる", "破る"] },
    { en: "let out",       ja: "漏らす",         wrong: ["閉じ込める", "隠す", "抑える"] },
    { en: "look over",     ja: "ざっと見る",     wrong: ["熟読する", "見逃す", "無視する"] },
    { en: "make off",      ja: "逃げる",         wrong: ["留まる", "近づく", "戻る"] },
    { en: "nod off",       ja: "うとうとする",   wrong: ["目を覚ます", "集中する", "立つ"] },
    { en: "opt for",       ja: "〜を選ぶ",       wrong: ["〜を拒む", "〜を避ける", "〜を返す"] },
    { en: "pass out",      ja: "気を失う",       wrong: ["意識を取り戻す", "合格する", "通り過ぎる"] },
    { en: "pile up",       ja: "積み重なる",     wrong: ["減る", "崩れる", "散る"] },
    { en: "play down",     ja: "軽視する",       wrong: ["強調する", "誇張する", "称える"] },
    { en: "plug in",       ja: "(電源に)差し込む", wrong: ["抜く", "切る", "消す"] },
    { en: "pull off",      ja: "成し遂げる",     wrong: ["失敗する", "あきらめる", "中断する"] },
    { en: "push for",      ja: "強く求める",     wrong: ["拒む", "譲る", "あきらめる"] },
    { en: "put through",   ja: "電話をつなぐ",   wrong: ["切る", "保留する", "拒む"] },
    { en: "read out",      ja: "読み上げる",     wrong: ["黙読する", "要約する", "省く"] },
    { en: "round up",      ja: "かき集める",     wrong: ["散らす", "逃がす", "減らす"] },
    { en: "scale back",    ja: "縮小する",       wrong: ["拡大する", "維持する", "加速する"] },
    { en: "send back",     ja: "送り返す",       wrong: ["受け取る", "届ける", "保管する"] },
    { en: "shut down",     ja: "閉鎖する",       wrong: ["起動する", "開く", "続ける"] },
    { en: "sign up",       ja: "申し込む",       wrong: ["取り消す", "辞退する", "断る"] },
    { en: "single out",    ja: "選び出す",       wrong: ["まとめる", "除外する", "隠す"] },
    { en: "step down",     ja: "辞任する",       wrong: ["就任する", "昇進する", "留任する"] },
    { en: "stir up",       ja: "かき立てる",     wrong: ["鎮める", "落ち着かせる", "冷ます"] },
    { en: "sum up",        ja: "要約する",       wrong: ["詳述する", "省く", "複雑にする"] },
    { en: "switch off",    ja: "電源を切る",     wrong: ["入れる", "回す", "押す"] },
    { en: "take down",     ja: "書き留める",     wrong: ["取り付ける", "暗記する", "組み立てる"] },
    { en: "tear down",     ja: "取り壊す",       wrong: ["建てる", "修理する", "支える"] },
    { en: "think up",      ja: "考え出す",       wrong: ["忘れる", "真似る", "放棄する"] },
    { en: "top up",        ja: "補充する",       wrong: ["使い切る", "空ける", "捨てる"] },
    { en: "track down",    ja: "突き止める",     wrong: ["見失う", "放置する", "隠す"] },
    { en: "trade in",      ja: "下取りに出す",   wrong: ["新品で買う", "廃棄する", "保管する"] },
    { en: "tune in",       ja: "(番組を)受信する", wrong: ["消す", "無視する", "切る"] },
    { en: "wait on",       ja: "給仕する",       wrong: ["命令する", "無視する", "放置する"] },
    { en: "ward off",      ja: "撃退する",       wrong: ["招く", "受け入れる", "屈する"] },
    { en: "weed out",      ja: "取り除く",       wrong: ["残す", "増やす", "育てる"] },
    { en: "weigh up",      ja: "比較検討する",   wrong: ["即断する", "無視する", "放棄する"] },
    { en: "wipe out",      ja: "全滅させる",     wrong: ["増やす", "救う", "守る"] },
    { en: "zoom in",       ja: "拡大する",       wrong: ["縮小する", "引く", "消す"] },
    { en: "abide by",      ja: "〜に従う",       wrong: ["〜に背く", "〜を疑う", "〜を変える"] },
    { en: "amount to",     ja: "〜に達する",     wrong: ["〜に満たない", "〜を下回る", "〜を超えない"] },
    { en: "bank on",       ja: "当てにする",     wrong: ["疑う", "避ける", "放棄する"] },
    { en: "boil down to",  ja: "要するに〜だ",   wrong: ["〜とは無関係だ", "〜を複雑にする", "〜を省く"] },
    { en: "brush up on",   ja: "学び直す",       wrong: ["忘れる", "放棄する", "飛ばす"] },
    { en: "catch on",      ja: "流行する",       wrong: ["すたれる", "混乱する", "消える"] },
    { en: "chip in",       ja: "お金を出し合う", wrong: ["独り占めする", "借りる", "断る"] },
    { en: "come by",       ja: "手に入れる",     wrong: ["失う", "捨てる", "断る"] },
    { en: "cut back on",   ja: "〜を減らす",     wrong: ["〜を増やす", "〜を保つ", "〜を加える"] },
    { en: "dawn on",       ja: "〜にわかり始める", wrong: ["〜を忘れる", "〜を隠す", "〜を疑う"] },
    { en: "do away with",  ja: "廃止する",       wrong: ["導入する", "維持する", "復活させる"] },
    { en: "dwell on",      ja: "〜をくよくよ考える", wrong: ["〜を忘れる", "〜を流す", "〜を急ぐ"] },
    { en: "face up to",    ja: "〜に立ち向かう", wrong: ["〜から逃げる", "〜を無視する", "〜を隠す"] },
    { en: "fall back on",  ja: "〜に頼る",       wrong: ["〜を捨てる", "〜を避ける", "〜を疑う"] },
    { en: "fill up",       ja: "満タンにする",   wrong: ["空にする", "減らす", "こぼす"] },
    { en: "get around",    ja: "動き回る",       wrong: ["立ち止まる", "直面する", "従う"] },
    { en: "go along with", ja: "〜に同調する",   wrong: ["〜に反対する", "〜を無視する", "〜を妨げる"] },
    { en: "hit upon",      ja: "思いつく",       wrong: ["忘れる", "見逃す", "拒む"] },
    { en: "keep to",       ja: "〜を守る",       wrong: ["〜を破る", "〜を変える", "〜をやめる"] },
    { en: "lash out",      ja: "激しく非難する", wrong: ["ほめる", "なだめる", "黙る"] },
    { en: "level off",     ja: "横ばいになる",   wrong: ["急上昇する", "急落する", "変動する"] },
    { en: "make up one's mind", ja: "決心する",  wrong: ["迷う", "先延ばしする", "撤回する"] },
    { en: "pin down",      ja: "特定する",       wrong: ["ぼかす", "見逃す", "放置する"] },
    { en: "stem from",     ja: "〜に由来する",   wrong: ["〜を引き起こす", "〜を防ぐ", "〜を終える"] },
    { en: "stumble upon",  ja: "偶然見つける",   wrong: ["探し回る", "見失う", "隠す"] },
    { en: "talk into",     ja: "説得して〜させる", wrong: ["思いとどまらせる", "黙らせる", "反対する"] },
    { en: "back down",     ja: "引き下がる",     wrong: ["押し通す", "前進する", "対立する"] },
    { en: "branch out",    ja: "事業を広げる",   wrong: ["縮小する", "撤退する", "集中する"] },
    { en: "phase out",     ja: "段階的に廃止する", wrong: ["導入する", "拡大する", "維持する"] },
    { en: "weigh in",      ja: "意見を述べる",   wrong: ["黙る", "棄権する", "退く"] },
    { en: "tone down",     ja: "和らげる",       wrong: ["強調する", "激化させる", "誇張する"] },
    { en: "drum up",       ja: "(支持を)かき集める", wrong: ["鎮める", "抑える", "減らす"] },
    { en: "shrug off",     ja: "軽く受け流す",   wrong: ["深刻に受け止める", "怒る", "悩む"] },
  ],
  900: [
    { en: "under the weather",     ja: "体調が悪い",       wrong: ["元気いっぱいだ", "天気が良い", "外出中だ"] },
    { en: "beat around the bush",  ja: "遠回しに言う",     wrong: ["単刀直入に言う", "黙り込む", "大声で言う"] },
    { en: "once in a blue moon",   ja: "ごくまれに",       wrong: ["毎日", "いつも", "二度と"] },
    { en: "hit the nail on the head", ja: "的を射る",      wrong: ["的外れだ", "誇張する", "ごまかす"] },
    { en: "a piece of cake",       ja: "とても簡単なこと", wrong: ["非常に難しいこと", "おいしい料理", "危険なこと"] },
    { en: "break the ice",         ja: "場を和ませる",     wrong: ["雰囲気を壊す", "沈黙する", "けんかする"] },
    { en: "cost an arm and a leg", ja: "大金がかかる",     wrong: ["ただ同然だ", "値切る", "安価だ"] },
    { en: "bite the bullet",       ja: "困難をぐっと耐える", wrong: ["簡単に逃げる", "あきらめる", "先延ばしする"] },
    { en: "let the cat out of the bag", ja: "うっかり秘密を漏らす", wrong: ["秘密を守る", "嘘をつく", "猫を飼う"] },
    { en: "the ball is in your court", ja: "次はあなた次第だ", wrong: ["もう決まった", "私の番だ", "終わった"] },
    { en: "once and for all",      ja: "きっぱりと",       wrong: ["何度も", "曖昧に", "一時的に"] },
    { en: "on the same page",      ja: "認識が一致して",   wrong: ["意見が対立して", "無関心で", "別行動で"] },
    { en: "cut corners",           ja: "手を抜く",         wrong: ["丁寧にやる", "遠回りする", "費用をかける"] },
    { en: "the last straw",        ja: "我慢の限界",       wrong: ["最初の警告", "ささいな喜び", "幸運の印"] },
    { en: "a blessing in disguise", ja: "不幸中の幸い",    wrong: ["単なる不幸", "予想通りの幸運", "呪い"] },
    { en: "burn the midnight oil", ja: "夜遅くまで働く",   wrong: ["早寝する", "さぼる", "昼寝する"] },
    { en: "spill the beans",       ja: "秘密を漏らす",     wrong: ["秘密を守る", "食べ物をこぼす", "嘘をつく"] },
    { en: "get cold feet",         ja: "怖気づく",         wrong: ["自信を持つ", "前進する", "興奮する"] },
    { en: "pull someone's leg",    ja: "からかう",         wrong: ["助ける", "責める", "真剣に話す"] },
    { en: "hit the sack",          ja: "寝る",             wrong: ["起きる", "殴る", "出かける"] },
    { en: "call it a day",         ja: "切り上げる",       wrong: ["始める", "徹夜する", "延長する"] },
    { en: "jump on the bandwagon", ja: "時流に乗る",       wrong: ["流れに逆らう", "孤立する", "先導する"] },
    { en: "the tip of the iceberg", ja: "氷山の一角",      wrong: ["全体像", "些細な問題", "結末"] },
    { en: "a dime a dozen",        ja: "ありふれた",       wrong: ["貴重な", "高価な", "珍しい"] },
    { en: "add fuel to the fire",  ja: "火に油を注ぐ",     wrong: ["事態を鎮める", "問題を解決する", "妥協する"] },
    { en: "back to the drawing board", ja: "一からやり直し", wrong: ["完成間近", "計画通り", "中止"] },
    { en: "barking up the wrong tree", ja: "見当違いをする", wrong: ["正解する", "的を射る", "慎重になる"] },
    { en: "the best of both worlds", ja: "一挙両得",       wrong: ["板挟み", "最悪の事態", "妥協"] },
    { en: "cut to the chase",      ja: "本題に入る",       wrong: ["前置きを長くする", "話をそらす", "黙る"] },
    { en: "down to earth",         ja: "現実的で気取らない", wrong: ["高慢な", "夢想的な", "神経質な"] },
    { en: "face the music",        ja: "報いを受ける",     wrong: ["責任を逃れる", "称賛される", "無視する"] },
    { en: "go the extra mile",     ja: "一段と努力する",   wrong: ["手を抜く", "最低限で済ます", "あきらめる"] },
    { en: "hit the books",         ja: "しっかり勉強する", wrong: ["遊ぶ", "さぼる", "休む"] },
    { en: "in the same boat",      ja: "同じ苦境にある",   wrong: ["有利な立場にある", "無関係だ", "対立している"] },
    { en: "kill two birds with one stone", ja: "一石二鳥", wrong: ["二度手間", "無駄骨", "失敗"] },
    { en: "leave no stone unturned", ja: "八方手を尽くす", wrong: ["何もしない", "適当にやる", "あきらめる"] },
    { en: "a long shot",           ja: "成功の見込みが薄いこと", wrong: ["確実なこと", "簡単なこと", "近道"] },
    { en: "miss the boat",         ja: "好機を逃す",       wrong: ["好機をつかむ", "間に合う", "先んじる"] },
    { en: "on thin ice",           ja: "危ない状況で",     wrong: ["安全な状況で", "余裕をもって", "順調に"] },
    { en: "out of the blue",       ja: "突然に",           wrong: ["予定通りに", "徐々に", "いつも通りに"] },
    { en: "peace of mind",         ja: "心の平穏",         wrong: ["不安", "混乱", "後悔"] },
    { en: "play it by ear",        ja: "臨機応変にやる",   wrong: ["綿密に計画する", "丸暗記する", "放棄する"] },
    { en: "pull yourself together", ja: "気を取り直す",    wrong: ["取り乱す", "あきらめる", "逃げる"] },
    { en: "see eye to eye",        ja: "意見が一致する",   wrong: ["対立する", "無視し合う", "誤解する"] },
    { en: "sit on the fence",      ja: "どっちつかずでいる", wrong: ["はっきり決める", "対立する", "逃げる"] },
    { en: "speak of the devil",    ja: "噂をすれば(本人が来る)", wrong: ["沈黙する", "内緒話をする", "中傷する"] },
    { en: "steal someone's thunder", ja: "手柄を横取りする", wrong: ["手柄を譲る", "応援する", "引き立てる"] },
    { en: "take it with a grain of salt", ja: "割り引いて聞く", wrong: ["鵜呑みにする", "激怒する", "無視する"] },
    { en: "the whole nine yards",  ja: "何から何まで",     wrong: ["ほんの一部", "要点だけ", "半分"] },
    { en: "throw in the towel",    ja: "降参する",         wrong: ["奮起する", "挑戦する", "勝つ"] },
    { en: "under the radar",       ja: "目立たないように", wrong: ["公然と", "派手に", "正面から"] },
    { en: "up in the air",         ja: "未定で",           wrong: ["確定して", "完了して", "中止で"] },
    { en: "when pigs fly",         ja: "あり得ないこと",   wrong: ["すぐに", "確実に", "日常的に"] },
    { en: "wrap your head around", ja: "(やっと)理解する", wrong: ["混乱する", "無視する", "忘れる"] },
    { en: "a slap on the wrist",   ja: "軽い罰",           wrong: ["厳罰", "賞賛", "警告なし"] },
    { en: "against the clock",     ja: "時間と競って",     wrong: ["余裕をもって", "のんびりと", "期限なしで"] },
    { en: "all ears",              ja: "熱心に聞いて",     wrong: ["上の空で", "無視して", "話して"] },
    { en: "at the drop of a hat",  ja: "すぐさま",         wrong: ["しぶしぶ", "後で", "決して"] },
    { en: "ballpark figure",       ja: "おおよその数字",   wrong: ["正確な数字", "最終結果", "合計"] },
    { en: "bend over backwards",   ja: "精一杯尽くす",     wrong: ["手を抜く", "断る", "妨げる"] },
    { en: "bite off more than you can chew", ja: "手に負えないことに手を出す", wrong: ["余裕を持つ", "慎重に選ぶ", "断る"] },
    { en: "by the skin of your teeth", ja: "かろうじて",   wrong: ["楽々と", "完全に", "失敗して"] },
    { en: "caught red-handed",     ja: "現行犯で捕まる",   wrong: ["無実が証明される", "見逃される", "逃げ切る"] },
    { en: "a chip on your shoulder", ja: "けんか腰",       wrong: ["穏やかさ", "謙虚さ", "無関心"] },
    { en: "cry over spilt milk",   ja: "済んだことを悔やむ", wrong: ["前向きに進む", "予防する", "喜ぶ"] },
    { en: "devil's advocate",      ja: "あえて反対意見を言う人", wrong: ["賛同者", "傍観者", "調停者"] },
    { en: "down the drain",        ja: "無駄になって",     wrong: ["報われて", "蓄えられて", "順調で"] },
    { en: "draw the line",         ja: "一線を引く",       wrong: ["妥協する", "際限なくやる", "無視する"] },
    { en: "an elephant in the room", ja: "触れにくい問題", wrong: ["些細な話題", "明白な解決", "軽い冗談"] },
    { en: "a fish out of water",   ja: "場違いで居心地が悪い", wrong: ["くつろいで", "適応して", "自信満々で"] },
    { en: "get the ball rolling",  ja: "物事を始動させる", wrong: ["中止する", "先延ばしする", "終える"] },
    { en: "give the benefit of the doubt", ja: "善意に解釈する", wrong: ["疑ってかかる", "責める", "無視する"] },
    { en: "go down in flames",     ja: "大失敗する",       wrong: ["大成功する", "無事に終わる", "続く"] },
    { en: "hands are tied",        ja: "身動きが取れない", wrong: ["自由に動ける", "権限がある", "余裕がある"] },
    { en: "hit rock bottom",       ja: "どん底に達する",   wrong: ["頂点に達する", "持ち直す", "安定する"] },
    { en: "in a nutshell",         ja: "要するに",         wrong: ["詳しく言うと", "例えば", "ところで"] },
    { en: "jump the gun",          ja: "早まったことをする", wrong: ["慎重に待つ", "遅れる", "計画する"] },
    { en: "keep your chin up",     ja: "気を落とさない",   wrong: ["落ち込む", "油断する", "あきらめる"] },
    { en: "know the ropes",        ja: "勝手を心得ている", wrong: ["不慣れだ", "迷っている", "失敗する"] },
    { en: "last but not least",    ja: "最後に大事なことだが", wrong: ["最初に", "どうでもいいが", "ついでに"] },
    { en: "let sleeping dogs lie", ja: "寝た子を起こすな", wrong: ["わざわざ波風を立てる", "問題を蒸し返す", "挑発する"] },
    { en: "make a long story short", ja: "手短に言えば",   wrong: ["詳しく述べると", "例えば", "遠回しに言うと"] },
    { en: "no pain no gain",       ja: "苦労なくして得るものなし", wrong: ["楽して儲ける", "努力は無駄", "運次第"] },
    { en: "not my cup of tea",     ja: "好みではない",     wrong: ["大好きだ", "得意だ", "初めてだ"] },
    { en: "off the hook",          ja: "窮地を脱して",     wrong: ["窮地に陥って", "責められて", "束縛されて"] },
    { en: "on cloud nine",         ja: "有頂天で",         wrong: ["絶望して", "平静で", "退屈して"] },
    { en: "on the ball",           ja: "有能で機敏で",     wrong: ["鈍くて", "怠けて", "混乱して"] },
    { en: "once bitten twice shy", ja: "一度失敗すると慎重になる", wrong: ["何度も同じ失敗をする", "動じない", "大胆になる"] },
    { en: "paint the town red",    ja: "繰り出して大いに遊ぶ", wrong: ["家でくつろぐ", "真面目に働く", "早寝する"] },
    { en: "par for the course",    ja: "想定内のこと",     wrong: ["異例のこと", "大成功", "大失敗"] },
    { en: "pull out all the stops", ja: "全力を尽くす",    wrong: ["手を抜く", "中断する", "様子を見る"] },
    { en: "put all your eggs in one basket", ja: "一か所に全てを賭ける", wrong: ["分散させる", "慎重に分ける", "何もしない"] },
    { en: "rain on someone's parade", ja: "水を差す",      wrong: ["盛り上げる", "祝福する", "応援する"] },
    { en: "read between the lines", ja: "言外の意味を読み取る", wrong: ["文字通りに受け取る", "読み飛ばす", "誤読する"] },
    { en: "ring a bell",           ja: "心当たりがある",   wrong: ["全く知らない", "忘れる", "無関係だ"] },
    { en: "rule of thumb",         ja: "経験則",           wrong: ["厳密な法則", "例外", "推測"] },
    { en: "run of the mill",       ja: "ありふれた",       wrong: ["並外れた", "高級な", "珍しい"] },
    { en: "sit tight",             ja: "じっと待つ",       wrong: ["すぐ動く", "逃げる", "急ぐ"] },
    { en: "take a rain check",     ja: "またの機会にする", wrong: ["即決する", "断固断る", "今すぐやる"] },
    { en: "the cream of the crop", ja: "えり抜きの最良",   wrong: ["最低のもの", "平均的なもの", "残り物"] },
    { en: "throw caution to the wind", ja: "大胆に思い切る", wrong: ["慎重に進める", "ためらう", "断念する"] },
    { en: "tie the knot",          ja: "結婚する",         wrong: ["離婚する", "婚約を破棄する", "出会う"] },
    { en: "turn a blind eye",      ja: "見て見ぬふりをする", wrong: ["厳しく取り締まる", "注意深く見る", "告発する"] },
    { en: "up to scratch",         ja: "水準に達して",     wrong: ["水準以下で", "完璧で", "未完成で"] },
    { en: "walk on eggshells",     ja: "細心の注意を払う", wrong: ["大胆に振る舞う", "無頓着でいる", "荒っぽくする"] },
    { en: "wear your heart on your sleeve", ja: "感情を隠さない", wrong: ["感情を隠す", "冷淡である", "嘘をつく"] },
    { en: "a piece of work",       ja: "厄介な人",         wrong: ["親切な人", "平凡な人", "芸術家"] },
    { en: "actions speak louder than words", ja: "言うより行動が大事", wrong: ["口先だけが大事", "沈黙は金", "言葉が全て"] },
    { en: "add insult to injury",  ja: "追い打ちをかける", wrong: ["慰める", "埋め合わせる", "和解する"] },
    { en: "ahead of the curve",    ja: "時代の先を行く",   wrong: ["時代遅れだ", "平均的だ", "後れを取る"] },
    { en: "all in your head",      ja: "気のせい",         wrong: ["現実だ", "証明済みだ", "他人のせい"] },
    { en: "apple of my eye",       ja: "最愛の人",         wrong: ["嫌いな人", "他人", "ライバル"] },
    { en: "around the clock",      ja: "24時間ぶっ通しで", wrong: ["ほんの一瞬", "日中だけ", "不定期に"] },
    { en: "at odds with",          ja: "〜と対立して",     wrong: ["〜と一致して", "〜と協力して", "〜と無関係で"] },
    { en: "his bark is worse than his bite", ja: "口ほど怖くない", wrong: ["見かけ以上に危険だ", "予測通りだ", "無害だ"] },
    { en: "beat a dead horse",     ja: "無駄なことを繰り返す", wrong: ["有意義に進める", "新しく始める", "潔く諦める"] },
    { en: "bend the rules",        ja: "規則を曲げる",     wrong: ["規則を厳守する", "規則を作る", "規則を廃止する"] },
    { en: "between a rock and a hard place", ja: "板挟みで", wrong: ["余裕があって", "安全圏で", "自由な状況で"] },
    { en: "bite your tongue",      ja: "言いたいのをこらえる", wrong: ["思ったまま言う", "大声で叫ぶ", "黙って去る"] },
    { en: "break new ground",      ja: "新境地を開く",     wrong: ["前例を踏襲する", "撤退する", "模倣する"] },
    { en: "bring to the table",    ja: "(議論に)提供する", wrong: ["取り上げる", "隠す", "放棄する"] },
    { en: "by and large",          ja: "概して",           wrong: ["例外的に", "厳密には", "たまに"] },
    { en: "call the shots",        ja: "采配を振る",       wrong: ["従う", "傍観する", "助言を仰ぐ"] },
    { en: "carved in stone",       ja: "確定して変更不可", wrong: ["流動的で", "未定で", "撤回可能で"] },
    { en: "a cash cow",            ja: "ドル箱(もうけ頭)", wrong: ["赤字事業", "初期投資", "負債"] },
    { en: "a change of heart",     ja: "心変わり",         wrong: ["不動の決意", "無関心", "記憶喪失"] },
    { en: "clear the air",         ja: "わだかまりを解く", wrong: ["緊張を高める", "対立を煽る", "沈黙する"] },
    { en: "close but no cigar",    ja: "惜しいが及ばず",   wrong: ["大成功", "大失敗", "余裕の達成"] },
    { en: "come full circle",      ja: "一巡して元に戻る", wrong: ["直進する", "途中で止まる", "逸れる"] },
    { en: "cost-effective",        ja: "費用対効果が高い", wrong: ["割高な", "無料の", "赤字の"] },
    { en: "cut from the same cloth", ja: "似た者同士",     wrong: ["正反対の", "無関係の", "対立する"] },
    { en: "a dead end",            ja: "行き詰まり",       wrong: ["突破口", "近道", "出発点"] },
    { en: "dodge a bullet",        ja: "危機を辛うじて回避する", wrong: ["危機に陥る", "正面突破する", "被害を受ける"] },
    { en: "down to the wire",      ja: "最後の最後まで",   wrong: ["早々と", "余裕で", "中途半端に"] },
    { en: "drag your feet",        ja: "ぐずぐずする",     wrong: ["てきぱき進める", "先んじる", "急ぐ"] },
    { en: "a drop in the bucket",  ja: "ほんのわずか",     wrong: ["大部分", "十分な量", "全体"] },
    { en: "easier said than done", ja: "言うは易く行うは難し", wrong: ["簡単に実行できる", "不可能だ", "口だけだ"] },
    { en: "fair and square",       ja: "正々堂々と",       wrong: ["ずるをして", "曖昧に", "偶然に"] },
    { en: "a feather in your cap", ja: "誇るべき業績",     wrong: ["不名誉", "失態", "日常茶飯事"] },
    { en: "fly off the handle",    ja: "かっとなる",       wrong: ["冷静を保つ", "我慢する", "受け流す"] },
    { en: "food for thought",      ja: "考える材料",       wrong: ["結論", "雑談", "娯楽"] },
    { en: "for the birds",         ja: "くだらない",       wrong: ["価値がある", "重要な", "真剣な"] },
    { en: "from scratch",          ja: "一から",           wrong: ["途中から", "完成品から", "他人任せで"] },
    { en: "get a kick out of",     ja: "〜を大いに楽しむ", wrong: ["〜に退屈する", "〜を嫌う", "〜を恐れる"] },
    { en: "get your act together", ja: "しっかりする",     wrong: ["だらける", "混乱する", "投げ出す"] },
    { en: "give someone a hand",   ja: "手を貸す",         wrong: ["邪魔をする", "見捨てる", "責める"] },
    { en: "go cold turkey",        ja: "きっぱりやめる",   wrong: ["徐々に減らす", "続ける", "増やす"] },
    { en: "go out on a limb",      ja: "あえて危険を冒す", wrong: ["安全策をとる", "傍観する", "逃げる"] },
    { en: "grasp at straws",       ja: "わらにもすがる",   wrong: ["余裕を持つ", "確実な手を打つ", "諦める"] },
    { en: "a green light",         ja: "(物事の)許可",     wrong: ["禁止", "警告", "保留"] },
    { en: "a hard pill to swallow", ja: "受け入れがたい事実", wrong: ["朗報", "簡単な選択", "些細な問題"] },
    { en: "have a ball",           ja: "大いに楽しむ",     wrong: ["退屈する", "苦労する", "失敗する"] },
    { en: "hold your horses",      ja: "焦るな",           wrong: ["急げ", "進め", "逃げろ"] },
    { en: "in hot water",          ja: "困った立場で",     wrong: ["安全な立場で", "有利な状況で", "くつろいで"] },
    { en: "in the loop",           ja: "情報を共有して",   wrong: ["蚊帳の外で", "無関心で", "孤立して"] },
    { en: "jump through hoops",    ja: "面倒な手続きを踏む", wrong: ["楽に済ます", "省略する", "拒否する"] },
    { en: "keep at bay",           ja: "寄せ付けない",     wrong: ["招き入れる", "放置する", "助長する"] },
    { en: "lay the groundwork",    ja: "下地を作る",       wrong: ["仕上げる", "放棄する", "破壊する"] },
    { en: "learn the ropes",       ja: "こつを覚える",     wrong: ["忘れる", "教える", "我流でやる"] },
    { en: "lose your touch",       ja: "腕が鈍る",         wrong: ["腕を上げる", "維持する", "初めて挑む"] },
    { en: "make ends meet",        ja: "何とか生計を立てる", wrong: ["贅沢に暮らす", "破産する", "大儲けする"] },
    { en: "a needle in a haystack", ja: "見つけにくいもの", wrong: ["見つけやすいもの", "ありふれたもの", "無価値なもの"] },
    { en: "off the cuff",          ja: "即興で",           wrong: ["入念に準備して", "慎重に", "丸暗記で"] },
    { en: "on the fence",          ja: "態度を決めかねて", wrong: ["きっぱり決めて", "対立して", "無関心で"] },
    { en: "on the right track",    ja: "順調に進んで",     wrong: ["道を誤って", "停滞して", "後退して"] },
    { en: "out of the woods",      ja: "危機を脱して",     wrong: ["危機の最中で", "安全圏外で", "行き詰まって"] },
    { en: "over the moon",         ja: "大喜びで",         wrong: ["落胆して", "平静で", "退屈して"] },
    { en: "pass the buck",         ja: "責任を転嫁する",   wrong: ["責任を取る", "引き受ける", "分担する"] },
    { en: "put your foot down",    ja: "断固たる態度をとる", wrong: ["妥協する", "優柔不断になる", "引き下がる"] },
    { en: "put your money where your mouth is", ja: "有言実行する", wrong: ["口だけで終わる", "賭けを断る", "黙る"] },
    { en: "raise the bar",         ja: "水準を引き上げる", wrong: ["水準を下げる", "据え置く", "放棄する"] },
    { en: "red tape",              ja: "お役所的な煩雑な手続き", wrong: ["迅速な対応", "簡略化", "特例"] },
    { en: "rock the boat",         ja: "波風を立てる",     wrong: ["現状を保つ", "和解する", "協調する"] },
    { en: "saved by the bell",     ja: "きわどいところで救われる", wrong: ["自力で切り抜ける", "失敗する", "手遅れになる"] },
    { en: "second nature",         ja: "身についた習性",   wrong: ["不慣れなこと", "苦手なこと", "一時的な癖"] },
    { en: "sell like hotcakes",    ja: "飛ぶように売れる", wrong: ["全く売れない", "在庫が残る", "値下げされる"] },
    { en: "set in stone",          ja: "確定して動かせない", wrong: ["流動的な", "暫定的な", "撤回可能な"] },
    { en: "a silver lining",       ja: "希望の光",         wrong: ["絶望", "前兆", "結末"] },
    { en: "smell a rat",           ja: "怪しいと感じる",   wrong: ["信用する", "見逃す", "安心する"] },
    { en: "spread yourself too thin", ja: "手を広げすぎる", wrong: ["一点に集中する", "余力を残す", "断る"] },
    { en: "take the bull by the horns", ja: "困難に正面から立ち向かう", wrong: ["問題を避ける", "先送りする", "人任せにする"] },
    { en: "the bottom line",       ja: "肝心な点",         wrong: ["些末な点", "前置き", "余談"] },
    { en: "the writing on the wall", ja: "不吉な前兆",     wrong: ["朗報", "確証", "偶然"] },
    { en: "think outside the box", ja: "既成概念にとらわれず考える", wrong: ["型通りに考える", "模倣する", "放棄する"] },
    { en: "throw under the bus",   ja: "身代わりにして見捨てる", wrong: ["かばう", "助ける", "称える"] },
    { en: "on the tip of my tongue", ja: "のどまで出かかっている", wrong: ["すっかり忘れた", "はっきり覚えている", "初耳だ"] },
    { en: "to make matters worse", ja: "さらに悪いことに", wrong: ["幸いにも", "要するに", "例えば"] },
    { en: "touch base",            ja: "連絡を取る",       wrong: ["連絡を絶つ", "無視する", "対立する"] },
    { en: "a train of thought",    ja: "思考の流れ",       wrong: ["結論", "雑念", "沈黙"] },
    { en: "twist someone's arm",   ja: "無理強いする",     wrong: ["自由にさせる", "説得をあきらめる", "助ける"] },
    { en: "up to par",             ja: "標準に達して",     wrong: ["標準以下で", "規格外で", "未完成で"] },
    { en: "a wild goose chase",    ja: "無駄な追求",       wrong: ["確実な成功", "近道", "容易な仕事"] },
    { en: "a storm in a teacup",   ja: "から騒ぎ",         wrong: ["重大な危機", "静かな日常", "順調な進行"] },
    { en: "the best laid plans",   ja: "周到な計画も狂うもの", wrong: ["計画は必ず成功する", "無計画が一番", "運がすべて"] },
    { en: "burning bridges",       ja: "後戻りできなくする", wrong: ["関係を修復する", "退路を確保する", "和解する"] },
    { en: "a slippery slope",      ja: "悪化の一途をたどる道", wrong: ["安全な道", "近道", "上り調子"] },
    { en: "the elephant's share",  ja: "大半の取り分",     wrong: ["わずかな取り分", "均等な分配", "残りかす"] },
    { en: "go against the grain",  ja: "性に合わない",     wrong: ["しっくりくる", "好みに合う", "従順である"] },
    { en: "the calm before the storm", ja: "嵐の前の静けさ", wrong: ["騒乱の最中", "平穏な日常", "終息の兆し"] },
    { en: "a wolf in sheep's clothing", ja: "偽善者(猫かぶり)", wrong: ["正直者", "臆病者", "英雄"] },
  ],
};
