// 英単語データ TOEICレベル別 (500 / 700 / 900)
// 各エントリ: { en: 英単語, ja: 正解の意味, choices: 誤答を含む4択候補(正解は自動で混ぜる) }
// choices には誤答を3つ書く。出題時に正解 ja を加えてシャッフルする。

const WORD_DATA = {
  500: [
    { en: "apple",     ja: "りんご",       wrong: ["みかん", "ぶどう", "いちご"] },
    { en: "travel",    ja: "旅行する",     wrong: ["働く", "食べる", "眠る"] },
    { en: "office",    ja: "事務所",       wrong: ["工場", "市場", "学校"] },
    { en: "buy",       ja: "買う",         wrong: ["売る", "貸す", "借りる"] },
    { en: "morning",   ja: "朝",           wrong: ["夜", "昼", "夕方"] },
    { en: "letter",    ja: "手紙",         wrong: ["電話", "新聞", "雑誌"] },
    { en: "happy",     ja: "幸せな",       wrong: ["悲しい", "怒った", "退屈な"] },
    { en: "doctor",    ja: "医者",         wrong: ["看護師", "教師", "警官"] },
    { en: "weather",   ja: "天気",         wrong: ["季節", "気温", "風景"] },
    { en: "ticket",    ja: "切符",         wrong: ["財布", "鍵", "硬貨"] },
    { en: "kitchen",   ja: "台所",         wrong: ["寝室", "浴室", "居間"] },
    { en: "answer",    ja: "答える",       wrong: ["尋ねる", "話す", "書く"] },
    { en: "begin",     ja: "始める",       wrong: ["終える", "続ける", "やめる"] },
    { en: "easy",      ja: "簡単な",       wrong: ["難しい", "重要な", "危険な"] },
    { en: "money",     ja: "お金",         wrong: ["時間", "場所", "仕事"] },
    { en: "garden",    ja: "庭",           wrong: ["屋根", "壁", "床"] },
    { en: "remember",  ja: "覚えている",   wrong: ["忘れる", "考える", "信じる"] },
    { en: "cheap",     ja: "安い",         wrong: ["高い", "新しい", "古い"] },
    { en: "bridge",    ja: "橋",           wrong: ["道", "駅", "港"] },
    { en: "invite",    ja: "招待する",     wrong: ["拒否する", "案内する", "紹介する"] },
  ],
  700: [
    { en: "schedule",   ja: "予定",        wrong: ["遅延", "会議", "休暇"] },
    { en: "increase",   ja: "増加する",    wrong: ["減少する", "維持する", "比較する"] },
    { en: "available",  ja: "利用できる",  wrong: ["不可能な", "高価な", "必要な"] },
    { en: "customer",   ja: "顧客",        wrong: ["同僚", "上司", "部下"] },
    { en: "deliver",    ja: "配達する",    wrong: ["注文する", "返品する", "製造する"] },
    { en: "manager",    ja: "管理者",      wrong: ["新入社員", "顧客", "訪問者"] },
    { en: "expense",    ja: "経費",        wrong: ["利益", "給料", "税金"] },
    { en: "improve",    ja: "改善する",    wrong: ["悪化させる", "中止する", "延期する"] },
    { en: "department", ja: "部署",        wrong: ["建物", "支店", "工場"] },
    { en: "contract",   ja: "契約",        wrong: ["請求書", "領収書", "見積もり"] },
    { en: "recommend",  ja: "推薦する",    wrong: ["批判する", "禁止する", "無視する"] },
    { en: "industry",   ja: "産業",        wrong: ["政府", "教育", "医療"] },
    { en: "reduce",     ja: "減らす",      wrong: ["増やす", "保つ", "数える"] },
    { en: "apply",      ja: "応募する",    wrong: ["辞退する", "解雇する", "昇進する"] },
    { en: "purchase",   ja: "購入する",    wrong: ["返却する", "交換する", "予約する"] },
    { en: "efficient",  ja: "効率的な",    wrong: ["非効率な", "高価な", "複雑な"] },
    { en: "warehouse",  ja: "倉庫",        wrong: ["事務所", "店舗", "工房"] },
    { en: "negotiate",  ja: "交渉する",    wrong: ["合意する", "中断する", "発表する"] },
    { en: "estimate",   ja: "見積もる",    wrong: ["支払う", "請求する", "確認する"] },
    { en: "colleague",  ja: "同僚",        wrong: ["顧客", "競合相手", "部下"] },
  ],
  900: [
    { en: "acquire",       ja: "獲得する",      wrong: ["放棄する", "分配する", "消費する"] },
    { en: "comprehensive", ja: "包括的な",      wrong: ["部分的な", "一時的な", "曖昧な"] },
    { en: "diminish",      ja: "減少させる",    wrong: ["増幅する", "維持する", "強化する"] },
    { en: "subsequent",    ja: "その後の",      wrong: ["以前の", "現在の", "同時の"] },
    { en: "allocate",      ja: "割り当てる",    wrong: ["回収する", "浪費する", "節約する"] },
    { en: "tentative",     ja: "暫定的な",      wrong: ["最終的な", "永続的な", "強制的な"] },
    { en: "prevail",       ja: "普及している",  wrong: ["衰退する", "禁止される", "孤立する"] },
    { en: "compliance",    ja: "法令順守",      wrong: ["違反", "免除", "申請"] },
    { en: "discrepancy",   ja: "食い違い",      wrong: ["一致", "増加", "合計"] },
    { en: "feasible",      ja: "実現可能な",    wrong: ["不可能な", "理論的な", "危険な"] },
    { en: "incentive",     ja: "動機付け",      wrong: ["障害", "罰則", "免除"] },
    { en: "mitigate",      ja: "緩和する",      wrong: ["悪化させる", "誇張する", "促進する"] },
    { en: "preliminary",   ja: "予備の",        wrong: ["最終の", "詳細な", "正式な"] },
    { en: "redundant",     ja: "余分な",        wrong: ["必須の", "希少な", "効率的な"] },
    { en: "sustain",       ja: "持続させる",    wrong: ["中断する", "破壊する", "縮小する"] },
    { en: "viable",        ja: "実行可能な",    wrong: ["無効な", "高価な", "複雑な"] },
    { en: "advocate",      ja: "提唱する",      wrong: ["反対する", "無視する", "撤回する"] },
    { en: "deteriorate",   ja: "悪化する",      wrong: ["改善する", "安定する", "回復する"] },
    { en: "lucrative",     ja: "もうかる",      wrong: ["損をする", "無償の", "高額な"] },
    { en: "scrutinize",    ja: "精査する",      wrong: ["見逃す", "推測する", "省略する"] },
  ],
};
